/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package lineage2.gameserver.network.serverpackets.components;

import java.util.NoSuchElementException;

/**
 * @author Mobius
 * @version $Revision: 1.0 $
 */
public enum NpcString
{
	/**
	 * Field NONE.
	 */
	NONE(-1),
	/**
	 * Field THE_RADIO_SIGNAL_DETECTOR_IS_RESPONDING_A_SUSPICIOUS_PILE_OF_STONES_CATCHES_YOUR_EYE.
	 */
	THE_RADIO_SIGNAL_DETECTOR_IS_RESPONDING_A_SUSPICIOUS_PILE_OF_STONES_CATCHES_YOUR_EYE(11453),
	/**
	 * Field ATT__ATTACK__S1__RO__ROGUE__S2.
	 */
	ATT__ATTACK__S1__RO__ROGUE__S2(46350),
	/**
	 * Field LISTEN_YOU_VILLAGERS_OUR_LIEGE_WHO_WILL_SOON_BECAME_A_LORD_HAS_DEFEATED_THE_HEADLESS_KNIGHT.
	 */
	LISTEN_YOU_VILLAGERS_OUR_LIEGE_WHO_WILL_SOON_BECAME_A_LORD_HAS_DEFEATED_THE_HEADLESS_KNIGHT(70854),
	/**
	 * Field S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_GLUDIO.
	 */
	S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_GLUDIO(70859),
	/**
	 * Field S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_DION.
	 */
	S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_DION(70959),
	/**
	 * Field S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_GIRAN.
	 */
	S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_GIRAN(71059),
	/**
	 * Field S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_OREN.
	 */
	S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_OREN(71259),
	/**
	 * Field S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_ADEN.
	 */
	S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_ADEN(71351),
	/**
	 * Field S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_SCHUTTGART.
	 */
	S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_SCHUTTGART(71459),
	/**
	 * Field S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_INNADRIL.
	 */
	S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_INNADRIL(71159),
	/**
	 * Field S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_RUNE.
	 */
	S1_HAS_BECOME_THE_LORD_OF_THE_TOWN_OF_RUNE(71659),
	/**
	 * Field PROTECT_THE_CATAPULT_OF_GLUDIO.
	 */
	PROTECT_THE_CATAPULT_OF_GLUDIO(72951),
	/**
	 * Field PROTECT_THE_CATAPULT_OF_DION.
	 */
	PROTECT_THE_CATAPULT_OF_DION(72952),
	/**
	 * Field PROTECT_THE_CATAPULT_OF_GIRAN.
	 */
	PROTECT_THE_CATAPULT_OF_GIRAN(72953),
	/**
	 * Field PROTECT_THE_CATAPULT_OF_OREN.
	 */
	PROTECT_THE_CATAPULT_OF_OREN(72954),
	/**
	 * Field PROTECT_THE_CATAPULT_OF_ADEN.
	 */
	PROTECT_THE_CATAPULT_OF_ADEN(72955),
	/**
	 * Field PROTECT_THE_CATAPULT_OF_INNADRIL.
	 */
	PROTECT_THE_CATAPULT_OF_INNADRIL(72956),
	/**
	 * Field PROTECT_THE_CATAPULT_OF_GODDARD.
	 */
	PROTECT_THE_CATAPULT_OF_GODDARD(72957),
	/**
	 * Field PROTECT_THE_CATAPULT_OF_RUNE.
	 */
	PROTECT_THE_CATAPULT_OF_RUNE(72958),
	/**
	 * Field PROTECT_THE_CATAPULT_OF_SCHUTTGART.
	 */
	PROTECT_THE_CATAPULT_OF_SCHUTTGART(72959),
	/**
	 * Field THE_CATAPULT_OF_GLUDIO_HAS_BEEN_DESTROYED.
	 */
	THE_CATAPULT_OF_GLUDIO_HAS_BEEN_DESTROYED(72961),
	/**
	 * Field THE_CATAPULT_OF_DION_HAS_BEEN_DESTROYED.
	 */
	THE_CATAPULT_OF_DION_HAS_BEEN_DESTROYED(72962),
	/**
	 * Field THE_CATAPULT_OF_GIRAN_HAS_BEEN_DESTROYED.
	 */
	THE_CATAPULT_OF_GIRAN_HAS_BEEN_DESTROYED(72963),
	/**
	 * Field THE_CATAPULT_OF_OREN_HAS_BEEN_DESTROYED.
	 */
	THE_CATAPULT_OF_OREN_HAS_BEEN_DESTROYED(72964),
	/**
	 * Field THE_CATAPULT_OF_ADEN_HAS_BEEN_DESTROYED.
	 */
	THE_CATAPULT_OF_ADEN_HAS_BEEN_DESTROYED(72965),
	/**
	 * Field THE_CATAPULT_OF_INNADRIL_HAS_BEEN_DESTROYED.
	 */
	THE_CATAPULT_OF_INNADRIL_HAS_BEEN_DESTROYED(72966),
	/**
	 * Field THE_CATAPULT_OF_GODDARD_HAS_BEEN_DESTROYED.
	 */
	THE_CATAPULT_OF_GODDARD_HAS_BEEN_DESTROYED(72967),
	/**
	 * Field THE_CATAPULT_OF_RUNE_HAS_BEEN_DESTROYED.
	 */
	THE_CATAPULT_OF_RUNE_HAS_BEEN_DESTROYED(72968),
	/**
	 * Field THE_CATAPULT_OF_SCHUTTGART_HAS_BEEN_DESTROYED.
	 */
	THE_CATAPULT_OF_SCHUTTGART_HAS_BEEN_DESTROYED(72969),
	/**
	 * Field PROTECT_THE_SUPPLIES_SAFE_OF_GLUDIO.
	 */
	PROTECT_THE_SUPPLIES_SAFE_OF_GLUDIO(73051),
	/**
	 * Field PROTECT_THE_SUPPLIES_SAFE_OF_DION.
	 */
	PROTECT_THE_SUPPLIES_SAFE_OF_DION(73052),
	/**
	 * Field PROTECT_THE_SUPPLIES_SAFE_OF_GIRAN.
	 */
	PROTECT_THE_SUPPLIES_SAFE_OF_GIRAN(73053),
	/**
	 * Field PROTECT_THE_SUPPLIES_SAFE_OF_OREN.
	 */
	PROTECT_THE_SUPPLIES_SAFE_OF_OREN(73054),
	/**
	 * Field PROTECT_THE_SUPPLIES_SAFE_OF_ADEN.
	 */
	PROTECT_THE_SUPPLIES_SAFE_OF_ADEN(73055),
	/**
	 * Field PROTECT_THE_SUPPLIES_SAFE_OF_INNADRIL.
	 */
	PROTECT_THE_SUPPLIES_SAFE_OF_INNADRIL(73056),
	/**
	 * Field PROTECT_THE_SUPPLIES_SAFE_OF_GODDARD.
	 */
	PROTECT_THE_SUPPLIES_SAFE_OF_GODDARD(73057),
	/**
	 * Field PROTECT_THE_SUPPLIES_SAFE_OF_RUNE.
	 */
	PROTECT_THE_SUPPLIES_SAFE_OF_RUNE(73058),
	/**
	 * Field PROTECT_THE_SUPPLIES_SAFE_OF_SCHUTTGART.
	 */
	PROTECT_THE_SUPPLIES_SAFE_OF_SCHUTTGART(73059),
	/**
	 * Field THE_SUPPLIES_SAFE_OF_GLUDIO_HAS_BEEN_DESTROYED.
	 */
	THE_SUPPLIES_SAFE_OF_GLUDIO_HAS_BEEN_DESTROYED(73061),
	/**
	 * Field THE_SUPPLIES_SAFE_OF_DION_HAS_BEEN_DESTROYED.
	 */
	THE_SUPPLIES_SAFE_OF_DION_HAS_BEEN_DESTROYED(73062),
	/**
	 * Field THE_SUPPLIES_SAFE_OF_GIRAN_HAS_BEEN_DESTROYED.
	 */
	THE_SUPPLIES_SAFE_OF_GIRAN_HAS_BEEN_DESTROYED(73063),
	/**
	 * Field THE_SUPPLIES_SAFE_OF_OREN_HAS_BEEN_DESTROYED.
	 */
	THE_SUPPLIES_SAFE_OF_OREN_HAS_BEEN_DESTROYED(73064),
	/**
	 * Field THE_SUPPLIES_SAFE_OF_ADEN_HAS_BEEN_DESTROYED.
	 */
	THE_SUPPLIES_SAFE_OF_ADEN_HAS_BEEN_DESTROYED(73065),
	/**
	 * Field THE_SUPPLIES_SAFE_OF_INNADRIL_HAS_BEEN_DESTROYED.
	 */
	THE_SUPPLIES_SAFE_OF_INNADRIL_HAS_BEEN_DESTROYED(73066),
	/**
	 * Field THE_SUPPLIES_SAFE_OF_GODDARD_HAS_BEEN_DESTROYED.
	 */
	THE_SUPPLIES_SAFE_OF_GODDARD_HAS_BEEN_DESTROYED(73067),
	/**
	 * Field THE_SUPPLIES_SAFE_OF_RUNE_HAS_BEEN_DESTROYED.
	 */
	THE_SUPPLIES_SAFE_OF_RUNE_HAS_BEEN_DESTROYED(73068),
	/**
	 * Field THE_SUPPLIES_SAFE_OF_SCHUTTGART_HAS_BEEN_DESTROYED.
	 */
	THE_SUPPLIES_SAFE_OF_SCHUTTGART_HAS_BEEN_DESTROYED(73069),
	/**
	 * Field PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_GLUDIO.
	 */
	PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_GLUDIO(73151),
	/**
	 * Field PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_DION.
	 */
	PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_DION(73152),
	/**
	 * Field PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_GIRAN.
	 */
	PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_GIRAN(73153),
	/**
	 * Field PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_OREN.
	 */
	PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_OREN(73154),
	/**
	 * Field PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_ADEN.
	 */
	PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_ADEN(73155),
	/**
	 * Field PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_INNADRIL.
	 */
	PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_INNADRIL(73156),
	/**
	 * Field PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_GODDARD.
	 */
	PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_GODDARD(73157),
	/**
	 * Field PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_RUNE.
	 */
	PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_RUNE(73158),
	/**
	 * Field PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_SCHUTTGART.
	 */
	PROTECT_THE_MILITARY_ASSOCIATION_LEADER_OF_SCHUTTGART(73159),
	/**
	 * Field THE_MILITARY_ASSOCIATION_LEADER_OF_GLUDIO_IS_DEAD.
	 */
	THE_MILITARY_ASSOCIATION_LEADER_OF_GLUDIO_IS_DEAD(73161),
	/**
	 * Field THE_MILITARY_ASSOCIATION_LEADER_OF_DION_IS_DEAD.
	 */
	THE_MILITARY_ASSOCIATION_LEADER_OF_DION_IS_DEAD(73162),
	/**
	 * Field THE_MILITARY_ASSOCIATION_LEADER_OF_GIRAN_IS_DEAD.
	 */
	THE_MILITARY_ASSOCIATION_LEADER_OF_GIRAN_IS_DEAD(73163),
	/**
	 * Field THE_MILITARY_ASSOCIATION_LEADER_OF_OREN_IS_DEAD.
	 */
	THE_MILITARY_ASSOCIATION_LEADER_OF_OREN_IS_DEAD(73164),
	/**
	 * Field THE_MILITARY_ASSOCIATION_LEADER_OF_ADEN_IS_DEAD.
	 */
	THE_MILITARY_ASSOCIATION_LEADER_OF_ADEN_IS_DEAD(73165),
	/**
	 * Field THE_MILITARY_ASSOCIATION_LEADER_OF_INNADRIL_IS_DEAD.
	 */
	THE_MILITARY_ASSOCIATION_LEADER_OF_INNADRIL_IS_DEAD(73166),
	/**
	 * Field THE_MILITARY_ASSOCIATION_LEADER_OF_GODDARD_IS_DEAD.
	 */
	THE_MILITARY_ASSOCIATION_LEADER_OF_GODDARD_IS_DEAD(73167),
	/**
	 * Field THE_MILITARY_ASSOCIATION_LEADER_OF_RUNE_IS_DEAD.
	 */
	THE_MILITARY_ASSOCIATION_LEADER_OF_RUNE_IS_DEAD(73168),
	/**
	 * Field THE_MILITARY_ASSOCIATION_LEADER_OF_SCHUTTGART_IS_DEAD.
	 */
	THE_MILITARY_ASSOCIATION_LEADER_OF_SCHUTTGART_IS_DEAD(73169),
	/**
	 * Field PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GLUDIO.
	 */
	PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GLUDIO(73251),
	/**
	 * Field PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_DION.
	 */
	PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_DION(73252),
	/**
	 * Field PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GIRAN.
	 */
	PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GIRAN(73253),
	/**
	 * Field PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_OREN.
	 */
	PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_OREN(73254),
	/**
	 * Field PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_ADEN.
	 */
	PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_ADEN(73255),
	/**
	 * Field PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_INNADRIL.
	 */
	PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_INNADRIL(73256),
	/**
	 * Field PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GODDARD.
	 */
	PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GODDARD(73257),
	/**
	 * Field PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_RUNE.
	 */
	PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_RUNE(73258),
	/**
	 * Field PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_SCHUTTGART.
	 */
	PROTECT_THE_RELIGIOUS_ASSOCIATION_LEADER_OF_SCHUTTGART(73259),
	/**
	 * Field THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GLUDIO_IS_DEAD.
	 */
	THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GLUDIO_IS_DEAD(73261),
	/**
	 * Field THE_RELIGIOUS_ASSOCIATION_LEADER_OF_DION_IS_DEAD.
	 */
	THE_RELIGIOUS_ASSOCIATION_LEADER_OF_DION_IS_DEAD(73262),
	/**
	 * Field THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GIRAN_IS_DEAD.
	 */
	THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GIRAN_IS_DEAD(73263),
	/**
	 * Field THE_RELIGIOUS_ASSOCIATION_LEADER_OF_OREN_IS_DEAD.
	 */
	THE_RELIGIOUS_ASSOCIATION_LEADER_OF_OREN_IS_DEAD(73264),
	/**
	 * Field THE_RELIGIOUS_ASSOCIATION_LEADER_OF_ADEN_IS_DEAD.
	 */
	THE_RELIGIOUS_ASSOCIATION_LEADER_OF_ADEN_IS_DEAD(73265),
	/**
	 * Field THE_RELIGIOUS_ASSOCIATION_LEADER_OF_INNADRIL_IS_DEAD.
	 */
	THE_RELIGIOUS_ASSOCIATION_LEADER_OF_INNADRIL_IS_DEAD(73266),
	/**
	 * Field THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GODDARD_IS_DEAD.
	 */
	THE_RELIGIOUS_ASSOCIATION_LEADER_OF_GODDARD_IS_DEAD(73267),
	/**
	 * Field THE_RELIGIOUS_ASSOCIATION_LEADER_OF_RUNE_IS_DEAD.
	 */
	THE_RELIGIOUS_ASSOCIATION_LEADER_OF_RUNE_IS_DEAD(73268),
	/**
	 * Field THE_RELIGIOUS_ASSOCIATION_LEADER_OF_SCHUTTGART_IS_DEAD.
	 */
	THE_RELIGIOUS_ASSOCIATION_LEADER_OF_SCHUTTGART_IS_DEAD(73269),
	/**
	 * Field PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_GLUDIO.
	 */
	PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_GLUDIO(73351),
	/**
	 * Field PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_DION.
	 */
	PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_DION(73352),
	/**
	 * Field PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_GIRAN.
	 */
	PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_GIRAN(73353),
	/**
	 * Field PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_OREN.
	 */
	PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_OREN(73354),
	/**
	 * Field PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_ADEN.
	 */
	PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_ADEN(73355),
	/**
	 * Field PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_INNADRIL.
	 */
	PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_INNADRIL(73356),
	/**
	 * Field PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_GODDARD.
	 */
	PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_GODDARD(73357),
	/**
	 * Field PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_RUNE.
	 */
	PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_RUNE(73358),
	/**
	 * Field PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_SCHUTTGART.
	 */
	PROTECT_THE_ECONOMIC_ASSOCIATION_LEADER_OF_SCHUTTGART(73359),
	/**
	 * Field THE_ECONOMIC_ASSOCIATION_LEADER_OF_GLUDIO_IS_DEAD.
	 */
	THE_ECONOMIC_ASSOCIATION_LEADER_OF_GLUDIO_IS_DEAD(73361),
	/**
	 * Field THE_ECONOMIC_ASSOCIATION_LEADER_OF_DION_IS_DEAD.
	 */
	THE_ECONOMIC_ASSOCIATION_LEADER_OF_DION_IS_DEAD(73362),
	/**
	 * Field THE_ECONOMIC_ASSOCIATION_LEADER_OF_GIRAN_IS_DEAD.
	 */
	THE_ECONOMIC_ASSOCIATION_LEADER_OF_GIRAN_IS_DEAD(73363),
	/**
	 * Field THE_ECONOMIC_ASSOCIATION_LEADER_OF_OREN_IS_DEAD.
	 */
	THE_ECONOMIC_ASSOCIATION_LEADER_OF_OREN_IS_DEAD(73364),
	/**
	 * Field THE_ECONOMIC_ASSOCIATION_LEADER_OF_ADEN_IS_DEAD.
	 */
	THE_ECONOMIC_ASSOCIATION_LEADER_OF_ADEN_IS_DEAD(73365),
	/**
	 * Field THE_ECONOMIC_ASSOCIATION_LEADER_OF_INNADRIL_IS_DEAD.
	 */
	THE_ECONOMIC_ASSOCIATION_LEADER_OF_INNADRIL_IS_DEAD(73366),
	/**
	 * Field THE_ECONOMIC_ASSOCIATION_LEADER_OF_GODDARD_IS_DEAD.
	 */
	THE_ECONOMIC_ASSOCIATION_LEADER_OF_GODDARD_IS_DEAD(73367),
	/**
	 * Field THE_ECONOMIC_ASSOCIATION_LEADER_OF_RUNE_IS_DEAD.
	 */
	THE_ECONOMIC_ASSOCIATION_LEADER_OF_RUNE_IS_DEAD(73368),
	/**
	 * Field THE_ECONOMIC_ASSOCIATION_LEADER_OF_SCHUTTGART_IS_DEAD.
	 */
	THE_ECONOMIC_ASSOCIATION_LEADER_OF_SCHUTTGART_IS_DEAD(73369),
	/**
	 * Field DEFEAT_S1_ENEMY_KNIGHTS.
	 */
	DEFEAT_S1_ENEMY_KNIGHTS(73451),
	/**
	 * Field YOU_HAVE_DEFEATED_S2_OF_S1_KNIGHTS.
	 */
	YOU_HAVE_DEFEATED_S2_OF_S1_KNIGHTS(73461),
	/**
	 * Field YOU_WEAKENED_THE_ENEMYS_DEFENSE.
	 */
	YOU_WEAKENED_THE_ENEMYS_DEFENSE(73462),
	/**
	 * Field DEFEAT_S1_WARRIORS_AND_ROGUES.
	 */
	DEFEAT_S1_WARRIORS_AND_ROGUES(73551),
	/**
	 * Field YOU_HAVE_DEFEATED_S2_OF_S1_WARRIORS_AND_ROGUES.
	 */
	YOU_HAVE_DEFEATED_S2_OF_S1_WARRIORS_AND_ROGUES(73561),
	/**
	 * Field YOU_WEAKENED_THE_ENEMYS_ATTACK.
	 */
	YOU_WEAKENED_THE_ENEMYS_ATTACK(73562),
	/**
	 * Field DEFEAT_S1_WIZARDS_AND_SUMMONERS.
	 */
	DEFEAT_S1_WIZARDS_AND_SUMMONERS(73651),
	/**
	 * Field YOU_HAVE_DEFEATED_S2_OF_S1_ENEMIES.
	 */
	YOU_HAVE_DEFEATED_S2_OF_S1_ENEMIES(73661),
	/**
	 * Field YOU_WEAKENED_THE_ENEMYS_MAGIC.
	 */
	YOU_WEAKENED_THE_ENEMYS_MAGIC(73662),
	/**
	 * Field DEFEAT_S1_HEALERS_AND_BUFFERS.
	 */
	DEFEAT_S1_HEALERS_AND_BUFFERS(73751),
	/**
	 * Field YOU_HAVE_DEFEATED_S2_OF_S1_HEALERS_AND_BUFFERS.
	 */
	YOU_HAVE_DEFEATED_S2_OF_S1_HEALERS_AND_BUFFERS(73761),
	/**
	 * Field YOU_HAVE_WEAKENED_THE_ENEMYS_SUPPORT.
	 */
	YOU_HAVE_WEAKENED_THE_ENEMYS_SUPPORT(73762),
	/**
	 * Field DEFEAT_S1_WARSMITHS_AND_OVERLORDS.
	 */
	DEFEAT_S1_WARSMITHS_AND_OVERLORDS(73851),
	/**
	 * Field YOU_HAVE_DEFEATED_S2_OF_S1_WARSMITHS_AND_OVERLORDS.
	 */
	YOU_HAVE_DEFEATED_S2_OF_S1_WARSMITHS_AND_OVERLORDS(73861),
	/**
	 * Field YOU_DESTROYED_THE_ENEMYS_PROFESSIONALS.
	 */
	YOU_DESTROYED_THE_ENEMYS_PROFESSIONALS(73862),
	/**
	 * Field RETURN.
	 */
	RETURN(1000170),
	/**
	 * Field EVENT_NUMBER.
	 */
	EVENT_NUMBER(1000172),
	/**
	 * Field FIRST_PRIZE.
	 */
	FIRST_PRIZE(1000173),
	/**
	 * Field SECOND_PRIZE.
	 */
	SECOND_PRIZE(1000174),
	/**
	 * Field THIRD_PRIZE.
	 */
	THIRD_PRIZE(1000175),
	/**
	 * Field FOURTH_PRIZE.
	 */
	FOURTH_PRIZE(1000176),
	/**
	 * Field THERE_HAS_BEEN_NO_WINNING_LOTTERY_TICKET.
	 */
	THERE_HAS_BEEN_NO_WINNING_LOTTERY_TICKET(1000177),
	/**
	 * Field YOUR_LUCKY_NUMBERS_HAVE_BEEN_SELECTED_ABOVE.
	 */
	YOUR_LUCKY_NUMBERS_HAVE_BEEN_SELECTED_ABOVE(1000179),
	/**
	 * Field PREPARE_TO_DIE_FOREIGN_INVADERS_I_AM_GUSTAV_THE_ETERNAL_RULER_OF_THIS_FORTRESS_AND_I_HAVE_TAKEN_UP_MY_SWORD_TO_REPEL_THEE.
	 */
	PREPARE_TO_DIE_FOREIGN_INVADERS_I_AM_GUSTAV_THE_ETERNAL_RULER_OF_THIS_FORTRESS_AND_I_HAVE_TAKEN_UP_MY_SWORD_TO_REPEL_THEE(1000275),
	/**
	 * Field GLORY_TO_ADEN_THE_KINGDOM_OF_THE_LION_GLORY_TO_SIR_GUSTAV_OUR_IMMORTAL_LORD.
	 */
	GLORY_TO_ADEN_THE_KINGDOM_OF_THE_LION_GLORY_TO_SIR_GUSTAV_OUR_IMMORTAL_LORD(1000276),
	/**
	 * Field SOLDIERS_OF_GUSTAV_GO_FORTH_AND_DESTROY_THE_INVADERS.
	 */
	SOLDIERS_OF_GUSTAV_GO_FORTH_AND_DESTROY_THE_INVADERS(1000277),
	/**
	 * Field THIS_IS_UNBELIEVABLE_HAVE_I_REALLY_BEEN_DEFEATED_I_SHALL_RETURN_AND_TAKE_YOUR_HEAD.
	 */
	THIS_IS_UNBELIEVABLE_HAVE_I_REALLY_BEEN_DEFEATED_I_SHALL_RETURN_AND_TAKE_YOUR_HEAD(1000278),
	/**
	 * Field COULD_IT_BE_THAT_I_HAVE_REACHED_MY_END_I_CANNOT_DIE_WITHOUT_HONOR_WITHOUT_THE_PERMISSION_OF_SIR_GUSTAV.
	 */
	COULD_IT_BE_THAT_I_HAVE_REACHED_MY_END_I_CANNOT_DIE_WITHOUT_HONOR_WITHOUT_THE_PERMISSION_OF_SIR_GUSTAV(1000279),
	/**
	 * Field AH_THE_BITTER_TASTE_OF_DEFEAT_I_FEAR_MY_TORMENTS_ARE_NOT_OVER.
	 */
	AH_THE_BITTER_TASTE_OF_DEFEAT_I_FEAR_MY_TORMENTS_ARE_NOT_OVER(1000280),
	/**
	 * Field THIS_WORLD_WILL_SOON_BE_ANNIHILATED.
	 */
	THIS_WORLD_WILL_SOON_BE_ANNIHILATED(1000303),
	/**
	 * Field ALL_IS_LOST__PREPARE_TO_MEET_THE_GODDESS_OF_DEATH.
	 */
	ALL_IS_LOST__PREPARE_TO_MEET_THE_GODDESS_OF_DEATH(1000415),
	/**
	 * Field ALL_IS_LOST__THE_PROPHECY_OF_DESTRUCTION_HAS_BEEN_FULFILLED.
	 */
	ALL_IS_LOST__THE_PROPHECY_OF_DESTRUCTION_HAS_BEEN_FULFILLED(1000416),
	/**
	 * Field THE_END_OF_TIME_HAS_COME__THE_PROPHECY_OF_DESTRUCTION_HAS_BEEN_FULFILLED.
	 */
	THE_END_OF_TIME_HAS_COME__THE_PROPHECY_OF_DESTRUCTION_HAS_BEEN_FULFILLED(1000417),
	/**
	 * Field THE_DAY_OF_JUDGMENT_IS_NEAR.
	 */
	THE_DAY_OF_JUDGMENT_IS_NEAR(1000305),
	/**
	 * Field THE_PROPHECY_OF_DARKNESS_HAS_BEEN_FULFILLED.
	 */
	THE_PROPHECY_OF_DARKNESS_HAS_BEEN_FULFILLED(1000421),
	/**
	 * Field AS_FORETOLD_IN_THE_PROPHECY_OF_DARKNESS__THE_ERA_OF_CHAOS_HAS_BEGUN.
	 */
	AS_FORETOLD_IN_THE_PROPHECY_OF_DARKNESS__THE_ERA_OF_CHAOS_HAS_BEGUN(1000422),
	/**
	 * Field THE_PROPHECY_OF_DARKNESS_HAS_COME_TO_PASS.
	 */
	THE_PROPHECY_OF_DARKNESS_HAS_COME_TO_PASS(1000423),
	/**
	 * Field I_BESTOW_UPON_YOU_A_BLESSING.
	 */
	I_BESTOW_UPON_YOU_A_BLESSING(1000306),
	/**
	 * Field S1__I_GIVE_YOU_THE_BLESSING_OF_PROPHECY.
	 */
	S1__I_GIVE_YOU_THE_BLESSING_OF_PROPHECY(1000424),
	/**
	 * Field HERALD_OF_THE_NEW_ERA__OPEN_YOUR_EYES.
	 */
	HERALD_OF_THE_NEW_ERA__OPEN_YOUR_EYES(1000426),
	/**
	 * Field S1__I_BESTOW_UPON_YOU_THE_AUTHORITY_OF_THE_ABYSS.
	 */
	S1__I_BESTOW_UPON_YOU_THE_AUTHORITY_OF_THE_ABYSS(1000425),
	/**
	 * Field YOU_DONT_HAVE_ANY_HOPE__YOUR_END_HAS_COME.
	 */
	YOU_DONT_HAVE_ANY_HOPE__YOUR_END_HAS_COME(1000420),
	/**
	 * Field A_CURSE_UPON_YOU.
	 */
	A_CURSE_UPON_YOU(1000304),
	/**
	 * Field S1__YOU_BRING_AN_ILL_WIND.
	 */
	S1__YOU_BRING_AN_ILL_WIND(1000418),
	/**
	 * Field S1__YOU_MIGHT_AS_WELL_GIVE_UP.
	 */
	S1__YOU_MIGHT_AS_WELL_GIVE_UP(1000419),
	/**
	 * Field THE_DEFENDERS_OF_S1_CASTLE_WILL_BE_TELEPORTED_TO_THE_INNER_CASTLE.
	 */
	THE_DEFENDERS_OF_S1_CASTLE_WILL_BE_TELEPORTED_TO_THE_INNER_CASTLE(1000443),
	/**
	 * Field COMPETITION.
	 */
	COMPETITION(1000507),
	/**
	 * Field SEAL_VALIDATION.
	 */
	SEAL_VALIDATION(1000508),
	/**
	 * Field PREPARATION.
	 */
	PREPARATION(1000509),
	/**
	 * Field DUSK.
	 */
	DUSK(1000510),
	/**
	 * Field DAWN.
	 */
	DAWN(1000511),
	/**
	 * Field NO_OWNER.
	 */
	NO_OWNER(1000512),
	/**
	 * Field __UNREGISTERED__.
	 */
	__UNREGISTERED__(1000495),
	/**
	 * Field VALAKAS_ARROGAANT_FOOL_YOU_DARE_TO_CHALLENGE_ME.
	 */
	VALAKAS_ARROGAANT_FOOL_YOU_DARE_TO_CHALLENGE_ME(1000519),
	/**
	 * Field VALAKAS_FINDS_YOU_ATTACKS_ANNOYING_SILENCE.
	 */
	VALAKAS_FINDS_YOU_ATTACKS_ANNOYING_SILENCE(1801071),
	/**
	 * Field VALAKAS_PDEF_ISM_DECREACED_SLICED_DASH.
	 */
	VALAKAS_PDEF_ISM_DECREACED_SLICED_DASH(1801072),
	/**
	 * Field VALAKAS_OVERWHELMED_BY_ATTACK_NOW_TIME_ATTACK.
	 */
	VALAKAS_OVERWHELMED_BY_ATTACK_NOW_TIME_ATTACK(1801073),
	/**
	 * Field VALAKAS_RANGED_ATTACKS_PROVOKED.
	 */
	VALAKAS_RANGED_ATTACKS_PROVOKED(1801074),
	/**
	 * Field VALAKAS_HEIGHTENED_BY_COUNTERATTACKS.
	 */
	VALAKAS_HEIGHTENED_BY_COUNTERATTACKS(1801075),
	/**
	 * Field VALAKAS_RANGED_ATTACKS_ENRAGED_TARGET_FREE.
	 */
	VALAKAS_RANGED_ATTACKS_ENRAGED_TARGET_FREE(1801076),
	/**
	 * Field VALAKAS_THE_EVIL_FIRE_DRAGON_VALAKAS_DEFEATED.
	 */
	VALAKAS_THE_EVIL_FIRE_DRAGON_VALAKAS_DEFEATED(1900151),
	/**
	 * Field ANTHARAS_YOU_CANNOT_HOPE_TO_DEFEAT_ME.
	 */
	ANTHARAS_YOU_CANNOT_HOPE_TO_DEFEAT_ME(1000520),
	/**
	 * Field ANTHARAS_THE_EVIL_LAND_DRAGON_ANTHARAS_DEFEATED.
	 */
	ANTHARAS_THE_EVIL_LAND_DRAGON_ANTHARAS_DEFEATED(1900150),
	/**
	 * Field ANTHARAS_EARTH_ENERGY_GATHERING_LEGS.
	 */
	ANTHARAS_EARTH_ENERGY_GATHERING_LEGS(1900155),
	/**
	 * Field ANTHARAS_STARTS_ABSORB_EARTH_ENERGY.
	 */
	ANTHARAS_STARTS_ABSORB_EARTH_ENERGY(1900156),
	/**
	 * Field ANTHARAS_RAISES_ITS_THICK_TAIL.
	 */
	ANTHARAS_RAISES_ITS_THICK_TAIL(1900157),
	/**
	 * Field ANTHARAS_YOU_ARE_OVERCOME_.
	 */
	ANTHARAS_YOU_ARE_OVERCOME_(1900158),
	/**
	 * Field ANTHARAS_EYES_FILLED_WITH_RAGE.
	 */
	ANTHARAS_EYES_FILLED_WITH_RAGE(1900159),
	/**
	 * Field REQUIEM_OF_HATRED.
	 */
	REQUIEM_OF_HATRED(1000522),
	/**
	 * Field FUGUE_OF_JUBILATION.
	 */
	FUGUE_OF_JUBILATION(1000523),
	/**
	 * Field FRENETIC_TOCCATA.
	 */
	FRENETIC_TOCCATA(1000524),
	/**
	 * Field HYPNOTIC_MAZURKA.
	 */
	HYPNOTIC_MAZURKA(1000525),
	/**
	 * Field MOURNFUL_CHORALE_PRELUDE.
	 */
	MOURNFUL_CHORALE_PRELUDE(1000526),
	/**
	 * Field RONDO_OF_SOLITUDE.
	 */
	RONDO_OF_SOLITUDE(1000527),
	/**
	 * Field GLUDIO.
	 */
	GLUDIO(1001001),
	/**
	 * Field DION.
	 */
	DION(1001002),
	/**
	 * Field GIRAN.
	 */
	GIRAN(1001003),
	/**
	 * Field OREN.
	 */
	OREN(1001004),
	/**
	 * Field ADEN.
	 */
	ADEN(1001005),
	/**
	 * Field INNADRIL.
	 */
	INNADRIL(1001006),
	/**
	 * Field THE_KINGDOM_OF_ELMORE.
	 */
	THE_KINGDOM_OF_ELMORE(1001100),
	/**
	 * Field GODDARD.
	 */
	GODDARD(1001007),
	/**
	 * Field RUNE.
	 */
	RUNE(1001008),
	/**
	 * Field SCHUTTGART.
	 */
	SCHUTTGART(1001009),
	/**
	 * Field A_BLACK_MOON_NOW_DO_YOU_UNDERSTAND_THAT_HE_HAS_OPENED_HIS_EYES.
	 */
	A_BLACK_MOON_NOW_DO_YOU_UNDERSTAND_THAT_HE_HAS_OPENED_HIS_EYES(1010221),
	/**
	 * Field CLOUDS_OF_BLOOD_ARE_GATHERING_SOON_IT_WILL_START_TO_RAIN_THE_RAIN_OF_CRIMSON_BLOOD.
	 */
	CLOUDS_OF_BLOOD_ARE_GATHERING_SOON_IT_WILL_START_TO_RAIN_THE_RAIN_OF_CRIMSON_BLOOD(1010222),
	/**
	 * Field WHILE_THE_FOOLISH_LIGHT_WAS_ASLEEP_THE_DARKNESS_WILL_AWAKEN_FIRST_UH.
	 */
	WHILE_THE_FOOLISH_LIGHT_WAS_ASLEEP_THE_DARKNESS_WILL_AWAKEN_FIRST_UH(1010223),
	/**
	 * Field IT_IS_THE_DEEPEST_DARKNESS_WITH_ITS_ARRIVAL_THE_WORLD_WILL_SOON_DIE.
	 */
	IT_IS_THE_DEEPEST_DARKNESS_WITH_ITS_ARRIVAL_THE_WORLD_WILL_SOON_DIE(1010224),
	/**
	 * Field DEATH_IS_JUST_A_NEW_BEGINNING_HUHU_FEAR_NOT.
	 */
	DEATH_IS_JUST_A_NEW_BEGINNING_HUHU_FEAR_NOT(1010225),
	/**
	 * Field AHH_BEAUTIFUL_GODDES_OF_DEATH_COVER_OVER_THE_FILTH_OF_THOS_WORLD_YOUR_DARKNESS.
	 */
	AHH_BEAUTIFUL_GODDES_OF_DEATH_COVER_OVER_THE_FILTH_OF_THOS_WORLD_YOUR_DARKNESS(1010226),
	/**
	 * Field THE_GODDESS_RESURRECTION_HAS_ALREADY_BEGUN_HUHU_INSIGNIFICANT_CREATURES_LIKE_YOU_CAN_DO_NOTHING.
	 */
	THE_GODDESS_RESURRECTION_HAS_ALREADY_BEGUN_HUHU_INSIGNIFICANT_CREATURES_LIKE_YOU_CAN_DO_NOTHING(1010227),
	/**
	 * Field WHO_DARES_TO_COVET_THE_THRONE_OF_OUR_CASTLE__LEAVE_IMMEDIATELY_OR_YOU_WILL_PAY_THE_PRICE_OF_YOUR_AUDACITY_WITH_YOUR_VERY_OWN_BLOOD.
	 */
	WHO_DARES_TO_COVET_THE_THRONE_OF_OUR_CASTLE__LEAVE_IMMEDIATELY_OR_YOU_WILL_PAY_THE_PRICE_OF_YOUR_AUDACITY_WITH_YOUR_VERY_OWN_BLOOD(1010623),
	/**
	 * Field HMM_THOSE_WHO_ARE_NOT_OF_THE_BLOODLINE_ARE_COMING_THIS_WAY_TO_TAKE_OVER_THE_CASTLE__HUMPH__THE_BITTER_GRUDGES_OF_THE_DEAD.
	 */
	HMM_THOSE_WHO_ARE_NOT_OF_THE_BLOODLINE_ARE_COMING_THIS_WAY_TO_TAKE_OVER_THE_CASTLE__HUMPH__THE_BITTER_GRUDGES_OF_THE_DEAD(1010624),
	/**
	 * Field AARGH_IF_I_DIE_THEN_THE_MAGIC_FORCE_FIELD_OF_BLOOD_WILL.
	 */
	AARGH_IF_I_DIE_THEN_THE_MAGIC_FORCE_FIELD_OF_BLOOD_WILL(1010625),
	/**
	 * Field ITS_NOT_OVER_YET__IT_WONT_BE__OVER__LIKE_THIS__NEVER.
	 */
	ITS_NOT_OVER_YET__IT_WONT_BE__OVER__LIKE_THIS__NEVER(1010626),
	/**
	 * Field OOOH_WHO_POURED_NECTAR_ON_MY_HEAD_WHILE_I_WAS_SLEEPING.
	 */
	OOOH_WHO_POURED_NECTAR_ON_MY_HEAD_WHILE_I_WAS_SLEEPING(1010627),
	/**
	 * Field UNDECIDED.
	 */
	UNDECIDED(1010635),
	/**
	 * Field HEH_HEH_I_SEE_THAT_THE_FEAST_HAS_BEGAN_BE_WARY_THE_CURSE_OF_THE_HELLMANN_FAMILY_HAS_POISONED_THIS_LAND.
	 */
	HEH_HEH_I_SEE_THAT_THE_FEAST_HAS_BEGAN_BE_WARY_THE_CURSE_OF_THE_HELLMANN_FAMILY_HAS_POISONED_THIS_LAND(1010636),
	/**
	 * Field ARISE_MY_FAITHFUL_SERVANTS_YOU_MY_PEOPLE_WHO_HAVE_INHERITED_THE_BLOOD.
	 */
	ARISE_MY_FAITHFUL_SERVANTS_YOU_MY_PEOPLE_WHO_HAVE_INHERITED_THE_BLOOD(1010637),
	/**
	 * Field GRARR_FOR_THE_NEXT_2_MINUTES_OR_SO_THE_GAME_ARENA_ARE_WILL_BE_CLEANED.
	 */
	GRARR_FOR_THE_NEXT_2_MINUTES_OR_SO_THE_GAME_ARENA_ARE_WILL_BE_CLEANED(1010639),
	/**
	 * Field MATCH_BEGINS_IN_S1_MINUTES.
	 */
	MATCH_BEGINS_IN_S1_MINUTES(1800080),
	/**
	 * Field THE_MATCH_IS_AUTOMATICALLY_CANCELED_BECAUSE_YOU_ARE_TOO_FAR_FROM_THE_ADMISSION_MANAGER.
	 */
	THE_MATCH_IS_AUTOMATICALLY_CANCELED_BECAUSE_YOU_ARE_TOO_FAR_FROM_THE_ADMISSION_MANAGER(1800081),
	/**
	 * Field MATCH_CANCELLED.
	 */
	MATCH_CANCELLED(1800123),
	/**
	 * Field BEGIN_STAGE_1_FREYA.
	 */
	BEGIN_STAGE_1_FREYA(1801086),
	/**
	 * Field BEGIN_STAGE_2_FREYA.
	 */
	BEGIN_STAGE_2_FREYA(1801087),
	/**
	 * Field BEGIN_STAGE_3_FREYA.
	 */
	BEGIN_STAGE_3_FREYA(1801088),
	/**
	 * Field BEGIN_STAGE_4_FREYA.
	 */
	BEGIN_STAGE_4_FREYA(1801089),
	/**
	 * Field TIME_REMAINING_UNTIL_NEXT_BATTLE.
	 */
	TIME_REMAINING_UNTIL_NEXT_BATTLE(1801090),
	/**
	 * Field FREYA_HAS_STARTED_TO_MOVE.
	 */
	FREYA_HAS_STARTED_TO_MOVE(1801097),
	/**
	 * Field S1_OF_BALANCE.
	 */
	S1_OF_BALANCE(1801100),
	/**
	 * Field SWIFT_S1.
	 */
	SWIFT_S1(1801101),
	/**
	 * Field S1_OF_BLESSING.
	 */
	S1_OF_BLESSING(1801102),
	/**
	 * Field SHARP_S1.
	 */
	SHARP_S1(1801103),
	/**
	 * Field USEFUL_S1.
	 */
	USEFUL_S1(1801104),
	/**
	 * Field RECKLESS_S1.
	 */
	RECKLESS_S1(1801105),
	/**
	 * Field ALPEN_KOOKABURRA.
	 */
	ALPEN_KOOKABURRA(1801106),
	/**
	 * Field ALPEN_COUGAR.
	 */
	ALPEN_COUGAR(1801107),
	/**
	 * Field ALPEN_BUFFALO.
	 */
	ALPEN_BUFFALO(1801108),
	/**
	 * Field ALPEN_GRENDEL.
	 */
	ALPEN_GRENDEL(1801109),
	/**
	 * Field WE_HAVE_BROKEN_THROUGH_THE_GATE_DESTROY_THE_ENCAMPMENT_AND_MOVE_TO_THE_COMMAND_POST.
	 */
	WE_HAVE_BROKEN_THROUGH_THE_GATE_DESTROY_THE_ENCAMPMENT_AND_MOVE_TO_THE_COMMAND_POST(1300001),
	/**
	 * Field THE_COMMAND_GATE_HAS_OPENED_CAPTURE_THE_FLAG_QUICKLY_AND_RAISE_IT_HIGH_TO_PROCLAIM_OUR_VICTORY.
	 */
	THE_COMMAND_GATE_HAS_OPENED_CAPTURE_THE_FLAG_QUICKLY_AND_RAISE_IT_HIGH_TO_PROCLAIM_OUR_VICTORY(1300002),
	/**
	 * Field THE_GODS_HAVE_FORSAKEN_US__RETREAT.
	 */
	THE_GODS_HAVE_FORSAKEN_US__RETREAT(1300003),
	/**
	 * Field YOU_MAY_HAVE_BROKEN_OUR_ARROWS_BUT_YOU_WILL_NEVER_BREAK_OUR_WILL_ARCHERS_RETREAT.
	 */
	YOU_MAY_HAVE_BROKEN_OUR_ARROWS_BUT_YOU_WILL_NEVER_BREAK_OUR_WILL_ARCHERS_RETREAT(1300004),
	/**
	 * Field AT_LAST_THE_MAGIC_FIELD_THAT_PROTECTS_THE_FORTRESS_HAS_WEAKENED_VOLUNTEERS_STAND_BACK.
	 */
	AT_LAST_THE_MAGIC_FIELD_THAT_PROTECTS_THE_FORTRESS_HAS_WEAKENED_VOLUNTEERS_STAND_BACK(1300005),
	/**
	 * Field AIIEEEE_COMMAND_CENTER_THIS_IS_GUARD_UNIT_WE_NEED_BACKUP_RIGHT_AWAY.
	 */
	AIIEEEE_COMMAND_CENTER_THIS_IS_GUARD_UNIT_WE_NEED_BACKUP_RIGHT_AWAY(1300006),
	/**
	 * Field FORTRESS_POWER_DISABLED.
	 */
	FORTRESS_POWER_DISABLED(1300007),
	/**
	 * Field MACHINE_NO_1_POWER_OFF.
	 */
	MACHINE_NO_1_POWER_OFF(1300009),
	/**
	 * Field MACHINE_NO_2_POWER_OFF.
	 */
	MACHINE_NO_2_POWER_OFF(1300010),
	/**
	 * Field MACHINE_NO_3_POWER_OFF.
	 */
	MACHINE_NO_3_POWER_OFF(1300011),
	/**
	 * Field SPIRIT_OF_FIRE_UNLEASH_YOUR_POWER_BURN_THE_ENEMY.
	 */
	SPIRIT_OF_FIRE_UNLEASH_YOUR_POWER_BURN_THE_ENEMY(1300014),
	/**
	 * Field DO_YOU_NEED_MY_POWER_YOU_SEEM_TO_BE_STRUGGLING.
	 */
	DO_YOU_NEED_MY_POWER_YOU_SEEM_TO_BE_STRUGGLING(1300016),
	/**
	 * Field DONT_THINK_THAT_ITS_GONNA_END_LIKE_THIS.
	 */
	DONT_THINK_THAT_ITS_GONNA_END_LIKE_THIS(1300018),
	/**
	 * Field I_FEEL_SO_MUCH_GRIEF_THAT_I_CANT_EVEN_TAKE_CARE_OF_MYSELF.
	 */
	I_FEEL_SO_MUCH_GRIEF_THAT_I_CANT_EVEN_TAKE_CARE_OF_MYSELF(1300020),
	/**
	 * Field INDEPENDENT_STATE.
	 */
	INDEPENDENT_STATE(1300122),
	/**
	 * Field NONPARTISAN.
	 */
	NONPARTISAN(1300123),
	/**
	 * Field CONTRACT_STATE.
	 */
	CONTRACT_STATE(1300124),
	/**
	 * Field FIRST_PASSWORD_HAS_BEEN_ENTERED.
	 */
	FIRST_PASSWORD_HAS_BEEN_ENTERED(1300125),
	/**
	 * Field SECOND_PASSWORD_HAS_BEEN_ENTERED.
	 */
	SECOND_PASSWORD_HAS_BEEN_ENTERED(1300126),
	/**
	 * Field PASSWORD_HAS_NOT_BEEN_ENTERED.
	 */
	PASSWORD_HAS_NOT_BEEN_ENTERED(1300127),
	/**
	 * Field ATTEMPT_S1__3_IS_IN_PROGRESS.
	 */
	ATTEMPT_S1__3_IS_IN_PROGRESS(1300128),
	/**
	 * Field THE_1ST_MARK_IS_CORRECT.
	 */
	THE_1ST_MARK_IS_CORRECT(1300129),
	/**
	 * Field THE_2ND_MARK_IS_CORRECT.
	 */
	THE_2ND_MARK_IS_CORRECT(1300130),
	/**
	 * Field THE_MARKS_HAVE_NOT_BEEN_ASSEMBLED.
	 */
	THE_MARKS_HAVE_NOT_BEEN_ASSEMBLED(1300131),
	/**
	 * Field OLYMPIAD_CLASSFREE_TEAM_MATCH_IS_GOING_TO_BEGIN_IN_ARENA_S1_IN_A_MOMENT.
	 */
	OLYMPIAD_CLASSFREE_TEAM_MATCH_IS_GOING_TO_BEGIN_IN_ARENA_S1_IN_A_MOMENT(1300132),
	/**
	 * Field DOMAIN_FORTRESS.
	 */
	DOMAIN_FORTRESS(1300133),
	/**
	 * Field BOUNDARY_FORTRESS.
	 */
	BOUNDARY_FORTRESS(1300134),
	/**
	 * Field S1HOUR_S2MINUTE.
	 */
	S1HOUR_S2MINUTE(1300135),
	/**
	 * Field BEGIN_STAGE_1.
	 */
	BEGIN_STAGE_1(1300150),
	/**
	 * Field BEGIN_STAGE_2.
	 */
	BEGIN_STAGE_2(1300151),
	/**
	 * Field BEGIN_STAGE_3.
	 */
	BEGIN_STAGE_3(1300152),
	/**
	 * Field WHAT_A_PREDICAMENT_MY_ATTEMPTS_WERE_UNSUCCESSUFUL.
	 */
	WHAT_A_PREDICAMENT_MY_ATTEMPTS_WERE_UNSUCCESSUFUL(1300162),
	/**
	 * Field COURAGE_AMBITION_PASSION_MERCENARIES_WHO_WANT_TO_REALIZE_THEIR_DREAM_OF_FIGHTING_IN_THE_TERRITORY_WAR_COME_TO_ME_FORTUNE_AND_GLORY_ARE_WAITING_FOR_YOU.
	 */
	COURAGE_AMBITION_PASSION_MERCENARIES_WHO_WANT_TO_REALIZE_THEIR_DREAM_OF_FIGHTING_IN_THE_TERRITORY_WAR_COME_TO_ME_FORTUNE_AND_GLORY_ARE_WAITING_FOR_YOU(1300163),
	/**
	 * Field DO_YOU_WISH_TO_FIGHT_ARE_YOU_AFRAID_NO_MATTER_HOW_HARD_YOU_TRY_YOU_HAVE_NOWHERE_TO_RUN.
	 */
	DO_YOU_WISH_TO_FIGHT_ARE_YOU_AFRAID_NO_MATTER_HOW_HARD_YOU_TRY_YOU_HAVE_NOWHERE_TO_RUN(1300164),
	/**
	 * Field CHARGE_CHARGE_CHARGE.
	 */
	CHARGE_CHARGE_CHARGE(1300165),
	/**
	 * Field OLYMPIAD_CLASSFREE_INDIVIDUAL_MATCH_IS_GOING_TO_BEGIN_IN_ARENA_S1_IN_A_MOMENT.
	 */
	OLYMPIAD_CLASSFREE_INDIVIDUAL_MATCH_IS_GOING_TO_BEGIN_IN_ARENA_S1_IN_A_MOMENT(1300166),
	/**
	 * Field OLYMPIAD_CLASS_INDIVIDUAL_MATCH_IS_GOING_TO_BEGIN_IN_ARENA_S1_IN_A_MOMENT.
	 */
	OLYMPIAD_CLASS_INDIVIDUAL_MATCH_IS_GOING_TO_BEGIN_IN_ARENA_S1_IN_A_MOMENT(1300167),
	/**
	 * Field NEWBIE_GUIDE_GIVE_YOU_THE_MAGIC_OF_SATTELITE_S1.
	 */
	NEWBIE_GUIDE_GIVE_YOU_THE_MAGIC_OF_SATTELITE_S1(1600027),
	/**
	 * Field AIRSHIP_IS_SUMMONED_IS_DEPART_IN_5_MINUTES.
	 */
	AIRSHIP_IS_SUMMONED_IS_DEPART_IN_5_MINUTES(1800219),
	/**
	 * Field AIRSHIP_IS_ARRIVED_IT_WILL_DEPART_TO_ADEN_IN_1_MINUTE.
	 */
	AIRSHIP_IS_ARRIVED_IT_WILL_DEPART_TO_ADEN_IN_1_MINUTE(1800220),
	/**
	 * Field AIRSHIP_IS_DEPARTED_TO_ADEN.
	 */
	AIRSHIP_IS_DEPARTED_TO_ADEN(1800221),
	/**
	 * Field AIRSHIP_IS_ARRIVED_IT_WILL_DEPART_TO_GRACIA_IN_1_MINUTE.
	 */
	AIRSHIP_IS_ARRIVED_IT_WILL_DEPART_TO_GRACIA_IN_1_MINUTE(1800222),
	/**
	 * Field AIRSHIP_IS_DEPARTED_TO_GRACIA.
	 */
	AIRSHIP_IS_DEPARTED_TO_GRACIA(1800223),
	/**
	 * Field IN_AIR_HARBOR_ALREADY_AIRSHIP_DOCKED_PLEASE_WAIT_AND_TRY_AGAIN.
	 */
	IN_AIR_HARBOR_ALREADY_AIRSHIP_DOCKED_PLEASE_WAIT_AND_TRY_AGAIN(1800224),
	/**
	 * Field ATTACK.
	 */
	ATTACK(1800243),
	/**
	 * Field DEFEND.
	 */
	DEFEND(1800244),
	/**
	 * Field MAGUEN_APPEARANCE.
	 */
	MAGUEN_APPEARANCE(1801149),
	/**
	 * Field THERE_ARE_5_MINUTES_REMAINING_TO_REGISTER_FOR_KRATEIS_CUBE_MATCH.
	 */
	THERE_ARE_5_MINUTES_REMAINING_TO_REGISTER_FOR_KRATEIS_CUBE_MATCH(1800203),
	/**
	 * Field THERE_ARE_3_MINUTES_REMAINING_TO_REGISTER_FOR_KRATEIS_CUBE_MATCH.
	 */
	THERE_ARE_3_MINUTES_REMAINING_TO_REGISTER_FOR_KRATEIS_CUBE_MATCH(1800204),
	/**
	 * Field THERE_ARE_1_MINUTES_REMAINING_TO_REGISTER_FOR_KRATEIS_CUBE_MATCH.
	 */
	THERE_ARE_1_MINUTES_REMAINING_TO_REGISTER_FOR_KRATEIS_CUBE_MATCH(1800205),
	/**
	 * Field THE_MATCH_WILL_BEGIN_IN_S1_MINUTES.
	 */
	THE_MATCH_WILL_BEGIN_IN_S1_MINUTES(1800206),
	/**
	 * Field THE_MATCH_WILL_BEGIN_SHORTLY.
	 */
	THE_MATCH_WILL_BEGIN_SHORTLY(1800207),
	/**
	 * Field REGISTRATION_FOR_THE_NEXT_MATCH_WILL_END_AT_S1_MINUTES_AFTER_HOUR.
	 */
	REGISTRATION_FOR_THE_NEXT_MATCH_WILL_END_AT_S1_MINUTES_AFTER_HOUR(1800208),
	/**
	 * Field EVEN_THOUGH_YOU_BRING_SOMETHING_CALLED_A_GIFT_AMONG_YOUR_HUMANS_IT_WOULD_JUST_BE_PROBLEMATIC_FOR_ME.
	 */
	EVEN_THOUGH_YOU_BRING_SOMETHING_CALLED_A_GIFT_AMONG_YOUR_HUMANS_IT_WOULD_JUST_BE_PROBLEMATIC_FOR_ME(1801190),
	/**
	 * Field I_JUST_DONT_KNOW_WHAT_EXPRESSION_I_SHOULD_HAVE_IT_APPEARED_ON_ME.
	 */
	I_JUST_DONT_KNOW_WHAT_EXPRESSION_I_SHOULD_HAVE_IT_APPEARED_ON_ME(1801191),
	/**
	 * Field THE_FEELING_OF_THANKS_IS_JUST_TOO_MUCH_DISTANT_MEMORY_FOR_ME.
	 */
	THE_FEELING_OF_THANKS_IS_JUST_TOO_MUCH_DISTANT_MEMORY_FOR_ME(1801192),
	/**
	 * Field BUT_I_KIND_OF_MISS_IT.
	 */
	BUT_I_KIND_OF_MISS_IT(1801193),
	/**
	 * Field I_AM_ICE_QUEEN_FREYA.
	 */
	I_AM_ICE_QUEEN_FREYA(1801194),
	/**
	 * Field DEAR_S1.
	 */
	DEAR_S1(1801195),
	/**
	 * Field RULERS_OF_THE_SEAL_I_BRING_YOU_WONDROUS_GIFTS.
	 */
	RULERS_OF_THE_SEAL_I_BRING_YOU_WONDROUS_GIFTS(1000431),
	/**
	 * Field RULERS_OF_THE_SEAL_I_HAVE_SOME_EXCELLENT_WEAPONS_TO_SHOW_YOU.
	 */
	RULERS_OF_THE_SEAL_I_HAVE_SOME_EXCELLENT_WEAPONS_TO_SHOW_YOU(1000432),
	/**
	 * Field IVE_BEEN_SO_BUSY_LATELY_IN_ADDITION_TO_PLANNING_MY_TRIP.
	 */
	IVE_BEEN_SO_BUSY_LATELY_IN_ADDITION_TO_PLANNING_MY_TRIP(1000433),
	/**
	 * Field IF_YOU_HAVE_ITEMS_PLEASE_GIVE_THEM_TO_ME.
	 */
	IF_YOU_HAVE_ITEMS_PLEASE_GIVE_THEM_TO_ME(1800279),
	/**
	 * Field MY_STOMACH_IS_EMPTY.
	 */
	MY_STOMACH_IS_EMPTY(1800280),
	/**
	 * Field IM_HUNGRY_IM_HUNGRY.
	 */
	IM_HUNGRY_IM_HUNGRY(1800281),
	/**
	 * Field IM_STILL_NOT_FULL.
	 */
	IM_STILL_NOT_FULL(1800282),
	/**
	 * Field IM_STILL_HUNGRY.
	 */
	IM_STILL_HUNGRY(1800283),
	/**
	 * Field I_FEEL_A_LITTLE_WOOZY.
	 */
	I_FEEL_A_LITTLE_WOOZY(1800284),
	/**
	 * Field GIVE_ME_SOMETHING_TO_EAT.
	 */
	GIVE_ME_SOMETHING_TO_EAT(1800285),
	/**
	 * Field NOW_ITS_TIME_TO_EAT.
	 */
	NOW_ITS_TIME_TO_EAT(1800286),
	/**
	 * Field I_ALSO_NEED_A_DESSERT.
	 */
	I_ALSO_NEED_A_DESSERT(1800287),
	/**
	 * Field IM_STILL_HUNGRY_.
	 */
	IM_STILL_HUNGRY_(1800288),
	/**
	 * Field IM_FULL_NOW_I_DONT_WANT_TO_EAT_ANYMORE.
	 */
	IM_FULL_NOW_I_DONT_WANT_TO_EAT_ANYMORE(1800289),
	/**
	 * Field ELAPSED_TIME.
	 */
	ELAPSED_TIME(1911119),
	/**
	 * Field TIME_REMAINING.
	 */
	TIME_REMAINING(1911120),
	/**
	 * Field I_FEEL_STRONG_MAGIC_FLOW.
	 */
	I_FEEL_STRONG_MAGIC_FLOW(1801111),
	/**
	 * Field I_HAVENT_EATEN_ANYTHING_IM_SO_WEAK.
	 */
	I_HAVENT_EATEN_ANYTHING_IM_SO_WEAK(1800290),
	/**
	 * Field WE_MUST_SEARCH_HIGH_AND_LOW_IN_EVERY_ROOM_FOR_THE_READING_DESK_THAT_CONTAINS_THE_BOOK_WE_SEEK.
	 */
	WE_MUST_SEARCH_HIGH_AND_LOW_IN_EVERY_ROOM_FOR_THE_READING_DESK_THAT_CONTAINS_THE_BOOK_WE_SEEK(1029450),
	/**
	 * Field REMEMBER_THE_CONTENT_OF_THE_BOOKS_THAT_YOU_FOUND.
	 */
	REMEMBER_THE_CONTENT_OF_THE_BOOKS_THAT_YOU_FOUND(1029451),
	/**
	 * Field IT_SEEMS_THAT_YOU_CANNOT_REMEMBER_TO_THE_ROOM_OF_THE_WATCHER_WHO_FOUND_THE_BOOK.
	 */
	IT_SEEMS_THAT_YOU_CANNOT_REMEMBER_TO_THE_ROOM_OF_THE_WATCHER_WHO_FOUND_THE_BOOK(1029452),
	/**
	 * Field YOUR_WORK_HERE_IS_DONE_SO_RETURN_TO_THE_CENTRAL_GUARDIAN.
	 */
	YOUR_WORK_HERE_IS_DONE_SO_RETURN_TO_THE_CENTRAL_GUARDIAN(1029453),
	/**
	 * Field THE_GUARDIAN_OF_THE_SEAL_DOESNT_SEEM_TO_GET_INJURED_AT_ALL_UNTIL_THE_BARRIER_IS_DESTROYED.
	 */
	THE_GUARDIAN_OF_THE_SEAL_DOESNT_SEEM_TO_GET_INJURED_AT_ALL_UNTIL_THE_BARRIER_IS_DESTROYED(1029550),
	/**
	 * Field THE_DEVICE_LOCATED_IN_THE_ROOM_IN_FRONT_OF_THE_GUARDIAN_OF_THE_SEAL_IS_DEFINITELY_THE_BARRIER_THAT_CONTROLS_THE_GUARDIANS_POWER.
	 */
	THE_DEVICE_LOCATED_IN_THE_ROOM_IN_FRONT_OF_THE_GUARDIAN_OF_THE_SEAL_IS_DEFINITELY_THE_BARRIER_THAT_CONTROLS_THE_GUARDIANS_POWER(1029551),
	/**
	 * Field TO_REMOVE_THE_BARRIER_YOU_MUST_FIND_THE_RELICS_THAT_FIT_THE_BARRIER_AND_ACTIVATE_THE_DEVICE.
	 */
	TO_REMOVE_THE_BARRIER_YOU_MUST_FIND_THE_RELICS_THAT_FIT_THE_BARRIER_AND_ACTIVATE_THE_DEVICE(1029552),
	/**
	 * Field ALL_THE_GUARDIANS_WERE_DEFEATED_AND_THE_SEAL_WAS_REMOVED.
	 */
	ALL_THE_GUARDIANS_WERE_DEFEATED_AND_THE_SEAL_WAS_REMOVED(1029553),
	/**
	 * Field WHAT_TOOK_SO_LONG_I_WAITED_FOR_EVER.
	 */
	WHAT_TOOK_SO_LONG_I_WAITED_FOR_EVER(1029350),
	/**
	 * Field I_MUST_ASK_LIBRARIAN_SOPHIA_ABOUT_THE_BOOK.
	 */
	I_MUST_ASK_LIBRARIAN_SOPHIA_ABOUT_THE_BOOK(1029351),
	/**
	 * Field THIS_LIBRARY.
	 */
	THIS_LIBRARY(1029352),
	/**
	 * Field AN_UNDERGROUND_LIBRARY.
	 */
	AN_UNDERGROUND_LIBRARY(1029353),
	/**
	 * Field THE_BOOK_THAT_WE_SEEK_IS_CERTAINLY_HERE.
	 */
	THE_BOOK_THAT_WE_SEEK_IS_CERTAINLY_HERE(1029354),
	/**
	 * Field YOU_FOOLISH_INVADERS_WHO_DISTURB_THE_REST_OF_SOLINA_BE_GONE_FROM_THIS_PLACE.
	 */
	YOU_FOOLISH_INVADERS_WHO_DISTURB_THE_REST_OF_SOLINA_BE_GONE_FROM_THIS_PLACE(1029460),
	/**
	 * Field I_KNOW_NOT_WHAT_YOU_SEEK_BUT_THIS_TRUTH_CANNOT_BE_HANDLED_BY_MERE_HUMANS.
	 */
	I_KNOW_NOT_WHAT_YOU_SEEK_BUT_THIS_TRUTH_CANNOT_BE_HANDLED_BY_MERE_HUMANS(1029461),
	/**
	 * Field I_WILL_NOT_STAND_BY_AND_WATCH_YOUR_FOOLISH_ACTIONS.
	 */
	I_WILL_NOT_STAND_BY_AND_WATCH_YOUR_FOOLISH_ACTIONS(1029462),
	/**
	 * Field COME_AND_EAT.
	 */
	COME_AND_EAT(1801117),
	/**
	 * Field LOOKS_DELICIOUS.
	 */
	LOOKS_DELICIOUS(1801118),
	/**
	 * Field LETS_GO_EAT.
	 */
	LETS_GO_EAT(1801119),
	/**
	 * Field HALL_OF_SUFFERING.
	 */
	HALL_OF_SUFFERING(1800240),
	/**
	 * Field HALL_OF_EROSION.
	 */
	HALL_OF_EROSION(1800241),
	/**
	 * Field HEART_OF_IMMORTALITY.
	 */
	HEART_OF_IMMORTALITY(1800242),
	/**
	 * Field YOU_CAN_HEAR_THE_UNDEAD_OF_EKIMUS_RUSHING_TOWARD_YOU.
	 */
	YOU_CAN_HEAR_THE_UNDEAD_OF_EKIMUS_RUSHING_TOWARD_YOU(1800263),
	/**
	 * Field THE_TUMOR_INSIDE_S1_HAS_BEEN_DESTROYED_NIN_ORDER_TO_DRAW_OUT_THE_COWARDLY_COHEMENES_YOU_MUST_DESTROY_ALL_THE_TUMORS.
	 */
	THE_TUMOR_INSIDE_S1_HAS_BEEN_DESTROYED_NIN_ORDER_TO_DRAW_OUT_THE_COWARDLY_COHEMENES_YOU_MUST_DESTROY_ALL_THE_TUMORS(1800274),
	/**
	 * Field THE_TUMOR_INSIDE_S1_HAS_COMPLETELY_REVIVED.
	 */
	THE_TUMOR_INSIDE_S1_HAS_COMPLETELY_REVIVED(1800275),
	/**
	 * Field ALL_THE_TUMORS_INSIDE_S1_HAVE_BEEN_DESTROYED_DRIVEN_INTO_A_CORNER_COHEMENES_APPEARS_CLOSE_BY.
	 */
	ALL_THE_TUMORS_INSIDE_S1_HAVE_BEEN_DESTROYED_DRIVEN_INTO_A_CORNER_COHEMENES_APPEARS_CLOSE_BY(1800299),
	/**
	 * Field S1S_PARTY_HAS_MOVED_TO_A_DIFFERENT_LOCATION_THROUGH_THE_CRACK_IN_THE_TUMOR.
	 */
	S1S_PARTY_HAS_MOVED_TO_A_DIFFERENT_LOCATION_THROUGH_THE_CRACK_IN_THE_TUMOR(1800247),
	/**
	 * Field S1S_PARTY_HAS_ENTERED_THE_CHAMBER_OF_EKIMUS_THROUGH_THE_CRACK_IN_THE_TUMOR.
	 */
	S1S_PARTY_HAS_ENTERED_THE_CHAMBER_OF_EKIMUS_THROUGH_THE_CRACK_IN_THE_TUMOR(1800248),
	/**
	 * Field EKIMUS_HAS_SENSED_ABNORMAL_ACTIVITY.
	 */
	EKIMUS_HAS_SENSED_ABNORMAL_ACTIVITY(1800249),
	/**
	 * Field CMON_CMON_SHOW_YOUR_FACE_YOU_LITTLE_RATS_LET_ME_SEE_WHAT_THE_DOOMED_WEAKLINGS_ARE_SCHEMING.
	 */
	CMON_CMON_SHOW_YOUR_FACE_YOU_LITTLE_RATS_LET_ME_SEE_WHAT_THE_DOOMED_WEAKLINGS_ARE_SCHEMING(1800233),
	/**
	 * Field IMPRESSIVE.
	 */
	IMPRESSIVE(1800234),
	/**
	 * Field KYAHAHA_SINCE_THE_TUMOR_HAS_BEEN_RESURRECTED_I_NO_LONGER_NEED_TO_WASTE_MY_TIME_ON_YOU.
	 */
	KYAHAHA_SINCE_THE_TUMOR_HAS_BEEN_RESURRECTED_I_NO_LONGER_NEED_TO_WASTE_MY_TIME_ON_YOU(1800235),
	/**
	 * Field KEU.
	 */
	KEU(1800236),
	/**
	 * Field S1_MINUTES_ARE_REMAINING.
	 */
	S1_MINUTES_ARE_REMAINING(1010643),
	/**
	 * Field CONGRATULATIONS_YOU_HAVE_SUCCEEDED_AT_S1_S2_THE_INSTANCE_WILL_SHORTLY_EXPIRE.
	 */
	CONGRATULATIONS_YOU_HAVE_SUCCEEDED_AT_S1_S2_THE_INSTANCE_WILL_SHORTLY_EXPIRE(1800245),
	/**
	 * Field YOU_HAVE_FAILED_AT_S1_S2.
	 */
	YOU_HAVE_FAILED_AT_S1_S2(1800246),
	/**
	 * Field YOU_WILL_PARTICIPATE_IN_S1_S2_SHORTLY.
	 */
	YOU_WILL_PARTICIPATE_IN_S1_S2_SHORTLY(1800262),
	/**
	 * Field I_SHALL_ACCEPT_YOUR_CHALLENGE_S1_COME_AND_DIE_IN_THE_ARMS_OF_IMMORTALITY.
	 */
	I_SHALL_ACCEPT_YOUR_CHALLENGE_S1_COME_AND_DIE_IN_THE_ARMS_OF_IMMORTALITY(1800261),
	/**
	 * Field THE_TUMOR_INSIDE_S1_THAT_HAS_PROVIDED_ENERGY_N_TO_EKIMUS_IS_DESTROYED.
	 */
	THE_TUMOR_INSIDE_S1_THAT_HAS_PROVIDED_ENERGY_N_TO_EKIMUS_IS_DESTROYED(1800302),
	/**
	 * Field THE_TUMOR_INSIDE_S1_HAS_BEEN_COMPLETELY_RESURRECTED_N_AND_STARTED_TO_ENERGIZE_EKIMUS_AGAIN.
	 */
	THE_TUMOR_INSIDE_S1_HAS_BEEN_COMPLETELY_RESURRECTED_N_AND_STARTED_TO_ENERGIZE_EKIMUS_AGAIN(1800303),
	/**
	 * Field WITH_ALL_CONNECTIONS_TO_THE_TUMOR_SEVERED_EKIMUS_HAS_LOST_ITS_POWER_TO_CONTROL_THE_FERAL_HOUND.
	 */
	WITH_ALL_CONNECTIONS_TO_THE_TUMOR_SEVERED_EKIMUS_HAS_LOST_ITS_POWER_TO_CONTROL_THE_FERAL_HOUND(1800269),
	/**
	 * Field WITH_THE_CONNECTION_TO_THE_TUMOR_RESTORED_EKIMUS_HAS_REGAINED_CONTROL_OVER_THE_FERAL_HOUND.
	 */
	WITH_THE_CONNECTION_TO_THE_TUMOR_RESTORED_EKIMUS_HAS_REGAINED_CONTROL_OVER_THE_FERAL_HOUND(1800270),
	/**
	 * Field THERE_IS_NO_PARTY_CURRENTLY_CHALLENGING_EKIMUS.
	 */
	THERE_IS_NO_PARTY_CURRENTLY_CHALLENGING_EKIMUS(1800229),
	/**
	 * Field YOU_CAN_FEEL_THE_SURGING_ENERGY_OF_DEATH_FROM_THE_TUMOR.
	 */
	YOU_CAN_FEEL_THE_SURGING_ENERGY_OF_DEATH_FROM_THE_TUMOR(1800264),
	/**
	 * Field THE_AREA_NEAR_THE_TUMOR_IS_FULL_OF_OMINOUS_ENERGY.
	 */
	THE_AREA_NEAR_THE_TUMOR_IS_FULL_OF_OMINOUS_ENERGY(1800265),
	/**
	 * Field THE_TUMOR_INSIDE_S1_HAS_BEEN_DESTROYED_NTHE_NEARBY_UNDEAD_THAT_WERE_ATTACKING_SEED_OF_LIFE_START_LOSING_THEIR_ENERGY_AND_RUN_AWAY.
	 */
	THE_TUMOR_INSIDE_S1_HAS_BEEN_DESTROYED_NTHE_NEARBY_UNDEAD_THAT_WERE_ATTACKING_SEED_OF_LIFE_START_LOSING_THEIR_ENERGY_AND_RUN_AWAY(1800300),
	/**
	 * Field THE_TUMOR_INSIDE_S1_HAS_COMPLETELY_REVIVED_.
	 */
	THE_TUMOR_INSIDE_S1_HAS_COMPLETELY_REVIVED_(1800301),
	/**
	 * Field THE_TUMOR_INSIDE_S1_HAS_BEEN_DESTROYED_NTHE_SPEED_THAT_EKIMUS_CALLS_OUT_HIS_PREY_HAS_SLOWED_DOWN.
	 */
	THE_TUMOR_INSIDE_S1_HAS_BEEN_DESTROYED_NTHE_SPEED_THAT_EKIMUS_CALLS_OUT_HIS_PREY_HAS_SLOWED_DOWN(1800304),
	/**
	 * Field THE_TUMOR_INSIDE_S1_HAS_COMPLETELY_REVIVED__.
	 */
	THE_TUMOR_INSIDE_S1_HAS_COMPLETELY_REVIVED__(1800305),
	/**
	 * Field BRING_MORE_MORE_SOULS.
	 */
	BRING_MORE_MORE_SOULS(1800306),
	/**
	 * Field HA_HA_HA.
	 */
	HA_HA_HA(7164),
	/**
	 * Field THE_SOUL_COFFIN_HAS_AWAKENED_EKIMUS.
	 */
	THE_SOUL_COFFIN_HAS_AWAKENED_EKIMUS(1800232),
	/**
	 * Field YUMYUM_YUMYUM.
	 */
	YUMYUM_YUMYUM(1800291),
	/**
	 * Field FIRST_NEWBIE_HELP_WINDOW.
	 */
	FIRST_NEWBIE_HELP_WINDOW(1600026),
	/**
	 * Field DONT_JUST_GO_I_STILL_HAVE_TONS_TO_TEACH_YOU.
	 */
	DONT_JUST_GO_I_STILL_HAVE_TONS_TO_TEACH_YOU(1032103),
	/**
	 * Field WEAPONS_HAVE_BEEN_ADDED_TO_YOUR_INVENTORY.
	 */
	WEAPONS_HAVE_BEEN_ADDED_TO_YOUR_INVENTORY(1032201),
	/**
	 * Field S1_COME_WITH_ME_I_WILL_LEAD_YOU_TO_IBANE.
	 */
	S1_COME_WITH_ME_I_WILL_LEAD_YOU_TO_IBANE(1032301),
	/**
	 * Field S1_COME_FOLLOW_ME.
	 */
	S1_COME_FOLLOW_ME(1032302),
	/**
	 * Field S1_THAT_MAN_IN_FRONT_IS_IBANE.
	 */
	S1_THAT_MAN_IN_FRONT_IS_IBANE(1032303),
	/**
	 * Field S1_COME_WITH_ME_I_WILL_LEAD_YOU_TO_HOLDEN.
	 */
	S1_COME_WITH_ME_I_WILL_LEAD_YOU_TO_HOLDEN(1032304),
	/**
	 * Field S1_THAT_MAN_IN_FRONT_IS_HOLDEN.
	 */
	S1_THAT_MAN_IN_FRONT_IS_HOLDEN(1032306),
	/**
	 * Field GOING_INTO_REAL_WAR_SOULSHOTS_ADDED.
	 */
	GOING_INTO_REAL_WAR_SOULSHOTS_ADDED(1032351),
	/**
	 * Field GOING_INTO_REAL_WAR_AUTOMATE_SOULSHOTS.
	 */
	GOING_INTO_REAL_WAR_AUTOMATE_SOULSHOTS(1032352),
	/**
	 * Field GOING_INTO_REAL_WAR_SPIRITSHOTS_ADDED.
	 */
	GOING_INTO_REAL_WAR_SPIRITSHOTS_ADDED(1032351),
	/**
	 * Field GOING_INTO_REAL_WAR_AUTOMATE_SPIRITSHOTS.
	 */
	GOING_INTO_REAL_WAR_AUTOMATE_SPIRITSHOTS(1032352),
	/**
	 * Field WATCH_OUT_YOU_ARE_BEING_ATTACKED.
	 */
	WATCH_OUT_YOU_ARE_BEING_ATTACKED(1032322),
	/**
	 * Field FINALLY_I_THOUGHT_I_WAS_GOING_TO_DIE_WAITING.
	 */
	FINALLY_I_THOUGHT_I_WAS_GOING_TO_DIE_WAITING(1032324),
	/**
	 * Field YOUR_NORMAL_ATTACKS_ARENT_WORKING.
	 */
	YOUR_NORMAL_ATTACKS_ARENT_WORKING(1032325),
	/**
	 * Field USE_YOUR_SKILL_ATTACKS_AGAINST_THEM.
	 */
	USE_YOUR_SKILL_ATTACKS_AGAINST_THEM(1032327),
	/**
	 * Field LOOKS_LIKE_ONLY_SKILL_BASED_ATTACKS_DAMAGE_THEM.
	 */
	LOOKS_LIKE_ONLY_SKILL_BASED_ATTACKS_DAMAGE_THEM(1032326),
	/**
	 * Field ENOUGH_OF_THIS_COME_AT_ME.
	 */
	ENOUGH_OF_THIS_COME_AT_ME(1032328),
	/**
	 * Field ACCESSORIES_HAVE_BEEN_ADDED_TO_YOUR_INVENTORY.
	 */
	ACCESSORIES_HAVE_BEEN_ADDED_TO_YOUR_INVENTORY(11022201),
	/**
	 * Field HEY_KID_HARRY_UP_AND_FOLLOW_ME.
	 */
	HEY_KID_HARRY_UP_AND_FOLLOW_ME(1811265),
	/**
	 * Field TALK_TO_THAT_APPRENTICE_AND_GET_ON_KOOKARU.
	 */
	TALK_TO_THAT_APPRENTICE_AND_GET_ON_KOOKARU(1811268),
	/**
	 * Field ARMOR_HAS_BEEN_ADDED_TO_YOUR_INVENTORY.
	 */
	ARMOR_HAS_BEEN_ADDED_TO_YOUR_INVENTORY(11022202),
	/**
	 * Field YOU_ARE_TOO_FAR_FROM_CORPSE_TO_SHOW_YOUR_CONDOLENCES.
	 */
	YOU_ARE_TOO_FAR_FROM_CORPSE_TO_SHOW_YOUR_CONDOLENCES(10307000),
	/**
	 * Field YOU_SHOWN_YOUR_CONDOLENCES_TO_ONE_CORPSE.
	 */
	YOU_SHOWN_YOUR_CONDOLENCES_TO_ONE_CORPSE(1036301),
	/**
	 * Field YOU_SHOWN_YOUR_CONDOLENCES_TO_SECOND_CORPSE.
	 */
	YOU_SHOWN_YOUR_CONDOLENCES_TO_SECOND_CORPSE(1036302),
	/**
	 * Field YOU_SHOWN_YOUR_CONDOLENCES_TO_THIRD_CORPSE.
	 */
	YOU_SHOWN_YOUR_CONDOLENCES_TO_THIRD_CORPSE(1036303),
	/**
	 * Field YOU_SHOWN_YOUR_CONDOLENCES_TO_FOURTH_CORPSE.
	 */
	YOU_SHOWN_YOUR_CONDOLENCES_TO_FOURTH_CORPSE(1036304),
	/**
	 * Field YOU_SHOWN_YOUR_CONDOLENCES_TO_FIFTH_CORPSE.
	 */
	YOU_SHOWN_YOUR_CONDOLENCES_TO_FIFTH_CORPSE(1036305),
	/**
	 * Field YOU_ARE_TOO_FAR_FROM_THE_CORPSE_TO_DO_THAT.
	 */
	YOU_ARE_TOO_FAR_FROM_THE_CORPSE_TO_DO_THAT(1810363),
	/**
	 * Field GRUDGE_OF_YE_SAGIRA_VICTIMS_HAVE_BEEN_RELIEVED_WITH_YOUR_TEARS.
	 */
	GRUDGE_OF_YE_SAGIRA_VICTIMS_HAVE_BEEN_RELIEVED_WITH_YOUR_TEARS(1810364),
	/**
	 * Field DONT_TOY_WITH_DEAD.
	 */
	DONT_TOY_WITH_DEAD(1036344),
	/**
	 * Field CATCH_UP_TO_KING_HES_WAITING.
	 */
	CATCH_UP_TO_KING_HES_WAITING(17178339),
	/**
	 * Field RUFF_RUFF_RRRRRR.
	 */
	RUFF_RUFF_RRRRRR(17178340),
	/**
	 * Field YOU_MUST_MOVE_TO_EXPLORATION_AREA_5_IN_ORDER_TO_CONTINUE.
	 */
	YOU_MUST_MOVE_TO_EXPLORATION_AREA_5_IN_ORDER_TO_CONTINUE(17178341),
	/**
	 * Field KING_HAS_RETURNED_TO_DEF_RETURN_TO_DEF_AND_START_AGAIN.
	 */
	KING_HAS_RETURNED_TO_DEF_RETURN_TO_DEF_AND_START_AGAIN(17178342),
	/**
	 * Field HAHAHA_YOU_DARE_TO_DISRUPT_ME_I_WILL_BE_YOUR_NIGHTMARE_FROM_WHICH_YOU_CAN_NEVER_AWAKEN.
	 */
	HAHAHA_YOU_DARE_TO_DISRUPT_ME_I_WILL_BE_YOUR_NIGHTMARE_FROM_WHICH_YOU_CAN_NEVER_AWAKEN(1801235),
	/**
	 * Field YOU_DARE_ATTACK_ME_I_WILL_FILL_YOUR_NIGHTMARES_WHITH_BLOOD.
	 */
	YOU_DARE_ATTACK_ME_I_WILL_FILL_YOUR_NIGHTMARES_WHITH_BLOOD(1801236),
	/**
	 * Field I_CANNOT_LET_YOU_STOP_THE_WRAITH_OF_SHILEN.
	 */
	I_CANNOT_LET_YOU_STOP_THE_WRAITH_OF_SHILEN(1801237),
	/**
	 * Field ANSUCUBUS.
	 */
	ANSUCUBUS(1801238),
	/**
	 * Field HALT_YOURNIGHTMARES_WILL_FILL_YOU_WITH_DREAD.
	 */
	HALT_YOURNIGHTMARES_WILL_FILL_YOU_WITH_DREAD(1801239),
	/**
	 * Field YOU_WONT_GET_AWAY.
	 */
	YOU_WONT_GET_AWAY(1801240),
	/**
	 * Field HOW_ALL__THAT_POWER_REMOED.
	 */
	HOW_ALL__THAT_POWER_REMOED(1801241),
	/**
	 * Field SHILEN_I_HAVE_FAILED.
	 */
	SHILEN_I_HAVE_FAILED(1801242),
	/**
	 * Field TO_THINK_THAT_I_COULD_FAIL_IMPOSSIBLE.
	 */
	TO_THINK_THAT_I_COULD_FAIL_IMPOSSIBLE(1801243),
	/**
	 * Field FREE_THE_GIANT_FROM_HIS_IMPRISONMENT_AND_AWAKEN_YOUR_TRUE_POWER.
	 */
	FREE_THE_GIANT_FROM_HIS_IMPRISONMENT_AND_AWAKEN_YOUR_TRUE_POWER(1811216),
	/**
	 * Field YOU_CANNOT_TELEPORT_WHILE_YOU_ARE_DEAD.
	 */
	YOU_CANNOT_TELEPORT_WHILE_YOU_ARE_DEAD(1811318),
	/**
	 * Field MM_IM_SEE.
	 */
	MM_IM_SEE(1620051),
	/**
	 * Field THANK_YOU_FOR_THE_REPORT_ROGIN.
	 */
	THANK_YOU_FOR_THE_REPORT_ROGIN(1620052),
	/**
	 * Field SOLDIERS_WERE_FIGHTING_A_BATTLE_THAT_CANT_BE_WON.
	 */
	SOLDIERS_WERE_FIGHTING_A_BATTLE_THAT_CANT_BE_WON(1620053),
	/**
	 * Field BUT_WE_HAVE_TO_DEFEND_OUR_VILLAGE_SO_WERE_FIGHTING.
	 */
	BUT_WE_HAVE_TO_DEFEND_OUR_VILLAGE_SO_WERE_FIGHTING(1620054),
	/**
	 * Field FOR_THE_FINE_WINES_AND_TREASURES_OF_ADEN.
	 */
	FOR_THE_FINE_WINES_AND_TREASURES_OF_ADEN(1620055),
	/**
	 * Field IM_PROUD_OF_EVERY_ONE_OF.
	 */
	IM_PROUD_OF_EVERY_ONE_OF(1620056),
	/**
	 * Field UGH_IFI_SEE_YOU_IN_THE_SPIRIT_WORLD_FIRST_ROUND_IS_ON_ME.
	 */
	UGH_IFI_SEE_YOU_IN_THE_SPIRIT_WORLD_FIRST_ROUND_IS_ON_ME(1620057),
	/**
	 * Field ROGIN_IM_HERE.
	 */
	ROGIN_IM_HERE(1620058),
	/**
	 * Field BRONK.
	 */
	BRONK(1620059),
	/**
	 * Field CHIEF.
	 */
	CHIEF(1620060),
	/**
	 * Field BRONK_.
	 */
	BRONK_(1620061),
	/**
	 * Field NO_WAY.
	 */
	NO_WAY(1620062),
	/**
	 * Field FOR_BRONK.
	 */
	FOR_BRONK(1620068),
	/**
	 * Field DWARVES_FOREVER.
	 */
	DWARVES_FOREVER(1620069),
	/**
	 * Field SAVE_THE_DWARVEN_VILLAGE.
	 */
	SAVE_THE_DWARVEN_VILLAGE(1620070),
	/**
	 * Field WHOAAAAAA.
	 */
	WHOAAAAAA(1620071),
	/**
	 * Field FIGHT.
	 */
	FIGHT(1620072),
	/**
	 * Field CHIEF_REPORTING_IN.
	 */
	CHIEF_REPORTING_IN(1620073),
	/**
	 * Field ENEMIES_ARE_APPROACHING_FROM_THE_SOUTH.
	 */
	ENEMIES_ARE_APPROACHING_FROM_THE_SOUTH(1620074),
	/**
	 * Field THE_ELDERS_HAVENT_BEEN_MOVED_TO_SAFETY.
	 */
	THE_ELDERS_HAVENT_BEEN_MOVED_TO_SAFETY(1620075),
	/**
	 * Field MANY_RESIDENTS_STILL_HAVENT_LEFT_THEIR_HOMES.
	 */
	MANY_RESIDENTS_STILL_HAVENT_LEFT_THEIR_HOMES(1620076),
	/**
	 * Field CHIEF_.
	 */
	CHIEF_(1620077),
	/**
	 * Field WATCH_THE_DWARVEN_VILLAGE_LAST_STAND.
	 */
	WATCH_THE_DWARVEN_VILLAGE_LAST_STAND(1620096),
	/**
	 * Field GAH_SHILEN_WHY_MUST_YOU_MAKE_US_SUFFER.
	 */
	GAH_SHILEN_WHY_MUST_YOU_MAKE_US_SUFFER(50853),
	/**
	 * Field SHILEN_ABANDONED_US_IT_IS_OUR_TIME_TO_DIE.
	 */
	SHILEN_ABANDONED_US_IT_IS_OUR_TIME_TO_DIE(50854),
	/**
	 * Field WITH_OUR_SACRIFICE_WILL_WE_FULLFILL_THE_PROPHECY.
	 */
	WITH_OUR_SACRIFICE_WILL_WE_FULLFILL_THE_PROPHECY(50855),
	/**
	 * Field BLOODY_RAIN_PLAGUE_DEATH_SHE_IS_NEAR.
	 */
	BLOODY_RAIN_PLAGUE_DEATH_SHE_IS_NEAR(50856),
	/**
	 * Field ARHHHH.
	 */
	ARHHHH(50857),
	/**
	 * Field WE_OFFER_OUR_BLOOD_AS_A_SACRIFICE_SHILEN_SEE_US.
	 */
	WE_OFFER_OUR_BLOOD_AS_A_SACRIFICE_SHILEN_SEE_US(50858),
	/**
	 * Field WILL_DARK_ELVES_BE_FORGOTTEN_AFTER_WHAT_WE_HAVE_DONE.
	 */
	WILL_DARK_ELVES_BE_FORGOTTEN_AFTER_WHAT_WE_HAVE_DONE(50859),
	/**
	 * Field UNBELIEVERS_RUN_DEATH_WILL_FOLLOW_YOU.
	 */
	UNBELIEVERS_RUN_DEATH_WILL_FOLLOW_YOU(50860),
	/**
	 * Field I_CURSE_OUR_BLOOD_I_DESPISE_WHAT_WE_ARE_SHILEN.
	 */
	I_CURSE_OUR_BLOOD_I_DESPISE_WHAT_WE_ARE_SHILEN(50861),
	/**
	 * Field MARK_OF_BELIS_CAN_BE_ACQUIRED_FROM_ENEMIES.
	 */
	MARK_OF_BELIS_CAN_BE_ACQUIRED_FROM_ENEMIES(1811199),
	/**
	 * Field ELECTRONIC_DEVICE_HAS_BEEN_DESTROYED.
	 */
	ELECTRONIC_DEVICE_HAS_BEEN_DESTROYED(1811200),
	/**
	 * Field BEHIND_YOU_THE_ENEMY_IS_AMBUSING_YOU.
	 */
	BEHIND_YOU_THE_ENEMY_IS_AMBUSING_YOU(1811194),
	/**
	 * Field IF_TERAIN_DIES_MISSION_WILL_FAIL.
	 */
	IF_TERAIN_DIES_MISSION_WILL_FAIL(1811197),
	/**
	 * Field DONT_COME_BACK_HERE.
	 */
	DONT_COME_BACK_HERE(1811217),
	/**
	 * Field RIDING_KOOKARU.
	 */
	RIDING_KOOKARU(17178345),
	/**
	 * Field YOU_WILL_FIND_PANTHEON_IN_THE_MUSEUM.
	 */
	YOU_WILL_FIND_PANTHEON_IN_THE_MUSEUM(1032316),
	/**
	 * Field ITS_DANGEROUS_OUT_THERE_IF_YOU_DONT.
	 */
	ITS_DANGEROUS_OUT_THERE_IF_YOU_DONT(1032315),
	/**
	 * Field ONE_DAY_A_STATUS_OF_YOU_COULD_BE_MADE.
	 */
	ONE_DAY_A_STATUS_OF_YOU_COULD_BE_MADE(1032334),
	/**
	 * Field DONT_KNOW_WHAT_TO_DO_LOOK_AT_THE_MAP.
	 */
	DONT_KNOW_WHAT_TO_DO_LOOK_AT_THE_MAP(1032338),
	/**
	 * Field WHY_HAVE_THE_HEROES_ABONDONED_US.
	 */
	WHY_HAVE_THE_HEROES_ABONDONED_US(1811286),
	/**
	 * Field KIDS_THESE_DAYS.
	 */
	KIDS_THESE_DAYS(1811257),
	/**
	 * Field GUARDIAN_MESSEGE.
	 */
	GUARDIAN_MESSEGE(1032355),
	/**
	 * Field WHEN_YOU_GO_TO_THE_MUSEUM.
	 */
	WHEN_YOU_GO_TO_THE_MUSEUM(1032336),
	/**
	 * Field ISNT_THERE_AN_EASIER_WAY_TO_GET.
	 */
	ISNT_THERE_AN_EASIER_WAY_TO_GET(1032314),
	/**
	 * Field IF_YOU_IGNORE_THE_TRAINING_GROUNDS.
	 */
	IF_YOU_IGNORE_THE_TRAINING_GROUNDS(1811255),
	/**
	 * Field DONT_GO_HUNTING_WITH_SOULSHOT.
	 */
	DONT_GO_HUNTING_WITH_SOULSHOT(1032331),
	/**
	 * Field PERHAPS_EVEN_THE_VILLAGE_BECOMES_DANGEROUS.
	 */
	PERHAPS_EVEN_THE_VILLAGE_BECOMES_DANGEROUS(1811307),
	/**
	 * Field YOULL_EAERN_OF_ITEMS_USING_THE_TRAINING_GROUNDS.
	 */
	YOULL_EAERN_OF_ITEMS_USING_THE_TRAINING_GROUNDS(1811256),
	/**
	 * Field HUNTING_AT_THE_BEACH_IS_A_BAD_IDEA.
	 */
	HUNTING_AT_THE_BEACH_IS_A_BAD_IDEA(1032329),
	/**
	 * Field ONLY_THE_STRONG_SURVIVE_AT_YE_SAGIRA_RUINS.
	 */
	ONLY_THE_STRONG_SURVIVE_AT_YE_SAGIRA_RUINS(1032330),
	/**
	 * Field BELLOW_LEVEL_REVICE_NB.
	 */
	BELLOW_LEVEL_REVICE_NB(1032332),
	/**
	 * Field THE_SEVEN_SINGS_ENDED.
	 */
	THE_SEVEN_SINGS_ENDED(1811289),
	/**
	 * Field WE_NEED_TO_FIND_WEAKNESS.
	 */
	WE_NEED_TO_FIND_WEAKNESS(1811290),
	/**
	 * Field SOMETHING_LIKE_THAT_COMES_OUT_OF_THE_RUINS.
	 */
	SOMETHING_LIKE_THAT_COMES_OUT_OF_THE_RUINS(1811287),
	/**
	 * Field CREATURES_HAVE_STOPPED_THEIR_ATTACK.
	 */
	CREATURES_HAVE_STOPPED_THEIR_ATTACK(1034113),
	/**
	 * Field CREATURES_RESSURECTED_DEFEND_YOURSELF.
	 */
	CREATURES_RESSURECTED_DEFEND_YOURSELF(1034105),
	/**
	 * Field CREATURES_RESSURECTED_DEFEND_YOURSELF2.
	 */
	CREATURES_RESSURECTED_DEFEND_YOURSELF2(1034111),
	/**
	 * Field CREATURES_RESSURECTED_DEFEND_YOURSELF3.
	 */
	CREATURES_RESSURECTED_DEFEND_YOURSELF3(1034114),
	/**
	 * Field CREATURES_RESSURECTED_FIRST_WAVE.
	 */
	CREATURES_RESSURECTED_FIRST_WAVE(1034106),
	/**
	 * Field CREATURES_RESSURECTED_SECOND_WAVE.
	 */
	CREATURES_RESSURECTED_SECOND_WAVE(1034107),
	/**
	 * Field CREATURES_RESSURECTED_THIRD_WAVE.
	 */
	CREATURES_RESSURECTED_THIRD_WAVE(1034108),
	/**
	 * Field CREATURES_RESSURECTED_FOURTH_WAVE.
	 */
	CREATURES_RESSURECTED_FOURTH_WAVE(1034109),
	/**
	 * Field CREATURES_RESSURECTED_FIFTH_WAVE.
	 */
	CREATURES_RESSURECTED_FIFTH_WAVE(1034110),
	/**
	 * Field CREATURES_RESSURECTED_DEATH_WOUND_HAS_BEEN_SUMMONED.
	 */
	CREATURES_RESSURECTED_DEATH_WOUND_HAS_BEEN_SUMMONED(1034112),
	/**
	 * Field MY_SUMMONS_ARE_NOT_AFRAID_OF_SHILENS_MONSTERS.
	 */
	MY_SUMMONS_ARE_NOT_AFRAID_OF_SHILENS_MONSTERS(1034103),
	/**
	 * Field I_CAN_HEAL_YOU_DURING_COMBAT.
	 */
	I_CAN_HEAL_YOU_DURING_COMBAT(1034102),
	/**
	 * Field I_HIT_THINGS_THEY_FALL_DEAD.
	 */
	I_HIT_THINGS_THEY_FALL_DEAD(1034101),
	/**
	 * Field WHAT_DIOI_FEEL_WHEN_I_KILL_SHILENS_MONSTERS_RECOIL.
	 */
	WHAT_DIOI_FEEL_WHEN_I_KILL_SHILENS_MONSTERS_RECOIL(1034104),
	/**
	 * Field GET_BEHIND_ME_GET_BEHIND_ME.
	 */
	GET_BEHIND_ME_GET_BEHIND_ME(1034118),
	/**
	 * Field THE_ONLY_GOOD_SHILEN_CREATURE_IS_A_DEAD_ONE.
	 */
	THE_ONLY_GOOD_SHILEN_CREATURE_IS_A_DEAD_ONE(1034119),
	/**
	 * Field DID_SONEONE_CRY_MEDIC_HERE_BE_HEALED.
	 */
	DID_SONEONE_CRY_MEDIC_HERE_BE_HEALED(1034120),
	/**
	 * Field IM_ON_FIRE_NO_WAIT_THAT_WOULD_BE_YOU.
	 */
	IM_ON_FIRE_NO_WAIT_THAT_WOULD_BE_YOU(1034121),
	/**
	 * Field BOOM_HEADSHOT.
	 */
	BOOM_HEADSHOT(1034122),
	/**
	 * Field CREATURES_HAVE_STOPPED_THEIR_ATTACK_USE_THIS_TIME_TO_REST_AND_RECOVER.
	 */
	CREATURES_HAVE_STOPPED_THEIR_ATTACK_USE_THIS_TIME_TO_REST_AND_RECOVER(1034123),
	/**
	 * Field DEATH_WOUND_CHAMPION_OF_SHILEN_SHALL_END_YOUR_WORLD.
	 */
	DEATH_WOUND_CHAMPION_OF_SHILEN_SHALL_END_YOUR_WORLD(1034116),
	/**
	 * Field AGH_HUMANS_HA_IT_DOES_NOT_MATTER_YOUR_WORLD_WILL_END_ANYWAYS.
	 */
	AGH_HUMANS_HA_IT_DOES_NOT_MATTER_YOUR_WORLD_WILL_END_ANYWAYS(1034117),
	/**
	 * Field THE_CRY_OF_FATE_PENDANT_WILL_BE_HELPFUL_TO_YOU.
	 */
	THE_CRY_OF_FATE_PENDANT_WILL_BE_HELPFUL_TO_YOU(1034124),
	/**
	 * Field IT_S_HERE.
	 */
	IT_S_HERE(1811262),
	/**
	 * Field AN_INTRUDER_INTERESTING.
	 */
	AN_INTRUDER_INTERESTING(10338011),
	/**
	 * Field PROVE_YOUR_WORTH.
	 */
	PROVE_YOUR_WORTH(10338012),
	/**
	 * Field ONLY_THOSE_STRONG_ENOUGH_SHALL_PROCEED.
	 */
	ONLY_THOSE_STRONG_ENOUGH_SHALL_PROCEED(10338013),
	/**
	 * Field ARE_YOU_AGAINST_THE_WILL_OF_LIGHT.
	 */
	ARE_YOU_AGAINST_THE_WILL_OF_LIGHT(10338014),
	/**
	 * Field COME_ATTACK_ME_IF_YOU_DARE.
	 */
	COME_ATTACK_ME_IF_YOU_DARE(10338015),
	/**
	 * Field ARE_YOU_PLANNING_TO_BETRAY_THE_GODS_AND_FOLLOW_A_GIANT.
	 */
	ARE_YOU_PLANNING_TO_BETRAY_THE_GODS_AND_FOLLOW_A_GIANT(10338016),
	/**
	 * Field ITS_THE_END_FOR_YOU_TRAITOR.
	 */
	ITS_THE_END_FOR_YOU_TRAITOR(10338017),
	/**
	 * Field HA_HA.
	 */
	HA_HA(10338018),
	/**
	 * Field I_WANT_TO_HEAR_YOU_CRY.
	 */
	I_WANT_TO_HEAR_YOU_CRY(10338019),
	/**
	 * Field MORTAL.
	 */
	MORTAL(10338020),
	/**
	 * Field LETS_SEE_WHAT_YOU_ARE_MADE_OF.
	 */
	LETS_SEE_WHAT_YOU_ARE_MADE_OF(10338021),
	/**
	 * Field YOU_WILL_NOT_FREE_HERMUNKUS.
	 */
	YOU_WILL_NOT_FREE_HERMUNKUS(10338022),
	/**
	 * Field YOULL_HAVE_TO_KILL_US_FIRST.
	 */
	YOULL_HAVE_TO_KILL_US_FIRST(10338023),
	/**
	 * Field TRYING_TO_FREE_HERMUNCUS.
	 */
	TRYING_TO_FREE_HERMUNCUS(10338024),
	/**
	 * Field REPENT_AND_YOU_DEATH_WILL_BE_QUICK.
	 */
	REPENT_AND_YOU_DEATH_WILL_BE_QUICK(10338025),
	/**
	 * Field YOU_WILL_NEVER_BREAK_THE_SEAL.
	 */
	YOU_WILL_NEVER_BREAK_THE_SEAL(10338026),
	/**
	 * Field DIE_TRAITOR.
	 */
	DIE_TRAITOR(10338027),
	/**
	 * Field ONLY_THE_LIGHT_MAY_PASS.
	 */
	ONLY_THE_LIGHT_MAY_PASS(10338028),
	/**
	 * Field YOU_ARE_NOT_LIGHT_YOU_MAY_NOT_PASS.
	 */
	YOU_ARE_NOT_LIGHT_YOU_MAY_NOT_PASS(10338029),
	/**
	 * Field RRECEIVE_THIS_POWER_FROM_THE_ANCIENT_GIANT.
	 */
	RRECEIVE_THIS_POWER_FROM_THE_ANCIENT_GIANT(10338036),
	/**
	 * Field USE_THIS_NEW_POWER_WHEN_THE_TIME_IS_RIGHT.
	 */
	USE_THIS_NEW_POWER_WHEN_THE_TIME_IS_RIGHT(10338037),
	/**
	 * Field I_HERMUNKUS_GIVE_MY_POWER_TO_THOSE_WHO_FIGHT_FOR_ME.
	 */
	I_HERMUNKUS_GIVE_MY_POWER_TO_THOSE_WHO_FIGHT_FOR_ME(1811213),
	/**
	 * Field THOUGH_SMALL_THIS_POWER_WILL_HELP_YOU_GREATLY.
	 */
	THOUGH_SMALL_THIS_POWER_WILL_HELP_YOU_GREATLY(1811214),
	/**
	 * Field _PROVE_YOUR_WORTH.
	 */
	_PROVE_YOUR_WORTH(10338030),
	/**
	 * Field ARE_YOU_STRONG_OR_WEAK_OF_THE_LIGHT_OR_DARKNESS.
	 */
	ARE_YOU_STRONG_OR_WEAK_OF_THE_LIGHT_OR_DARKNESS(10338031),
	/**
	 * Field ONLY_THOSE_OF_LIGHT_MAY_PASS_OTHERS_MUST_PROVE_THEIR_STRENGTH.
	 */
	ONLY_THOSE_OF_LIGHT_MAY_PASS_OTHERS_MUST_PROVE_THEIR_STRENGTH(10338032),
	/**
	 * Field LETS_GET_THIS_OVER_WITH.
	 */
	LETS_GET_THIS_OVER_WITH(1811181),
	/**
	 * Field I_MUST_GO_HELP_SOME_MORE.
	 */
	I_MUST_GO_HELP_SOME_MORE(1811222),
	/**
	 * Field FREE_ME_FROM_THIS_BINDING_OF_LIGHT.
	 */
	FREE_ME_FROM_THIS_BINDING_OF_LIGHT(10338006),
	/**
	 * Field DESTROY_THE_GHOST_OF_HARNAK_THIS_CORRUPTED_CREATURE.
	 */
	DESTROY_THE_GHOST_OF_HARNAK_THIS_CORRUPTED_CREATURE(10338007),
	/**
	 * Field FREE_ME_AND_I_PROMISE_YOU_THE_POWER_OF_GIANTS.
	 */
	FREE_ME_AND_I_PROMISE_YOU_THE_POWER_OF_GIANTS(10338008),
	/**
	 * Field REMAINING_TIME.
	 */
	REMAINING_TIME(1811302),
	/**
	 * Field NO_THE_SEAL_CONTROLS_HAVE_BEEN_EXPOSED_GUARDS_PROTECT_THE_SEAL_CONTROLS.
	 */
	NO_THE_SEAL_CONTROLS_HAVE_BEEN_EXPOSED_GUARDS_PROTECT_THE_SEAL_CONTROLS(1811223),
	/**
	 * Field DISABLE_DEVICE_WILL_GO_OUT_OF_CONTROL_IN_1_MINUTE.
	 */
	DISABLE_DEVICE_WILL_GO_OUT_OF_CONTROL_IN_1_MINUTE(1811226),
	/**
	 * Field _50_SECONDS_ARE_REMAINING.
	 */
	_50_SECONDS_ARE_REMAINING(1811227),
	/**
	 * Field _40_SECONDS_ARE_REMAINING.
	 */
	_40_SECONDS_ARE_REMAINING(1811228),
	/**
	 * Field _30_SECONDS_ARE_REMAINING.
	 */
	_30_SECONDS_ARE_REMAINING(1811229),
	/**
	 * Field _20_SECONDS_ARE_REMAINING.
	 */
	_20_SECONDS_ARE_REMAINING(1811230),
	/**
	 * Field _10_SECONDS_ARE_REMAINING.
	 */
	_10_SECONDS_ARE_REMAINING(1811231),
	/**
	 * Field _5_SECONDS.
	 */
	_5_SECONDS(1811232),
	/**
	 * Field _4_SECONDS.
	 */
	_4_SECONDS(1811233),
	/**
	 * Field _3_SECONDS.
	 */
	_3_SECONDS(1811234),
	/**
	 * Field _2_SECONDS.
	 */
	_2_SECONDS(1811235),
	/**
	 * Field _1_SECOND.
	 */
	_1_SECOND(1811236),
	/**
	 * Field YOU_MAY_USE_SCROLL_OF_AFTERLIFE_FROM_HERMUNCUS_TO_AWAKEN.
	 */
	YOU_MAY_USE_SCROLL_OF_AFTERLIFE_FROM_HERMUNCUS_TO_AWAKEN(10338010),
	/**
	 * Field AH_AH_FROM_THE_MAGIC_FORCE_NO_MORE_I_WILL_BE_FREED.
	 */
	AH_AH_FROM_THE_MAGIC_FORCE_NO_MORE_I_WILL_BE_FREED(1800874),
	/**
	 * Field EVEN_THE_MAGIC_FORCE_BINDS_YOU_YOU_WILL_NEVER_BE_FORGIVEN.
	 */
	EVEN_THE_MAGIC_FORCE_BINDS_YOU_YOU_WILL_NEVER_BE_FORGIVEN(1800860),
	/**
	 * Field PROTECT_THE_BRAZIERS_OF_PURITY_AT_ALL_COSTS.
	 */
	PROTECT_THE_BRAZIERS_OF_PURITY_AT_ALL_COSTS(1800855),
	/**
	 * Field THE_PURIFICATION_FIELD_IS_BEING_ATTACKED_GUARDIAN_SPIRITS_PROTECT_THE_MAGIC_FORCE.
	 */
	THE_PURIFICATION_FIELD_IS_BEING_ATTACKED_GUARDIAN_SPIRITS_PROTECT_THE_MAGIC_FORCE(1800854),
	/**
	 * Field NAIA_WAGANAGEL_PEUTAGUN.
	 */
	NAIA_WAGANAGEL_PEUTAGUN(1800858),
	/**
	 * Field TARGET_THREAT_LEVEL_LAUNCHING_STRONGEST_COUNTERMEASURE.
	 */
	TARGET_THREAT_LEVEL_LAUNCHING_STRONGEST_COUNTERMEASURE(1800853),
	/**
	 * Field DRIVE_DEVICE_ENTIRE_DESTRUCTION_MOVING_SUSPENSION.
	 */
	DRIVE_DEVICE_ENTIRE_DESTRUCTION_MOVING_SUSPENSION(1800873),
	/**
	 * Field DRIVE_DEVICE_PARTIAL_DESTRUCTION_IMPULSE_RESULT.
	 */
	DRIVE_DEVICE_PARTIAL_DESTRUCTION_IMPULSE_RESULT(1800859),
	/**
	 * Field DEFEND_OUR_DOMAIN_EVEN_AT_RISK_OF_YOUR_OWN_LIFE.
	 */
	DEFEND_OUR_DOMAIN_EVEN_AT_RISK_OF_YOUR_OWN_LIFE(1800856),
	/**
	 * Field PEUNGLUI_MUGLANEP_NAIA_WAGANAGEL_PEUTAGUN.
	 */
	PEUNGLUI_MUGLANEP_NAIA_WAGANAGEL_PEUTAGUN(1800872),
	/**
	 * Field PEUNGLUI_MUGLANEP.
	 */
	PEUNGLUI_MUGLANEP(1800857),
	/**
	 * Field NEWBIE_HELPER_HAS_CASTED_BUFFS_ON_$S1.
	 */
	NEWBIE_HELPER_HAS_CASTED_BUFFS_ON_$S1(1600027),
	/**
	 * Field TARGET_RECOGNITION_ACHIEVED_ATTACK_SEQUENCE_COMMENCING.
	 */
	TARGET_RECOGNITION_ACHIEVED_ATTACK_SEQUENCE_COMMENCING(1800852),
	/**
	 * Field ISTINA_SOUL_STONE_STARTS_POWERFULLY_ILLUMINATING_IN_RED.
	 */
	ISTINA_SOUL_STONE_STARTS_POWERFULLY_ILLUMINATING_IN_RED(1811138),
	/**
	 * Field ISTINA_SOUL_STONE_STARTS_POWERFULLY_ILLUMINATING_IN_BLUE.
	 */
	ISTINA_SOUL_STONE_STARTS_POWERFULLY_ILLUMINATING_IN_BLUE(1811139),
	/**
	 * Field ISTINA_SOUL_STONE_STARTS_POWERFULLY_ILLUMINATING_IN_GREEN.
	 */
	ISTINA_SOUL_STONE_STARTS_POWERFULLY_ILLUMINATING_IN_GREEN(1811140),
	/**
	 * Field ISTINA_GETS_FURIOUS_AND_RECKLESSLY_CRAZY.
	 */
	ISTINA_GETS_FURIOUS_AND_RECKLESSLY_CRAZY(1811141),
	/**
	 * Field BERSERKER_OF_ISTINA_HAS_BEEN_DISABLED.
	 */
	BERSERKER_OF_ISTINA_HAS_BEEN_DISABLED(1811148),
	/**
	 * Field ISTINA_SPREADS_PROTECTIVE_SHEET.
	 */
	ISTINA_SPREADS_PROTECTIVE_SHEET(1811156),
	/**
	 * Field ALERT_ALERT_DAMAGE_DETECTION_RECOGNIZED_COUNTERMEASURES_ENABLED.
	 */
	ALERT_ALERT_DAMAGE_DETECTION_RECOGNIZED_COUNTERMEASURES_ENABLED(1800851),
	/**
	 * Field They_managed_to_do_everything_on_the_first_try.
	 */
	They_managed_to_do_everything_on_the_first_try(1030101),
	/**
	 * Field The_job_can_start_with_the_old_scroll_of_items.
	 */
	The_job_can_start_with_the_old_scroll_of_items(530400),
	/**
	 * Field CREATURES_RESURRECTED_NONE_WAVE.
	 */
	CREATURES_RESURRECTED_NONE_WAVE(1034105),
	/**
	 * Field CREATURES_RESURRECTED_FIRST_WAVE.
	 */
	CREATURES_RESURRECTED_FIRST_WAVE(1034106),
	/**
	 * Field CREATURES_RESURRECTED_SECOND_WAVE.
	 */
	CREATURES_RESURRECTED_SECOND_WAVE(1034107),
	/**
	 * Field CREATURES_RESURRECTED_THIRD_WAVE.
	 */
	CREATURES_RESURRECTED_THIRD_WAVE(1034108),
	/**
	 * Field CREATURES_RESURRECTED_FOURTH_WAVE.
	 */
	CREATURES_RESURRECTED_FOURTH_WAVE(1034109),
	/**
	 * Field CREATURES_RESURRECTED_FIFTH_WAVE.
	 */
	CREATURES_RESURRECTED_FIFTH_WAVE(1034110),
	/**
	 * Field CREATURES_RESURRECTED_DEFEND_YOURSELF.
	 */
	CREATURES_RESURRECTED_DEFEND_YOURSELF(1034111),
	/**
	 * Field CREATURES_RESURRECTED_DEATH_WOUND_HAS_BEEN_SUMMONED.
	 */
	CREATURES_RESURRECTED_DEATH_WOUND_HAS_BEEN_SUMMONED(1034112),
	/**
	 * Field CREATURES_HAVE_STOPPED_THEIR_ATTACK_REST_AND_THEN_SPEAK_WITH_ADOLPH.
	 */
	CREATURES_HAVE_STOPPED_THEIR_ATTACK_REST_AND_THEN_SPEAK_WITH_ADOLPH(1034113),
	
	WHO_POTR_OUR_SAFETY(8888002),
	STAGE_1(8888017),
	STAGE_2(8888018),
	STAGE_3(8888019),
	STAGE_4(8888020),
	STAGE_5(8888021),
	STAGE_6(8888022),
	STAGE_7(8888023),
	STAGE_8(8888024),
	LAST_STAGE(8888025),
	BONUS_STAGE(8888026),
	PLAKSA(8888027),
	MUKSHUANDHOPNAP(8888028),
	KINEN(8888029),
	RESINA(8888030),
	KONYAR(8888031),
	YOTEMAK(8888032),
	BEZMOLVYJAS(8888033),
	AETTEKTO(8888003),
	POGLOTITESVET(8888004),
	POSMOTRIM(8888005),
	NEBOITESSMERTI(8888006),
	VSETOLKONACHINAETSA(8888007),
	POGLOTIVSE(8888008),
	VELIKOPLEPNO(8888009),
	PRIDETSAZANYATSAETIM(8888010),
	ZAVECHNIYPOKOI(8888011),
	ESLIRAZBITSVETSFERA(8888012),
	PRIDETSAOTPRAVITNEMNOGO(8888013),
	PRIZOVYSFERY(8888014),
	NEMNOGODAYTESILA(8888015),
	VOSKRESHVOINS(8888016);
	
	/**
	 * Field _id.
	 */
	private final int _id;
	/**
	 * Field _size.
	 */
	private final int _size;
	
	/**
	 * Constructor for NpcString.
	 * @param id int
	 */
	NpcString(int id)
	{
		_id = id;
		if (name().contains("S4"))
		{
			_size = 4;
		}
		else if (name().contains("S3"))
		{
			_size = 3;
		}
		else if (name().contains("S2"))
		{
			_size = 2;
		}
		else if (name().contains("S1"))
		{
			_size = 1;
		}
		else
		{
			_size = 0;
		}
	}
	
	/**
	 * Method getId.
	 * @return int
	 */
	public int getId()
	{
		return _id;
	}
	
	/**
	 * Method getSize.
	 * @return int
	 */
	public int getSize()
	{
		return _size;
	}
	
	/**
	 * Method valueOf.
	 * @param id int
	 * @return NpcString
	 */
	public static NpcString valueOf(int id)
	{
		for (NpcString m : values())
		{
			if (m.getId() == id)
			{
				return m;
			}
		}
		throw new NoSuchElementException("Not find NpcString by id: " + id);
	}
}
