/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package lineage2.gameserver.network.serverpackets.components;

import java.util.NoSuchElementException;

import lineage2.gameserver.model.Player;
import lineage2.gameserver.network.serverpackets.L2GameServerPacket;
import lineage2.gameserver.network.serverpackets.SystemMessage2;

/**
 * @author Mobius
 * @version $Revision: 1.0 $
 */
public enum SystemMsg implements IStaticPacket
{
	/**
	 * Field UNABLE_TO_DISSOLVE_YOUR_CLAN_HAS_REQUESTED_TO_PARTICIPATE_IN_A_CASTLE_SIEGE.
	 */
	UNABLE_TO_DISSOLVE_YOUR_CLAN_HAS_REQUESTED_TO_PARTICIPATE_IN_A_CASTLE_SIEGE(13),
	/**
	 * Field YOU_ARE_NOT_IN_SIEGE.
	 */
	YOU_ARE_NOT_IN_SIEGE(16),
	/**
	 * Field YOUR_TARGET_IS_OUT_OF_RANGE.
	 */
	YOUR_TARGET_IS_OUT_OF_RANGE(22),
	/**
	 * Field WELCOME_TO_THE_WORLD_OF_LINEAGE_II.
	 */
	WELCOME_TO_THE_WORLD_OF_LINEAGE_II(34),
	/**
	 * Field YOU_CAREFULLY_NOCK_AN_ARROW.
	 */
	YOU_CAREFULLY_NOCK_AN_ARROW(41),
	/**
	 * Field YOU_HAVE_EQUIPPED_YOUR_S1.
	 */
	YOU_HAVE_EQUIPPED_YOUR_S1(49),
	/**
	 * Field YOU_CANNOT_USE_THIS_ON_YOURSELF.
	 */
	YOU_CANNOT_USE_THIS_ON_YOURSELF(51),
	/**
	 * Field YOU_HAVE_EARNED_S1_ADENA.
	 */
	YOU_HAVE_EARNED_S1_ADENA(52),
	/**
	 * Field YOU_HAVE_EARNED_S2_S1S.
	 */
	YOU_HAVE_EARNED_S2_S1S(53),
	/**
	 * Field YOU_HAVE_EARNED_S1.
	 */
	YOU_HAVE_EARNED_S1(54),
	/**
	 * Field NOTHING_HAPPENED.
	 */
	NOTHING_HAPPENED(61),
	/**
	 * Field YOU_MAY_NOT_ATTACK_IN_A_PEACEFUL_ZONE.
	 */
	YOU_MAY_NOT_ATTACK_IN_A_PEACEFUL_ZONE(84),
	/**
	 * Field YOU_MAY_NOT_ATTACK_THIS_TARGET_IN_A_PEACEFUL_ZONE.
	 */
	YOU_MAY_NOT_ATTACK_THIS_TARGET_IN_A_PEACEFUL_ZONE(85),
	/**
	 * Field THIS_ITEM_CANNOT_BE_TRADED_OR_SOLD.
	 */
	THIS_ITEM_CANNOT_BE_TRADED_OR_SOLD(99),
	/**
	 * Field YOU_CANNOT_EXIT_THE_GAME_WHILE_IN_COMBAT.
	 */
	YOU_CANNOT_EXIT_THE_GAME_WHILE_IN_COMBAT(101),
	/**
	 * Field YOU_CANNOT_RESTART_WHILE_IN_COMBAT.
	 */
	YOU_CANNOT_RESTART_WHILE_IN_COMBAT(102),
	/**
	 * Field C1_HAS_BEEN_INVITED_TO_THE_PARTY.
	 */
	C1_HAS_BEEN_INVITED_TO_THE_PARTY(105),
	/**
	 * Field INVALID_TARGET.
	 */
	INVALID_TARGET(109),
	/**
	 * Field YOUR_SHIELD_DEFENSE_HAS_SUCCEEDED.
	 */
	YOUR_SHIELD_DEFENSE_HAS_SUCCEEDED(111),
	/**
	 * Field S1_CANNOT_BE_USED_DUE_TO_UNSUITABLE_TERMS.
	 */
	S1_CANNOT_BE_USED_DUE_TO_UNSUITABLE_TERMS(113),
	/**
	 * Field C1_HAS_DENIED_YOUR_REQUEST_TO_TRADE.
	 */
	C1_HAS_DENIED_YOUR_REQUEST_TO_TRADE(119),
	/**
	 * Field YOU_BEGIN_TRADING_WITH_C1.
	 */
	YOU_BEGIN_TRADING_WITH_C1(120),
	/**
	 * Field YOU_MAY_NO_LONGER_ADJUST_ITEMS_IN_THE_TRADE_BECAUSE_THE_TRADE_HAS_BEEN_CONFIRMED.
	 */
	YOU_MAY_NO_LONGER_ADJUST_ITEMS_IN_THE_TRADE_BECAUSE_THE_TRADE_HAS_BEEN_CONFIRMED(122),
	/**
	 * Field THAT_IS_AN_INCORRECT_TARGET.
	 */
	THAT_IS_AN_INCORRECT_TARGET(144),
	/**
	 * Field THAT_PLAYER_IS_NOT_ONLINE.
	 */
	THAT_PLAYER_IS_NOT_ONLINE(145),
	/**
	 * Field C1_IS_ON_ANOTHER_TASK.
	 */
	C1_IS_ON_ANOTHER_TASK(153),
	/**
	 * Field ONLY_THE_LEADER_CAN_GIVE_OUT_INVITATIONS.
	 */
	ONLY_THE_LEADER_CAN_GIVE_OUT_INVITATIONS(154),
	/**
	 * Field THE_PARTY_IS_FULL.
	 */
	THE_PARTY_IS_FULL(155),
	/**
	 * Field YOUR_ATTACK_HAS_FAILED.
	 */
	YOUR_ATTACK_HAS_FAILED(158),
	/**
	 * Field C1_IS_A_MEMBER_OF_ANOTHER_PARTY_AND_CANNOT_BE_INVITED.
	 */
	C1_IS_A_MEMBER_OF_ANOTHER_PARTY_AND_CANNOT_BE_INVITED(160),
	/**
	 * Field CONGRATULATIONS__YOUVE_COMPLETED_YOUR_THIRDCLASS_TRANSFER_QUEST.
	 */
	CONGRATULATIONS__YOUVE_COMPLETED_YOUR_THIRDCLASS_TRANSFER_QUEST(1606),
	/**
	 * Field WAITING_FOR_ANOTHER_REPLY.
	 */
	WAITING_FOR_ANOTHER_REPLY(164),
	/**
	 * Field YOU_CANNOT_ADD_YOURSELF_TO_YOUR_OWN_FRIEND_LIST.
	 */
	YOU_CANNOT_ADD_YOURSELF_TO_YOUR_OWN_FRIEND_LIST(165),
	/**
	 * Field FRIEND_LIST_IS_NOT_READY_YET.
	 */
	FRIEND_LIST_IS_NOT_READY_YET(166),
	/**
	 * Field C1_IS_ALREADY_ON_YOUR_FRIEND_LIST.
	 */
	C1_IS_ALREADY_ON_YOUR_FRIEND_LIST(167),
	/**
	 * Field C1_HAS_SENT_A_FRIEND_REQUEST.
	 */
	C1_HAS_SENT_A_FRIEND_REQUEST(168),
	/**
	 * Field ACCEPT_FRIENDSHIP_01_1_TO_ACCEPT_0_TO_DENY.
	 */
	ACCEPT_FRIENDSHIP_01_1_TO_ACCEPT_0_TO_DENY(169),
	/**
	 * Field THE_USER_WHO_REQUESTED_TO_BECOME_FRIENDS_IS_NOT_FOUND_IN_THE_GAME.
	 */
	THE_USER_WHO_REQUESTED_TO_BECOME_FRIENDS_IS_NOT_FOUND_IN_THE_GAME(170),
	/**
	 * Field C1_IS_NOT_ON_YOUR_FRIEND_LIST.
	 */
	C1_IS_NOT_ON_YOUR_FRIEND_LIST(171),
	/**
	 * Field YOU_LACK_THE_FUNDS_NEEDED_TO_PAY_FOR_THIS_TRANSACTION.
	 */
	YOU_LACK_THE_FUNDS_NEEDED_TO_PAY_FOR_THIS_TRANSACTION(172),
	/**
	 * Field THAT_PERSON_IS_IN_MESSAGE_REFUSAL_MODE.
	 */
	THAT_PERSON_IS_IN_MESSAGE_REFUSAL_MODE(176),
	/**
	 * Field MESSAGE_REFUSAL_MODE.
	 */
	MESSAGE_REFUSAL_MODE(177),
	/**
	 * Field CANNOT_SEE_TARGET.
	 */
	CANNOT_SEE_TARGET(181),
	/**
	 * Field ENTERED_THE_CLAN.
	 */
	ENTERED_THE_CLAN(195),
	/**
	 * Field S1_DECLINED_YOUR_CLAN_INVITATION.
	 */
	S1_DECLINED_YOUR_CLAN_INVITATION(196),
	/**
	 * Field YOU_HAVE_RECENTLY_BEEN_DISMISSED_FROM_A_CLAN.
	 */
	YOU_HAVE_RECENTLY_BEEN_DISMISSED_FROM_A_CLAN(199),
	/**
	 * Field INCORRECT_NAME.
	 */
	INCORRECT_NAME(204),
	/**
	 * Field SOME_LINEAGE_II_FEATURES_HAVE_BEEN_LIMITED_FOR_FREE_TRIALS_____.
	 */
	SOME_LINEAGE_II_FEATURES_HAVE_BEEN_LIMITED_FOR_FREE_TRIALS_____(2046),
	/**
	 * Field THE_RECIPE_IS_INCORRECT.
	 */
	THE_RECIPE_IS_INCORRECT(852),
	/**
	 * Field YOU_DO_NOT_HAVE_ENOUGH_MATERIALS_TO_PERFORM_THAT_ACTION.
	 */
	YOU_DO_NOT_HAVE_ENOUGH_MATERIALS_TO_PERFORM_THAT_ACTION(341),
	/**
	 * Field PLEASE_REGISTER_A_RECIPE.
	 */
	PLEASE_REGISTER_A_RECIPE(859),
	/**
	 * Field NOT_ENOUGH_MP.
	 */
	NOT_ENOUGH_MP(24),
	/**
	 * Field YOU_CANNOT_DO_THAT_WHILE_FISHING_.
	 */
	YOU_CANNOT_DO_THAT_WHILE_FISHING_(1470),
	/**
	 * Field S1_HAS_JOINED_THE_CLAN.
	 */
	S1_HAS_JOINED_THE_CLAN(222),
	/**
	 * Field S1_HAS_WITHDRAWN_FROM_THE_CLAN.
	 */
	S1_HAS_WITHDRAWN_FROM_THE_CLAN(223),
	/**
	 * Field AFTER_LEAVING_OR_HAVING_BEEN_DISMISSED_FROM_A_CLAN_YOU_MUST_WAIT_AT_LEAST_A_DAY_BEFORE_JOINING_ANOTHER_CLAN.
	 */
	AFTER_LEAVING_OR_HAVING_BEEN_DISMISSED_FROM_A_CLAN_YOU_MUST_WAIT_AT_LEAST_A_DAY_BEFORE_JOINING_ANOTHER_CLAN(232),
	/**
	 * Field THE_TARGET_MUST_BE_A_CLAN_MEMBER.
	 */
	THE_TARGET_MUST_BE_A_CLAN_MEMBER(234),
	/**
	 * Field ONLY_THE_CLAN_LEADER_IS_ENABLED.
	 */
	ONLY_THE_CLAN_LEADER_IS_ENABLED(236),
	/**
	 * Field A_CLAN_LEADER_CANNOT_WITHDRAW_FROM_THEIR_OWN_CLAN.
	 */
	A_CLAN_LEADER_CANNOT_WITHDRAW_FROM_THEIR_OWN_CLAN(239),
	/**
	 * Field CLAN_NAME_IS_INVALID.
	 */
	CLAN_NAME_IS_INVALID(261),
	/**
	 * Field YOU_DO_NOT_HAVE_THE_NECESSARY_MATERIALS_OR_PREREQUISITES_TO_LEARN_THIS_SKILL.
	 */
	YOU_DO_NOT_HAVE_THE_NECESSARY_MATERIALS_OR_PREREQUISITES_TO_LEARN_THIS_SKILL(276),
	/**
	 * Field YOU_HAVE_EARNED_S1_SKILL.
	 */
	YOU_HAVE_EARNED_S1_SKILL(277),
	/**
	 * Field YOU_DO_NOT_HAVE_ENOUGH_ADENA.
	 */
	YOU_DO_NOT_HAVE_ENOUGH_ADENA(279),
	/**
	 * Field YOU_DO_NOT_HAVE_ENOUGH_SP_TO_LEARN_THIS_SKILL.
	 */
	YOU_DO_NOT_HAVE_ENOUGH_SP_TO_LEARN_THIS_SKILL(278),
	/**
	 * Field CLAN_S1_HAS_SUCCESSFULLY_ENGRAVED_THE_HOLY_ARTIFACT.
	 */
	CLAN_S1_HAS_SUCCESSFULLY_ENGRAVED_THE_HOLY_ARTIFACT(285),
	/**
	 * Field YOUR_BASE_IS_BEING_ATTACKED.
	 */
	YOUR_BASE_IS_BEING_ATTACKED(286),
	/**
	 * Field THE_OPPOSING_CLAN_HAS_STARTED_TO_ENGRAVE_THE_HOLY_ARTIFACT.
	 */
	THE_OPPOSING_CLAN_HAS_STARTED_TO_ENGRAVE_THE_HOLY_ARTIFACT(287),
	/**
	 * Field THE_CASTLE_GATE_HAS_BEEN_DESTROYED.
	 */
	THE_CASTLE_GATE_HAS_BEEN_DESTROYED(288),
	/**
	 * Field AN_OUTPOST_OR_HEADQUARTERS_CANNOT_BE_BUILT_BECAUSE_ONE_ALREADY_EXISTS.
	 */
	AN_OUTPOST_OR_HEADQUARTERS_CANNOT_BE_BUILT_BECAUSE_ONE_ALREADY_EXISTS(289),
	/**
	 * Field YOU_CANNOT_SET_UP_A_BASE_HERE.
	 */
	YOU_CANNOT_SET_UP_A_BASE_HERE(290),
	/**
	 * Field CLAN_S1_IS_VICTORIOUS_OVER_S2S_CASTLE_SIEGE.
	 */
	CLAN_S1_IS_VICTORIOUS_OVER_S2S_CASTLE_SIEGE(291),
	/**
	 * Field S1_HAS_ANNOUNCED_THE_NEXT_CASTLE_SIEGE_TIME.
	 */
	S1_HAS_ANNOUNCED_THE_NEXT_CASTLE_SIEGE_TIME(292),
	/**
	 * Field THE_REGISTRATION_TERM_FOR_S1_HAS_ENDED.
	 */
	THE_REGISTRATION_TERM_FOR_S1_HAS_ENDED(293),
	/**
	 * Field YOU_CANNOT_SUMMON_THE_ENCAMPMENT_BECAUSE_YOU_ARE_NOT_A_MEMBER_OF_THE_SIEGE_CLAN_INVOLVED_IN_THE_CASTLE__FORTRESS__HIDEOUT_SIEGE.
	 */
	YOU_CANNOT_SUMMON_THE_ENCAMPMENT_BECAUSE_YOU_ARE_NOT_A_MEMBER_OF_THE_SIEGE_CLAN_INVOLVED_IN_THE_CASTLE__FORTRESS__HIDEOUT_SIEGE(294),
	/**
	 * Field S1S_SIEGE_WAS_CANCELED_BECAUSE_THERE_WERE_NO_CLANS_THAT_PARTICIPATED.
	 */
	S1S_SIEGE_WAS_CANCELED_BECAUSE_THERE_WERE_NO_CLANS_THAT_PARTICIPATED(295),
	/**
	 * Field YOU_HAVE_DROPPED_S1.
	 */
	YOU_HAVE_DROPPED_S1(298),
	/**
	 * Field C1_HAS_OBTAINED_S3_S2.
	 */
	C1_HAS_OBTAINED_S3_S2(299),
	/**
	 * Field C1_HAS_OBTAINED_S2.
	 */
	C1_HAS_OBTAINED_S2(300),
	/**
	 * Field S2_S1_HAS_DISAPPEARED.
	 */
	S2_S1_HAS_DISAPPEARED(301),
	/**
	 * Field S1_HAS_DISAPPEARED.
	 */
	S1_HAS_DISAPPEARED(302),
	/**
	 * Field CLAN_MEMBER_S1_HAS_LOGGED_INTO_GAME.
	 */
	CLAN_MEMBER_S1_HAS_LOGGED_INTO_GAME(304),
	/**
	 * Field THE_PLAYER_DECLINED_TO_JOIN_YOUR_PARTY.
	 */
	THE_PLAYER_DECLINED_TO_JOIN_YOUR_PARTY(305),
	/**
	 * Field INCORRECT_ITEM_COUNT.
	 */
	INCORRECT_ITEM_COUNT(351),
	/**
	 * Field INAPPROPRIATE_ENCHANT_CONDITIONS.
	 */
	INAPPROPRIATE_ENCHANT_CONDITIONS(355),
	/**
	 * Field S1_HOURS_UNTIL_CASTLE_SIEGE_CONCLUSION.
	 */
	S1_HOURS_UNTIL_CASTLE_SIEGE_CONCLUSION(358),
	/**
	 * Field S1_MINUTES_UNTIL_CASTLE_SIEGE_CONCLUSION.
	 */
	S1_MINUTES_UNTIL_CASTLE_SIEGE_CONCLUSION(359),
	/**
	 * Field THIS_CASTLE_SIEGE_WILL_END_IN_S1_SECONDS.
	 */
	THIS_CASTLE_SIEGE_WILL_END_IN_S1_SECONDS(360),
	/**
	 * Field YOU_HAVE_OBTAINED_A_S1_S2.
	 */
	YOU_HAVE_OBTAINED_A_S1_S2(369),
	/**
	 * Field C1_HAS_OBTAINED_S2S3.
	 */
	C1_HAS_OBTAINED_S2S3(376),
	/**
	 * Field S1_S2_DISAPPEARED.
	 */
	S1_S2_DISAPPEARED(377),
	/**
	 * Field C1_PURCHASED_S2.
	 */
	C1_PURCHASED_S2(378),
	/**
	 * Field C1_PURCHASED_S2S3.
	 */
	C1_PURCHASED_S2S3(379),
	/**
	 * Field C1_PURCHASED_S3_S2S.
	 */
	C1_PURCHASED_S3_S2S(380),
	/**
	 * Field SYSTEM_ERROR.
	 */
	SYSTEM_ERROR(399),
	/**
	 * Field YOU_DO_NOT_POSSESS_THE_CORRECT_TICKET_TO_BOARD_THE_BOAT.
	 */
	YOU_DO_NOT_POSSESS_THE_CORRECT_TICKET_TO_BOARD_THE_BOAT(402),
	/**
	 * Field DOES_NOT_FIT_STRENGTHENING_CONDITIONS_OF_THE_SCROLL.
	 */
	DOES_NOT_FIT_STRENGTHENING_CONDITIONS_OF_THE_SCROLL(424),
	/**
	 * Field YOU_CANNOT_SUMMON_DURING_A_TRADE_OR_WHILE_USING_A_PRIVATE_STORE.
	 */
	YOU_CANNOT_SUMMON_DURING_A_TRADE_OR_WHILE_USING_A_PRIVATE_STORE(577),
	/**
	 * Field A_PET_CANNOT_BE_UNSUMMONED_DURING_BATTLE.
	 */
	A_PET_CANNOT_BE_UNSUMMONED_DURING_BATTLE(579),
	/**
	 * Field DEAD_PETS_CANNOT_BE_RETURNED_TO_THEIR_SUMMONING_ITEM.
	 */
	DEAD_PETS_CANNOT_BE_RETURNED_TO_THEIR_SUMMONING_ITEM(589),
	/**
	 * Field YOU_MAY_NOT_RESTORE_A_HUNGRY_PET.
	 */
	YOU_MAY_NOT_RESTORE_A_HUNGRY_PET(594),
	/**
	 * Field YOU_MAY_NOT_EQUIP_A_PET_ITEM.
	 */
	YOU_MAY_NOT_EQUIP_A_PET_ITEM(600),
	/**
	 * Field YOU_CAN_ONLY_ENTER_UP_128_NAMES_IN_YOUR_FRIENDS_LIST.
	 */
	YOU_CAN_ONLY_ENTER_UP_128_NAMES_IN_YOUR_FRIENDS_LIST(605),
	/**
	 * Field THE_FRIENDS_LIST_OF_THE_PERSON_YOU_ARE_TRYING_TO_ADD_IS_FULL_SO_REGISTRATION_IS_NOT_POSSIBLE.
	 */
	THE_FRIENDS_LIST_OF_THE_PERSON_YOU_ARE_TRYING_TO_ADD_IS_FULL_SO_REGISTRATION_IS_NOT_POSSIBLE(606),
	/**
	 * Field YOU_DO_NOT_HAVE_ANY_FURTHER_SKILLS_TO_LEARN__COME_BACK_WHEN_YOU_HAVE_REACHED_LEVEL_S1.
	 */
	YOU_DO_NOT_HAVE_ANY_FURTHER_SKILLS_TO_LEARN__COME_BACK_WHEN_YOU_HAVE_REACHED_LEVEL_S1(607),
	/**
	 * Field YOU_HAVE_ALREADY_REQUESTED_A_CASTLE_SIEGE.
	 */
	YOU_HAVE_ALREADY_REQUESTED_A_CASTLE_SIEGE(638),
	/**
	 * Field YOU_ARE_ALREADY_REGISTERED_TO_THE_ATTACKER_SIDE_AND_MUST_CANCEL_YOUR_REGISTRATION_BEFORE_SUBMITTING_YOUR_REQUEST.
	 */
	YOU_ARE_ALREADY_REGISTERED_TO_THE_ATTACKER_SIDE_AND_MUST_CANCEL_YOUR_REGISTRATION_BEFORE_SUBMITTING_YOUR_REQUEST(642),
	/**
	 * Field YOU_HAVE_ALREADY_REGISTERED_TO_THE_DEFENDER_SIDE_AND_MUST_CANCEL_YOUR_REGISTRATION_BEFORE_SUBMITTING_YOUR_REQUEST.
	 */
	YOU_HAVE_ALREADY_REGISTERED_TO_THE_DEFENDER_SIDE_AND_MUST_CANCEL_YOUR_REGISTRATION_BEFORE_SUBMITTING_YOUR_REQUEST(643),
	/**
	 * Field YOU_ARE_NOT_YET_REGISTERED_FOR_THE_CASTLE_SIEGE.
	 */
	YOU_ARE_NOT_YET_REGISTERED_FOR_THE_CASTLE_SIEGE(644),
	/**
	 * Field ONLY_CLANS_OF_LEVEL_5_OR_HIGHER_MAY_REGISTER_FOR_A_CASTLE_SIEGE.
	 */
	ONLY_CLANS_OF_LEVEL_5_OR_HIGHER_MAY_REGISTER_FOR_A_CASTLE_SIEGE(645),
	/**
	 * Field YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_MODIFY_THE_CASTLE_DEFENDER_LIST.
	 */
	YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_MODIFY_THE_CASTLE_DEFENDER_LIST(646),
	/**
	 * Field YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_MODIFY_THE_SIEGE_TIME.
	 */
	YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_MODIFY_THE_SIEGE_TIME(647),
	/**
	 * Field NO_MORE_REGISTRATIONS_MAY_BE_ACCEPTED_FOR_THE_ATTACKER_SIDE.
	 */
	NO_MORE_REGISTRATIONS_MAY_BE_ACCEPTED_FOR_THE_ATTACKER_SIDE(648),
	/**
	 * Field NO_MORE_REGISTRATIONS_MAY_BE_ACCEPTED_FOR_THE_DEFENDER_SIDE.
	 */
	NO_MORE_REGISTRATIONS_MAY_BE_ACCEPTED_FOR_THE_DEFENDER_SIDE(649),
	/**
	 * Field YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_POSITION_MERCENARIES.
	 */
	YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_POSITION_MERCENARIES(653),
	/**
	 * Field YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_CANCEL_MERCENARY_POSITIONING.
	 */
	YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_CANCEL_MERCENARY_POSITIONING(654),
	/**
	 * Field MERCENARIES_CANNOT_BE_POSITIONED_HERE.
	 */
	MERCENARIES_CANNOT_BE_POSITIONED_HERE(655),
	/**
	 * Field THIS_MERCENARY_CANNOT_BE_POSITIONED_ANYMORE.
	 */
	THIS_MERCENARY_CANNOT_BE_POSITIONED_ANYMORE(656),
	/**
	 * Field POSITIONING_CANNOT_BE_DONE_HERE_BECAUSE_THE_DISTANCE_BETWEEN_MERCENARIES_IS_TOO_SHORT.
	 */
	POSITIONING_CANNOT_BE_DONE_HERE_BECAUSE_THE_DISTANCE_BETWEEN_MERCENARIES_IS_TOO_SHORT(657),
	/**
	 * Field THIS_IS_NOT_A_MERCENARY_OF_A_CASTLE_THAT_YOU_OWN_AND_SO_YOU_CANNOT_CANCEL_ITS_POSITIONING.
	 */
	THIS_IS_NOT_A_MERCENARY_OF_A_CASTLE_THAT_YOU_OWN_AND_SO_YOU_CANNOT_CANCEL_ITS_POSITIONING(658),
	/**
	 * Field THIS_IS_NOT_THE_TIME_FOR_SIEGE_REGISTRATION_AND_SO_REGISTRATIONS_CANNOT_BE_ACCEPTED_OR_REJECTED.
	 */
	THIS_IS_NOT_THE_TIME_FOR_SIEGE_REGISTRATION_AND_SO_REGISTRATIONS_CANNOT_BE_ACCEPTED_OR_REJECTED(659),
	/**
	 * Field THIS_IS_NOT_THE_TIME_FOR_SIEGE_REGISTRATION_AND_SO_REGISTRATION_AND_CANCELLATION_CANNOT_BE_DONE.
	 */
	THIS_IS_NOT_THE_TIME_FOR_SIEGE_REGISTRATION_AND_SO_REGISTRATION_AND_CANCELLATION_CANNOT_BE_DONE(660),
	/**
	 * Field S1_ADENA_DISAPPEARED.
	 */
	S1_ADENA_DISAPPEARED(672),
	/**
	 * Field ONLY_A_CLAN_LEADER_WHOSE_CLAN_IS_OF_LEVEL_2_OR_HIGHER_IS_ALLOWED_TO_PARTICIPATE_IN_A_CLAN_HALL_AUCTION.
	 */
	ONLY_A_CLAN_LEADER_WHOSE_CLAN_IS_OF_LEVEL_2_OR_HIGHER_IS_ALLOWED_TO_PARTICIPATE_IN_A_CLAN_HALL_AUCTION(673),
	/**
	 * Field IT_HAS_NOT_YET_BEEN_SEVEN_DAYS_SINCE_CANCELING_AN_AUCTION.
	 */
	IT_HAS_NOT_YET_BEEN_SEVEN_DAYS_SINCE_CANCELING_AN_AUCTION(674),
	/**
	 * Field THERE_ARE_NO_CLAN_HALLS_UP_FOR_AUCTION.
	 */
	THERE_ARE_NO_CLAN_HALLS_UP_FOR_AUCTION(675),
	/**
	 * Field SINCE_YOU_HAVE_ALREADY_SUBMITTED_A_BID_YOU_ARE_NOT_ALLOWED_TO_PARTICIPATE_IN_ANOTHER_AUCTION_AT_THIS_TIME.
	 */
	SINCE_YOU_HAVE_ALREADY_SUBMITTED_A_BID_YOU_ARE_NOT_ALLOWED_TO_PARTICIPATE_IN_ANOTHER_AUCTION_AT_THIS_TIME(676),
	/**
	 * Field YOUR_BID_PRICE_MUST_BE_HIGHER_THAN_THE_MINIMUM_PRICE_CURRENTLY_BEING_BID.
	 */
	YOUR_BID_PRICE_MUST_BE_HIGHER_THAN_THE_MINIMUM_PRICE_CURRENTLY_BEING_BID(677),
	/**
	 * Field YOU_HAVE_CANCELED_YOUR_BID.
	 */
	YOU_HAVE_CANCELED_YOUR_BID(679),
	/**
	 * Field YOU_ARE_NO_PRIORITY_RIGHTS_ON_A_SWEEPER.
	 */
	YOU_ARE_NO_PRIORITY_RIGHTS_ON_A_SWEEPER(683),
	/**
	 * Field YOU_CANNOT_MOVE_WHILE_FROZEN.
	 */
	YOU_CANNOT_MOVE_WHILE_FROZEN(687),
	/**
	 * Field CASTLE_OWNING_CLANS_ARE_AUTOMATICALLY_REGISTERED_ON_THE_DEFENDING_SIDE.
	 */
	CASTLE_OWNING_CLANS_ARE_AUTOMATICALLY_REGISTERED_ON_THE_DEFENDING_SIDE(688),
	/**
	 * Field A_CLAN_THAT_OWNS_A_CASTLE_CANNOT_PARTICIPATE_IN_ANOTHER_SIEGE.
	 */
	A_CLAN_THAT_OWNS_A_CASTLE_CANNOT_PARTICIPATE_IN_ANOTHER_SIEGE(689),
	/**
	 * Field YOU_CANNOT_REGISTER_AS_AN_ATTACKER_BECAUSE_YOU_ARE_IN_AN_ALLIANCE_WITH_THE_CASTLE_OWNING_CLAN.
	 */
	YOU_CANNOT_REGISTER_AS_AN_ATTACKER_BECAUSE_YOU_ARE_IN_AN_ALLIANCE_WITH_THE_CASTLE_OWNING_CLAN(690),
	/**
	 * Field THE_OTHER_PARTY_IS_FROZEN.
	 */
	THE_OTHER_PARTY_IS_FROZEN(692),
	/**
	 * Field NO_PACKAGES_HAVE_ARRIVED.
	 */
	NO_PACKAGES_HAVE_ARRIVED(694),
	/**
	 * Field YOU_DO_NOT_HAVE_ENOUGH_REQUIRED_ITEMS.
	 */
	YOU_DO_NOT_HAVE_ENOUGH_REQUIRED_ITEMS(701),
	/**
	 * Field IF_A_BASE_CAMP_DOES_NOT_EXIST_RESURRECTION_IS_NOT_POSSIBLE.
	 */
	IF_A_BASE_CAMP_DOES_NOT_EXIST_RESURRECTION_IS_NOT_POSSIBLE(716),
	/**
	 * Field THE_GUARDIAN_TOWER_HAS_BEEN_DESTROYED_AND_RESURRECTION_IS_NOT_POSSIBLE.
	 */
	THE_GUARDIAN_TOWER_HAS_BEEN_DESTROYED_AND_RESURRECTION_IS_NOT_POSSIBLE(717),
	/**
	 * Field THE_EFFECT_OF_S1_HAS_BEEN_REMOVED.
	 */
	THE_EFFECT_OF_S1_HAS_BEEN_REMOVED(749),
	/**
	 * Field THERE_ARE_NO_OTHER_SKILLS_TO_LEARN.
	 */
	THERE_ARE_NO_OTHER_SKILLS_TO_LEARN(750),
	/**
	 * Field YOU_CANNOT_POSITION_MERCENARIES_HERE.
	 */
	YOU_CANNOT_POSITION_MERCENARIES_HERE(753),
	/**
	 * Field THE_CLAN_HALL_WHICH_WAS_PUT_UP_FOR_AUCTION_HAS_BEEN_AWARDED_TO_S1_CLAN.
	 */
	THE_CLAN_HALL_WHICH_WAS_PUT_UP_FOR_AUCTION_HAS_BEEN_AWARDED_TO_S1_CLAN(776),
	/**
	 * Field THE_CLAN_HALL_WHICH_HAD_BEEN_PUT_UP_FOR_AUCTION_WAS_NOT_SOLD_AND_THEREFORE_HAS_BEEN_RELISTED.
	 */
	THE_CLAN_HALL_WHICH_HAD_BEEN_PUT_UP_FOR_AUCTION_WAS_NOT_SOLD_AND_THEREFORE_HAS_BEEN_RELISTED(777),
	/**
	 * Field OBSERVATION_IS_ONLY_POSSIBLE_DURING_A_SIEGE.
	 */
	OBSERVATION_IS_ONLY_POSSIBLE_DURING_A_SIEGE(780),
	/**
	 * Field THE_TRYOUTS_ARE_FINISHED.
	 */
	THE_TRYOUTS_ARE_FINISHED(787),
	/**
	 * Field THE_FINALS_ARE_FINISHED.
	 */
	THE_FINALS_ARE_FINISHED(788),
	/**
	 * Field THE_TRYOUTS_HAVE_BEGUN.
	 */
	THE_TRYOUTS_HAVE_BEGUN(789),
	/**
	 * Field THE_FINALS_HAVE_BEGUN.
	 */
	THE_FINALS_HAVE_BEGUN(790),
	/**
	 * Field THE_FINAL_MATCH_IS_ABOUT_TO_BEGIN.
	 */
	THE_FINAL_MATCH_IS_ABOUT_TO_BEGIN(791),
	/**
	 * Field YOU_ARE_NOT_AUTHORIZED_TO_DO_THAT.
	 */
	YOU_ARE_NOT_AUTHORIZED_TO_DO_THAT(794),
	/**
	 * Field YOU_ARE_TOO_LATE_THE_REGISTRATION_PERIOD_IS_OVER.
	 */
	YOU_ARE_TOO_LATE_THE_REGISTRATION_PERIOD_IS_OVER(800),
	/**
	 * Field THE_TRYOUTS_ARE_ABOUT_TO_BEGIN.
	 */
	THE_TRYOUTS_ARE_ABOUT_TO_BEGIN(815),
	/**
	 * Field THE_SIEGE_OF_S1_IS_FINISHED.
	 */
	THE_SIEGE_OF_S1_IS_FINISHED(843),
	/**
	 * Field THE_SIEGE_TO_CONQUER_S1_HAS_BEGUN.
	 */
	THE_SIEGE_TO_CONQUER_S1_HAS_BEGUN(844),
	/**
	 * Field THE_DEADLINE_TO_REGISTER_FOR_THE_SIEGE_OF_S1_HAS_PASSED.
	 */
	THE_DEADLINE_TO_REGISTER_FOR_THE_SIEGE_OF_S1_HAS_PASSED(845),
	/**
	 * Field THE_SIEGE_OF_S1_HAS_BEEN_CANCELED_DUE_TO_LACK_OF_INTEREST.
	 */
	THE_SIEGE_OF_S1_HAS_BEEN_CANCELED_DUE_TO_LACK_OF_INTEREST(846),
	/**
	 * Field A_CLAN_THAT_OWNS_A_CLAN_HALL_MAY_NOT_PARTICIPATE_IN_A_CLAN_HALL_SIEGE.
	 */
	A_CLAN_THAT_OWNS_A_CLAN_HALL_MAY_NOT_PARTICIPATE_IN_A_CLAN_HALL_SIEGE(847),
	/**
	 * Field S1_CLAN_HAS_DEFEATED_S2.
	 */
	S1_CLAN_HAS_DEFEATED_S2(855),
	/**
	 * Field THE_SIEGE_OF_S1_HAS_ENDED_IN_A_DRAW.
	 */
	THE_SIEGE_OF_S1_HAS_ENDED_IN_A_DRAW(856),
	/**
	 * Field THE_SEED_HAS_BEEN_SOWN.
	 */
	THE_SEED_HAS_BEEN_SOWN(871),
	/**
	 * Field THIS_SEED_MAY_NOT_BE_SOWN_HERE.
	 */
	THIS_SEED_MAY_NOT_BE_SOWN_HERE(872),
	/**
	 * Field THE_SYMBOL_HAS_BEEN_ADDED.
	 */
	THE_SYMBOL_HAS_BEEN_ADDED(877),
	/**
	 * Field THE_PRELIMINARY_MATCH_OF_S1_HAS_ENDED_IN_A_DRAW.
	 */
	THE_PRELIMINARY_MATCH_OF_S1_HAS_ENDED_IN_A_DRAW(858),
	/**
	 * Field THE_SYMBOL_HAS_BEEN_DELETED.
	 */
	THE_SYMBOL_HAS_BEEN_DELETED(878),
	/**
	 * Field THE_MANOR_SYSTEM_IS_CURRENTLY_UNDER_MAINTENANCE.
	 */
	THE_MANOR_SYSTEM_IS_CURRENTLY_UNDER_MAINTENANCE(879),
	/**
	 * Field THE_TRANSACTION_IS_COMPLETE.
	 */
	THE_TRANSACTION_IS_COMPLETE(880),
	/**
	 * Field THE_SYMBOL_CANNOT_BE_DRAWN.
	 */
	THE_SYMBOL_CANNOT_BE_DRAWN(899),
	/**
	 * Field NO_SLOT_EXISTS_TO_DRAW_THE_SYMBOL.
	 */
	NO_SLOT_EXISTS_TO_DRAW_THE_SYMBOL(900),
	/**
	 * Field THE_SOUL_CRYSTAL_SUCCEEDED_IN_ABSORBING_A_SOUL.
	 */
	THE_SOUL_CRYSTAL_SUCCEEDED_IN_ABSORBING_A_SOUL(974),
	/**
	 * Field THE_SOUL_CRYSTAL_WAS_NOT_ABLE_TO_ABSORB_THE_SOUL.
	 */
	THE_SOUL_CRYSTAL_WAS_NOT_ABLE_TO_ABSORB_THE_SOUL(975),
	/**
	 * Field THE_SOUL_CRYSTAL_BROKE_BECAUSE_IT_WAS_NOT_ABLE_TO_ENDURE_THE_SOUL_ENERGY.
	 */
	THE_SOUL_CRYSTAL_BROKE_BECAUSE_IT_WAS_NOT_ABLE_TO_ENDURE_THE_SOUL_ENERGY(976),
	/**
	 * Field THE_SOUL_CRYSTAL_CAUSED_RESONATION_AND_FAILED_AT_ABSORBING_A_SOUL.
	 */
	THE_SOUL_CRYSTAL_CAUSED_RESONATION_AND_FAILED_AT_ABSORBING_A_SOUL(977),
	/**
	 * Field THE_SOUL_CRYSTAL_IS_REFUSING_TO_ABSORB_THE_SOUL.
	 */
	THE_SOUL_CRYSTAL_IS_REFUSING_TO_ABSORB_THE_SOUL(978),
	/**
	 * Field YOU_HAVE_REGISTERED_FOR_A_CLAN_HALL_AUCTION.
	 */
	YOU_HAVE_REGISTERED_FOR_A_CLAN_HALL_AUCTION(1004),
	/**
	 * Field THERE_IS_NOT_ENOUGH_ADENA_IN_THE_CLAN_HALL_WAREHOUSE.
	 */
	THERE_IS_NOT_ENOUGH_ADENA_IN_THE_CLAN_HALL_WAREHOUSE(1005),
	/**
	 * Field YOUR_BID_HAS_BEEN_SUCCESSFULLY_PLACED.
	 */
	YOUR_BID_HAS_BEEN_SUCCESSFULLY_PLACED(1006),
	/**
	 * Field A_HUNGRY_STRIDER_CANNOT_BE_MOUNTED_OR_DISMOUNTED.
	 */
	A_HUNGRY_STRIDER_CANNOT_BE_MOUNTED_OR_DISMOUNTED(1008),
	/**
	 * Field A_STRIDER_CANNOT_BE_RIDDEN_WHEN_DEAD.
	 */
	A_STRIDER_CANNOT_BE_RIDDEN_WHEN_DEAD(1009),
	/**
	 * Field A_DEAD_STRIDER_CANNOT_BE_RIDDEN.
	 */
	A_DEAD_STRIDER_CANNOT_BE_RIDDEN(1010),
	/**
	 * Field A_STRIDER_IN_BATTLE_CANNOT_BE_RIDDEN.
	 */
	A_STRIDER_IN_BATTLE_CANNOT_BE_RIDDEN(1011),
	/**
	 * Field A_STRIDER_CANNOT_BE_RIDDEN_WHILE_IN_BATTLE.
	 */
	A_STRIDER_CANNOT_BE_RIDDEN_WHILE_IN_BATTLE(1012),
	/**
	 * Field A_STRIDER_CAN_BE_RIDDEN_ONLY_WHEN_STANDING.
	 */
	A_STRIDER_CAN_BE_RIDDEN_ONLY_WHEN_STANDING(1013),
	/**
	 * Field PETS_CRITICAL_HIT.
	 */
	PETS_CRITICAL_HIT(1017),
	/**
	 * Field SUMMONED_MONSTERS_CRITICAL_HIT.
	 */
	SUMMONED_MONSTERS_CRITICAL_HIT(1028),
	/**
	 * Field YOU_HAVE_EXCEEDED_THE_QUANTITY_THAT_CAN_BE_INPUTTED.
	 */
	YOU_HAVE_EXCEEDED_THE_QUANTITY_THAT_CAN_BE_INPUTTED(1036),
	/**
	 * Field PAYMENT_FOR_YOUR_CLAN_HALL_HAS_NOT_BEEN_MADE_PLEASE_ME_PAYMENT_TO_YOUR_CLAN_WAREHOUSE_BY_S1_TOMORROW.
	 */
	PAYMENT_FOR_YOUR_CLAN_HALL_HAS_NOT_BEEN_MADE_PLEASE_ME_PAYMENT_TO_YOUR_CLAN_WAREHOUSE_BY_S1_TOMORROW(1051),
	/**
	 * Field THE_CLAN_HALL_FEE_IS_ONE_WEEK_OVERDUE_THEREFORE_THE_CLAN_HALL_OWNERSHIP_HAS_BEEN_REVOKED.
	 */
	THE_CLAN_HALL_FEE_IS_ONE_WEEK_OVERDUE_THEREFORE_THE_CLAN_HALL_OWNERSHIP_HAS_BEEN_REVOKED(1052),
	/**
	 * Field IT_IS_NOT_POSSIBLE_TO_RESURRECT_IN_BATTLEFIELDS_WHERE_A_SIEGE_WAR_IS_TAKING_PLACE.
	 */
	IT_IS_NOT_POSSIBLE_TO_RESURRECT_IN_BATTLEFIELDS_WHERE_A_SIEGE_WAR_IS_TAKING_PLACE(1053),
	/**
	 * Field WHILE_OPERATING_A_PRIVATE_STORE_OR_WORKSHOP_YOU_CANNOT_DISCARD_DESTROY_OR_TRADE_AN_ITEM.
	 */
	WHILE_OPERATING_A_PRIVATE_STORE_OR_WORKSHOP_YOU_CANNOT_DISCARD_DESTROY_OR_TRADE_AN_ITEM(1065),
	/**
	 * Field S1_HP_HAS_BEEN_RESTORED.
	 */
	S1_HP_HAS_BEEN_RESTORED(1066),
	/**
	 * Field S2_HP_HAS_BEEN_RESTORED_BY_C1.
	 */
	S2_HP_HAS_BEEN_RESTORED_BY_C1(1067),
	/**
	 * Field S1_MP_HAS_BEEN_RESTORED.
	 */
	S1_MP_HAS_BEEN_RESTORED(1068),
	/**
	 * Field S2_MP_HAS_BEEN_RESTORED_BY_C1.
	 */
	S2_MP_HAS_BEEN_RESTORED_BY_C1(1069),
	/**
	 * Field THE_BID_AMOUNT_MUST_BE_HIGHER_THAN_THE_PREVIOUS_BID.
	 */
	THE_BID_AMOUNT_MUST_BE_HIGHER_THAN_THE_PREVIOUS_BID(1075),
	/**
	 * Field A_CLAN_MEMBER_MAY_NOT_BE_DISMISSED_DURING_COMBAT.
	 */
	A_CLAN_MEMBER_MAY_NOT_BE_DISMISSED_DURING_COMBAT(1117),
	/**
	 * Field WOULD_YOU_LIKE_TO_OPEN_THE_GATE.
	 */
	WOULD_YOU_LIKE_TO_OPEN_THE_GATE(1140),
	/**
	 * Field WOULD_YOU_LIKE_TO_CLOSE_THE_GATE.
	 */
	WOULD_YOU_LIKE_TO_CLOSE_THE_GATE(1141),
	/**
	 * Field SINCE_S1_ALREADY_EXISTS_NEARBY_YOU_CANNOT_SUMMON_IT_AGAIN.
	 */
	SINCE_S1_ALREADY_EXISTS_NEARBY_YOU_CANNOT_SUMMON_IT_AGAIN(1142),
	/**
	 * Field THE_TEMPORARY_ALLIANCE_OF_THE_CASTLE_ATTACKER_TEAM_IS_IN_EFFECT.
	 */
	THE_TEMPORARY_ALLIANCE_OF_THE_CASTLE_ATTACKER_TEAM_IS_IN_EFFECT(1189),
	/**
	 * Field THE_TEMPORARY_ALLIANCE_OF_THE_CASTLE_ATTACKER_TEAM_HAS_BEEN_DISSOLVED.
	 */
	THE_TEMPORARY_ALLIANCE_OF_THE_CASTLE_ATTACKER_TEAM_HAS_BEEN_DISSOLVED(1190),
	/**
	 * Field A_MERCENARY_CAN_BE_ASSIGNED_TO_A_POSITION_FROM_THE_BEGINNING_OF_THE_SEAL_VALIDATION_PERIOD_UNTIL_THE_TIME_WHEN_A_SIEGE_STARTS.
	 */
	A_MERCENARY_CAN_BE_ASSIGNED_TO_A_POSITION_FROM_THE_BEGINNING_OF_THE_SEAL_VALIDATION_PERIOD_UNTIL_THE_TIME_WHEN_A_SIEGE_STARTS(1194),
	/**
	 * Field THIS_MERCENARY_CANNOT_BE_ASSIGNED_TO_A_POSITION_BY_USING_THE_SEAL_OF_STRIFE.
	 */
	THIS_MERCENARY_CANNOT_BE_ASSIGNED_TO_A_POSITION_BY_USING_THE_SEAL_OF_STRIFE(1195),
	/**
	 * Field C1_DIED_AND_DROPPED_S3_S2.
	 */
	C1_DIED_AND_DROPPED_S3_S2(1208),
	/**
	 * Field C1_HAS_DIED_AND_DROPPED_S2_ADENA.
	 */
	C1_HAS_DIED_AND_DROPPED_S2_ADENA(1246),
	/**
	 * Field THE_NEW_SUBCLASS_HAS_BEEN_ADDED.
	 */
	THE_NEW_SUBCLASS_HAS_BEEN_ADDED(1269),
	/**
	 * Field YOU_HAVE_SUCCESSFULLY_SWITCHED_S1_TO_S2.
	 */
	YOU_HAVE_SUCCESSFULLY_SWITCHED_S1_TO_S2(1270),
	/**
	 * Field YOUR_EXCELLENT_SHIELD_DEFENSE_WAS_A_SUCCESS.
	 */
	YOUR_EXCELLENT_SHIELD_DEFENSE_WAS_A_SUCCESS(1281),
	/**
	 * Field SUBCLASSES_MAY_NOT_BE_CREATED_OR_CHANGED_WHILE_A_SKILL_IS_IN_USE.
	 */
	SUBCLASSES_MAY_NOT_BE_CREATED_OR_CHANGED_WHILE_A_SKILL_IS_IN_USE(1295),
	/**
	 * Field YOU_HAVE_EXITED_THE_PARTY_ROOM.
	 */
	YOU_HAVE_EXITED_THE_PARTY_ROOM(1391),
	/**
	 * Field C1_HAS_LEFT_THE_PARTY_ROOM.
	 */
	C1_HAS_LEFT_THE_PARTY_ROOM(1392),
	/**
	 * Field YOU_HAVE_BEEN_OUSTED_FROM_THE_PARTY_ROOM.
	 */
	YOU_HAVE_BEEN_OUSTED_FROM_THE_PARTY_ROOM(1393),
	/**
	 * Field C1_HAS_BEEN_KICKED_FROM_THE_PARTY_ROOM.
	 */
	C1_HAS_BEEN_KICKED_FROM_THE_PARTY_ROOM(1394),
	/**
	 * Field THE_PARTY_ROOM_HAS_BEEN_DISBANDED.
	 */
	THE_PARTY_ROOM_HAS_BEEN_DISBANDED(1395),
	/**
	 * Field THE_LIST_OF_PARTY_ROOMS_CAN_ONLY_BE_VIEWED_BY_A_PERSON_WHO_IS_NOT_PART_OF_A_PARTY.
	 */
	THE_LIST_OF_PARTY_ROOMS_CAN_ONLY_BE_VIEWED_BY_A_PERSON_WHO_IS_NOT_PART_OF_A_PARTY(1396),
	/**
	 * Field S1_CP_HAS_BEEN_RESTORED.
	 */
	S1_CP_HAS_BEEN_RESTORED(1405),
	/**
	 * Field S2_CP_HAS_BEEN_RESTORED_BY_C1.
	 */
	S2_CP_HAS_BEEN_RESTORED_BY_C1(1406),
	/**
	 * Field YOU_DO_NOT_MEET_THE_REQUIREMENTS_TO_ENTER_THAT_PARTY_ROOM.
	 */
	YOU_DO_NOT_MEET_THE_REQUIREMENTS_TO_ENTER_THAT_PARTY_ROOM(1413),
	/**
	 * Field YOU_CANNOT_DO_THAT_WHILE_FISHING_2.
	 */
	YOU_CANNOT_DO_THAT_WHILE_FISHING_2(1471),
	/**
	 * Field YOUR_OPPONENT_MADE_HASTE_WITH_THEIR_TAIL_BETWEEN_THEIR_LEGS_THE_MATCH_HAS_BEEN_CANCELLED.
	 */
	YOUR_OPPONENT_MADE_HASTE_WITH_THEIR_TAIL_BETWEEN_THEIR_LEGS_THE_MATCH_HAS_BEEN_CANCELLED(1493),
	/**
	 * Field YOUR_OPPONENT_DOES_NOT_MEET_THE_REQUIREMENTS_TO_DO_BATTLE_THE_MATCH_HAS_BEEN_CANCELLED.
	 */
	YOUR_OPPONENT_DOES_NOT_MEET_THE_REQUIREMENTS_TO_DO_BATTLE_THE_MATCH_HAS_BEEN_CANCELLED(1494),
	/**
	 * Field THE_MATCH_WILL_START_IN_S1_SECONDS.
	 */
	THE_MATCH_WILL_START_IN_S1_SECONDS(1495),
	/**
	 * Field THE_MATCH_HAS_STARTED.
	 */
	THE_MATCH_HAS_STARTED(1496),
	/**
	 * Field CONGRATULATIONS_C1_YOU_WIN_THE_MATCH.
	 */
	CONGRATULATIONS_C1_YOU_WIN_THE_MATCH(1497),
	/**
	 * Field THERE_IS_NO_VICTOR_THE_MATCH_ENDS_IN_A_TIE.
	 */
	THERE_IS_NO_VICTOR_THE_MATCH_ENDS_IN_A_TIE(1498),
	/**
	 * Field YOU_WILL_BE_MOVED_BACK_TO_TOWN_IN_S1_SECONDS.
	 */
	YOU_WILL_BE_MOVED_BACK_TO_TOWN_IN_S1_SECONDS(1499),
	/**
	 * Field C1_DOES_NOT_MEET_THE_PARTICIPATION_REQUIREMENTS_SUBCLASS_CHARACTER_CANNOT_PARTICIPATE_IN_THE_OLYMPIAD.
	 */
	C1_DOES_NOT_MEET_THE_PARTICIPATION_REQUIREMENTS_SUBCLASS_CHARACTER_CANNOT_PARTICIPATE_IN_THE_OLYMPIAD(1500),
	/**
	 * Field C1_DOES_NOT_MEET_THE_PARTICIPATION_REQUIREMENTS_ONLY_NOBLESSE_CHARACTERS_CAN_PARTICIPATE_IN_THE_OLYMPIAD.
	 */
	C1_DOES_NOT_MEET_THE_PARTICIPATION_REQUIREMENTS_ONLY_NOBLESSE_CHARACTERS_CAN_PARTICIPATE_IN_THE_OLYMPIAD(1501),
	/**
	 * Field C1_IS_ALREADY_REGISTERED_ON_THE_MATCH_WAITING_LIST.
	 */
	C1_IS_ALREADY_REGISTERED_ON_THE_MATCH_WAITING_LIST(1502),
	/**
	 * Field YOU_HAVE_BEEN_REGISTERED_FOR_THE_GRAND_OLYMPIAD_WAITING_LIST_FOR_A_CLASS_SPECIFIC_MATCH.
	 */
	YOU_HAVE_BEEN_REGISTERED_FOR_THE_GRAND_OLYMPIAD_WAITING_LIST_FOR_A_CLASS_SPECIFIC_MATCH(1503),
	/**
	 * Field YOU_ARE_CURRENTLY_REGISTERED_FOR_A_1V1_CLASS_IRRELEVANT_MATCH.
	 */
	YOU_ARE_CURRENTLY_REGISTERED_FOR_A_1V1_CLASS_IRRELEVANT_MATCH(1504),
	/**
	 * Field YOU_HAVE_BEEN_REMOVED_FROM_THE_GRAND_OLYMPIAD_WAITING_LIST.
	 */
	YOU_HAVE_BEEN_REMOVED_FROM_THE_GRAND_OLYMPIAD_WAITING_LIST(1505),
	/**
	 * Field YOU_ARE_NOT_CURRENTLY_REGISTERED_FOR_THE_GRAND_OLYMPIAD.
	 */
	YOU_ARE_NOT_CURRENTLY_REGISTERED_FOR_THE_GRAND_OLYMPIAD(1506),
	/**
	 * Field YOU_CANNOT_EQUIP_THAT_ITEM_IN_A_GRAND_OLYMPIAD_MATCH.
	 */
	YOU_CANNOT_EQUIP_THAT_ITEM_IN_A_GRAND_OLYMPIAD_MATCH(1507),
	/**
	 * Field YOU_CANNOT_USE_THAT_ITEM_IN_A_GRAND_OLYMPIAD_MATCH.
	 */
	YOU_CANNOT_USE_THAT_ITEM_IN_A_GRAND_OLYMPIAD_MATCH(1508),
	/**
	 * Field YOU_CANNOT_USE_THAT_SKILL_IN_A_GRAND_OLYMPIAD_MATCH.
	 */
	YOU_CANNOT_USE_THAT_SKILL_IN_A_GRAND_OLYMPIAD_MATCH(1509),
	/**
	 * Field C1_IS_MAKING_AN_ATTEMPT_TO_RESURRECT_YOU_IF_YOU_CHOOSE_THIS_PATH_S2_EXPERIENCE_WILL_BE_RETURNED_FOR_YOU.
	 */
	C1_IS_MAKING_AN_ATTEMPT_TO_RESURRECT_YOU_IF_YOU_CHOOSE_THIS_PATH_S2_EXPERIENCE_WILL_BE_RETURNED_FOR_YOU(1510),
	/**
	 * Field THE_TARGET_IS_UNAVAILABLE_FOR_SEEDING.
	 */
	THE_TARGET_IS_UNAVAILABLE_FOR_SEEDING(1516),
	/**
	 * Field THE_BLESSED_ENCHANT_FAILED.
	 */
	THE_BLESSED_ENCHANT_FAILED(1517),
	/**
	 * Field YOU_SHOULD_RELEASE_YOUR_PET_OR_SERVITOR_SO_THAT_IT_DOES_NOT_FALL_OFF_OF_THE_BOAT_AND_DROWN.
	 */
	YOU_SHOULD_RELEASE_YOUR_PET_OR_SERVITOR_SO_THAT_IT_DOES_NOT_FALL_OFF_OF_THE_BOAT_AND_DROWN(1523),
	/**
	 * Field WELCOME_TO_RUNE_HARBOR.
	 */
	WELCOME_TO_RUNE_HARBOR(1620),
	/**
	 * Field THE_GRAND_OLYMPIAD_GAMES_ARE_NOT_CURRENTLY_IN_PROGRESS.
	 */
	THE_GRAND_OLYMPIAD_GAMES_ARE_NOT_CURRENTLY_IN_PROGRESS(1651),
	/**
	 * Field C1_HAS_EARNED_S2_POINTS_IN_THE_GRAND_OLYMPIAD_GAMES.
	 */
	C1_HAS_EARNED_S2_POINTS_IN_THE_GRAND_OLYMPIAD_GAMES(1657),
	/**
	 * Field C1_HAS_LOST_S2_POINTS_IN_THE_GRAND_OLYMPIAD_GAMES.
	 */
	C1_HAS_LOST_S2_POINTS_IN_THE_GRAND_OLYMPIAD_GAMES(1658),
	/**
	 * Field LETHAL_STRIKE.
	 */
	LETHAL_STRIKE(1667),
	/**
	 * Field YOUR_LETHAL_STRIKE_WAS_SUCCESSFUL.
	 */
	YOUR_LETHAL_STRIKE_WAS_SUCCESSFUL(1668),
	/**
	 * Field THERE_WAS_NOTHING_FOUND_INSIDE.
	 */
	THERE_WAS_NOTHING_FOUND_INSIDE(1669),
	/**
	 * Field FOR_THE_CURRENT_GRAND_OLYMPIAD_YOU_HAVE_PARTICIPATED_IN_S1_MATCHES_S2_WINS_S3_DEFEATS_YOU_CURRENTLY_HAVE_S4_OLYMPIAD_POINTS.
	 */
	FOR_THE_CURRENT_GRAND_OLYMPIAD_YOU_HAVE_PARTICIPATED_IN_S1_MATCHES_S2_WINS_S3_DEFEATS_YOU_CURRENTLY_HAVE_S4_OLYMPIAD_POINTS(1673),
	/**
	 * Field THIS_COMMAND_CAN_ONLY_BE_USED_BY_A_NOBLESSE.
	 */
	THIS_COMMAND_CAN_ONLY_BE_USED_BY_A_NOBLESSE(1674),
	/**
	 * Field A_MANOR_CANNOT_BE_SET_UP_BETWEEN_430_AM_AND_8_PM.
	 */
	A_MANOR_CANNOT_BE_SET_UP_BETWEEN_430_AM_AND_8_PM(1675),
	/**
	 * Field THIS_AREA_CANNOT_BE_ENTERED_WHILE_MOUNTED_ATOP_OF_A_WYVERN.
	 */
	THIS_AREA_CANNOT_BE_ENTERED_WHILE_MOUNTED_ATOP_OF_A_WYVERN(1687),
	/**
	 * Field YOU_CANNOT_ENCHANT_WHILE_OPERATING_A_PRIVATE_STORE_OR_PRIVATE_WORKSHOP.
	 */
	YOU_CANNOT_ENCHANT_WHILE_OPERATING_A_PRIVATE_STORE_OR_PRIVATE_WORKSHOP(1688),
	/**
	 * Field C1_IS_ALREADY_REGISTERED_ON_THE_CLASS_MATCH_WAITING_LIST.
	 */
	C1_IS_ALREADY_REGISTERED_ON_THE_CLASS_MATCH_WAITING_LIST(1689),
	/**
	 * Field C1_IS_ALREADY_REGISTERED_ON_THE_WAITING_LIST_FOR_THE_CLASS_IRRELEVANT_INDIVIDUAL_MATCH.
	 */
	C1_IS_ALREADY_REGISTERED_ON_THE_WAITING_LIST_FOR_THE_CLASS_IRRELEVANT_INDIVIDUAL_MATCH(1690),
	/**
	 * Field YOU_MAY_NOT_OBSERVE_A_GRAND_OLYMPIAD_GAMES_MATCH_WHILE_YOU_ARE_ON_THE_WAITING_LIST.
	 */
	YOU_MAY_NOT_OBSERVE_A_GRAND_OLYMPIAD_GAMES_MATCH_WHILE_YOU_ARE_ON_THE_WAITING_LIST(1693),
	/**
	 * Field ONLY_A_CLAN_LEADER_THAT_IS_A_NOBLESSE_CAN_VIEW_THE_SIEGE_WAR_STATUS_WINDOW_DURING_A_SIEGE_WAR.
	 */
	ONLY_A_CLAN_LEADER_THAT_IS_A_NOBLESSE_CAN_VIEW_THE_SIEGE_WAR_STATUS_WINDOW_DURING_A_SIEGE_WAR(1694),
	/**
	 * Field YOUR_APPRENTICE_C1_HAS_LOGGED_IN.
	 */
	YOUR_APPRENTICE_C1_HAS_LOGGED_IN(1756),
	/**
	 * Field YOUR_APPRENTICE_C1_HAS_LOGGED_OUT.
	 */
	YOUR_APPRENTICE_C1_HAS_LOGGED_OUT(1757),
	/**
	 * Field YOUR_SPONSOR_C1_HAS_LOGGED_IN.
	 */
	YOUR_SPONSOR_C1_HAS_LOGGED_IN(1758),
	/**
	 * Field YOUR_SPONSOR_C1_HAS_LOGGED_OUT.
	 */
	YOUR_SPONSOR_C1_HAS_LOGGED_OUT(1759),
	/**
	 * Field SINCE_YOUR_CLAN_EMERGED_VICTORIOUS_FROM_THE_SIEGE_S1_POINTS_HAVE_BEEN_ADDED_TO_YOUR_CLANS_REPUTATION_SCORE.
	 */
	SINCE_YOUR_CLAN_EMERGED_VICTORIOUS_FROM_THE_SIEGE_S1_POINTS_HAVE_BEEN_ADDED_TO_YOUR_CLANS_REPUTATION_SCORE(1773),
	/**
	 * Field YOUR_CLAN_HAS_FAILED_TO_DEFEND_THE_CASTLE_S1_POINTS_HAVE_BEEN_DEDUCTED_FROM_YOU_CLAN_REPUTATION_SCORE_AND_ADDED_TO_YOUR_OPPONENTS.
	 */
	YOUR_CLAN_HAS_FAILED_TO_DEFEND_THE_CASTLE_S1_POINTS_HAVE_BEEN_DEDUCTED_FROM_YOU_CLAN_REPUTATION_SCORE_AND_ADDED_TO_YOUR_OPPONENTS(1784),
	/**
	 * Field THE_CLAN_SKILL_S1_HAS_BEEN_ADDED.
	 */
	THE_CLAN_SKILL_S1_HAS_BEEN_ADDED(1788),
	/**
	 * Field THE_REGISTRATION_PERIOD_FOR_A_CLAN_HALL_WAR_HAS_ENDED.
	 */
	THE_REGISTRATION_PERIOD_FOR_A_CLAN_HALL_WAR_HAS_ENDED(1823),
	/**
	 * Field YOU_HAVE_BEEN_REGISTERED_FOR_A_CLAN_HALL_WAR.
	 */
	YOU_HAVE_BEEN_REGISTERED_FOR_A_CLAN_HALL_WAR(1824),
	/**
	 * Field YOU_HAVE_FAILED_IN_YOUR_ATTEMPT_TO_REGISTER_FOR_THE_CLAN_HALL_WAR.
	 */
	YOU_HAVE_FAILED_IN_YOUR_ATTEMPT_TO_REGISTER_FOR_THE_CLAN_HALL_WAR(1825),
	/**
	 * Field IN_S1_MINUTES_THE_GAME_WILL_BEGIN_ALL_PLAYERS_MUST_HURRY_AND_MOVE_TO_THE_LEFT_SIDE_OF_THE_CLAN_HALLS_ARENA.
	 */
	IN_S1_MINUTES_THE_GAME_WILL_BEGIN_ALL_PLAYERS_MUST_HURRY_AND_MOVE_TO_THE_LEFT_SIDE_OF_THE_CLAN_HALLS_ARENA(1826),
	/**
	 * Field IN_S1_MINUTES_THE_GAME_WILL_BEGIN_ALL_PLAYERS_PLEASE_ENTER_THE_ARENA_NOW.
	 */
	IN_S1_MINUTES_THE_GAME_WILL_BEGIN_ALL_PLAYERS_PLEASE_ENTER_THE_ARENA_NOW(1827),
	/**
	 * Field IN_S1_SECONDS_THE_GAME_WILL_BEGIN.
	 */
	IN_S1_SECONDS_THE_GAME_WILL_BEGIN(1828),
	/**
	 * Field C1_IS_NOT_ALLOWED_TO_USE_THE_PARTY_ROOM_INVITE_COMMAND.
	 */
	C1_IS_NOT_ALLOWED_TO_USE_THE_PARTY_ROOM_INVITE_COMMAND(1830),
	/**
	 * Field C1_DOES_NOT_MEET_THE_CONDITIONS_OF_THE_PARTY_ROOM.
	 */
	C1_DOES_NOT_MEET_THE_CONDITIONS_OF_THE_PARTY_ROOM(1831),
	/**
	 * Field ONLY_A_ROOM_LEADER_MAY_INVITE_OTHERS_TO_A_PARTY_ROOM.
	 */
	ONLY_A_ROOM_LEADER_MAY_INVITE_OTHERS_TO_A_PARTY_ROOM(1832),
	/**
	 * Field THE_PARTY_ROOM_IS_FULL.
	 */
	THE_PARTY_ROOM_IS_FULL(1834),
	/**
	 * Field THIS_CLAN_HALL_WAR_HAS_BEEN_CANCELLED.
	 */
	THIS_CLAN_HALL_WAR_HAS_BEEN_CANCELLED(1841),
	/**
	 * Field C1_WISHES_TO_SUMMON_YOU_FROM_S2.
	 */
	C1_WISHES_TO_SUMMON_YOU_FROM_S2(1842),
	/**
	 * Field THE_CLAN_REPUTATION_SCORE_IS_TOO_LOW.
	 */
	THE_CLAN_REPUTATION_SCORE_IS_TOO_LOW(1860),
	/**
	 * Field YOUR_PETSERVITOR_IS_UNRESPONSIVE_AND_WILL_NOT_OBEY_ANY_ORDERS.
	 */
	YOUR_PETSERVITOR_IS_UNRESPONSIVE_AND_WILL_NOT_OBEY_ANY_ORDERS(1864),
	/**
	 * Field THE_PRELIMINARY_MATCH_WILL_BEGIN_IN_S1_SECONDS.
	 */
	THE_PRELIMINARY_MATCH_WILL_BEGIN_IN_S1_SECONDS(1881),
	/**
	 * Field THERE_ARE_NO_OFFERINGS_I_OWN_OR_I_MADE_A_BID_FOR.
	 */
	THERE_ARE_NO_OFFERINGS_I_OWN_OR_I_MADE_A_BID_FOR(1883),
	/**
	 * Field YOU_MAY_NOT_USE_ITEMS_IN_A_PRIVATE_STORE_OR_PRIVATE_WORK_SHOP.
	 */
	YOU_MAY_NOT_USE_ITEMS_IN_A_PRIVATE_STORE_OR_PRIVATE_WORK_SHOP(1891),
	/**
	 * Field A_SUBCLASS_CANNOT_BE_CREATED_OR_CHANGED_WHILE_YOU_ARE_OVER_YOUR_WEIGHT_LIMIT.
	 */
	A_SUBCLASS_CANNOT_BE_CREATED_OR_CHANGED_WHILE_YOU_ARE_OVER_YOUR_WEIGHT_LIMIT(1894),
	/**
	 * Field C1_HAS_ENTERED_THE_PARTY_ROOM.
	 */
	C1_HAS_ENTERED_THE_PARTY_ROOM(1900),
	/**
	 * Field S1_HAS_SENT_AN_INVITATION_TO_ROOM_S2.
	 */
	S1_HAS_SENT_AN_INVITATION_TO_ROOM_S2(1901),
	/**
	 * Field INCOMPATIBLE_ITEM_GRADE.
	 */
	INCOMPATIBLE_ITEM_GRADE(1902),
	/**
	 * Field A_SUBCLASS_MAY_NOT_BE_CREATED_OR_CHANGED_WHILE_A_SERVITOR_OR_PET_IS_SUMMONED.
	 */
	A_SUBCLASS_MAY_NOT_BE_CREATED_OR_CHANGED_WHILE_A_SERVITOR_OR_PET_IS_SUMMONED(1904),
	/**
	 * Field YOUR_PET_IS_TOO_HIGH_LEVEL_TO_CONTROL.
	 */
	YOUR_PET_IS_TOO_HIGH_LEVEL_TO_CONTROL(1918),
	/**
	 * Field THERE_IS_NO_OPPONENT_TO_RECEIVE_YOUR_CHALLENGE_FOR_A_DUEL.
	 */
	THERE_IS_NO_OPPONENT_TO_RECEIVE_YOUR_CHALLENGE_FOR_A_DUEL(1926),
	/**
	 * Field C1_HAS_BEEN_CHALLENGED_TO_A_DUEL.
	 */
	C1_HAS_BEEN_CHALLENGED_TO_A_DUEL(1927),
	/**
	 * Field C1S_PARTY_HAS_BEEN_CHALLENGED_TO_A_DUEL.
	 */
	C1S_PARTY_HAS_BEEN_CHALLENGED_TO_A_DUEL(1928),
	/**
	 * Field C1_HAS_ACCEPTED_YOUR_CHALLENGE_TO_A_DUEL.
	 */
	C1_HAS_ACCEPTED_YOUR_CHALLENGE_TO_A_DUEL(1929),
	/**
	 * Field YOU_HAVE_ACCEPTED_C1S_CHALLENGE_A_DUEL.
	 */
	YOU_HAVE_ACCEPTED_C1S_CHALLENGE_A_DUEL(1930),
	/**
	 * Field C1_HAS_DECLINED_YOUR_CHALLENGE_TO_A_DUEL.
	 */
	C1_HAS_DECLINED_YOUR_CHALLENGE_TO_A_DUEL(1931),
	/**
	 * Field C1_HAS_DECLINED_YOUR_CHALLENGE_TO_A_DUEL_.
	 */
	C1_HAS_DECLINED_YOUR_CHALLENGE_TO_A_DUEL_(1932),
	/**
	 * Field YOU_HAVE_ACCEPTED_C1S_CHALLENGE_TO_A_PARTY_DUEL.
	 */
	YOU_HAVE_ACCEPTED_C1S_CHALLENGE_TO_A_PARTY_DUEL(1933),
	/**
	 * Field S1_HAS_ACCEPTED_YOUR_CHALLENGE_TO_DUEL_AGAINST_THEIR_PARTY.
	 */
	S1_HAS_ACCEPTED_YOUR_CHALLENGE_TO_DUEL_AGAINST_THEIR_PARTY(1934),
	/**
	 * Field C1_HAS_DECLINED_YOUR_CHALLENGE_TO_A_PARTY_DUEL.
	 */
	C1_HAS_DECLINED_YOUR_CHALLENGE_TO_A_PARTY_DUEL(1935),
	/**
	 * Field THE_OPPOSING_PARTY_HAS_DECLINED_YOUR_CHALLENGE_TO_A_DUEL.
	 */
	THE_OPPOSING_PARTY_HAS_DECLINED_YOUR_CHALLENGE_TO_A_DUEL(1936),
	/**
	 * Field SINCE_THE_PERSON_YOU_CHALLENGED_IS_NOT_CURRENTLY_IN_A_PARTY_THEY_CANNOT_DUEL_AGAINST_YOUR_PARTY.
	 */
	SINCE_THE_PERSON_YOU_CHALLENGED_IS_NOT_CURRENTLY_IN_A_PARTY_THEY_CANNOT_DUEL_AGAINST_YOUR_PARTY(1937),
	/**
	 * Field C1_HAS_CHALLENGED_YOU_TO_A_DUEL.
	 */
	C1_HAS_CHALLENGED_YOU_TO_A_DUEL(1938),
	/**
	 * Field C1S_PARTY_HAS_CHALLENGED_YOUR_PARTY_TO_A_DUEL.
	 */
	C1S_PARTY_HAS_CHALLENGED_YOUR_PARTY_TO_A_DUEL(1939),
	/**
	 * Field YOU_ARE_UNABLE_TO_REQUEST_A_DUEL_AT_THIS_TIME.
	 */
	YOU_ARE_UNABLE_TO_REQUEST_A_DUEL_AT_THIS_TIME(1940),
	/**
	 * Field IN_A_MOMENT_YOU_WILL_BE_TRANSPORTED_TO_THE_SITE_WHERE_THE_DUEL_WILL_TAKE_PLACE.
	 */
	IN_A_MOMENT_YOU_WILL_BE_TRANSPORTED_TO_THE_SITE_WHERE_THE_DUEL_WILL_TAKE_PLACE(1944),
	/**
	 * Field THE_DUEL_WILL_BEGIN_IN_S1_SECONDS.
	 */
	THE_DUEL_WILL_BEGIN_IN_S1_SECONDS(1945),
	/**
	 * Field LET_THE_DUEL_BEGIN.
	 */
	LET_THE_DUEL_BEGIN(1949),
	/**
	 * Field C1_HAS_WON_THE_DUEL.
	 */
	C1_HAS_WON_THE_DUEL(1950),
	/**
	 * Field C1S_PARTY_HAS_WON_THE_DUEL.
	 */
	C1S_PARTY_HAS_WON_THE_DUEL(1951),
	/**
	 * Field THE_DUEL_HAS_ENDED_IN_A_TIE.
	 */
	THE_DUEL_HAS_ENDED_IN_A_TIE(1952),
	/**
	 * Field ONLY_THE_CLAN_LEADER_MAY_ISSUE_COMMANDS.
	 */
	ONLY_THE_CLAN_LEADER_MAY_ISSUE_COMMANDS(1966),
	/**
	 * Field S1.
	 */
	S1(1983),
	/**
	 * Field THE_FERRY_HAS_ARRIVED_AT_PRIMEVAL_ISLE.
	 */
	THE_FERRY_HAS_ARRIVED_AT_PRIMEVAL_ISLE(1988),
	/**
	 * Field THE_FERRY_WILL_LEAVE_FOR_RUNE_HARBOR_AFTER_ANCHORING_FOR_THREE_MINUTES.
	 */
	THE_FERRY_WILL_LEAVE_FOR_RUNE_HARBOR_AFTER_ANCHORING_FOR_THREE_MINUTES(1989),
	/**
	 * Field THE_FERRY_IS_NOW_DEPARTING_PRIMEVAL_ISLE_FOR_RUNE_HARBOR.
	 */
	THE_FERRY_IS_NOW_DEPARTING_PRIMEVAL_ISLE_FOR_RUNE_HARBOR(1990),
	/**
	 * Field THE_FERRY_WILL_LEAVE_FOR_PRIMEVAL_ISLE_AFTER_ANCHORING_FOR_THREE_MINUTES.
	 */
	THE_FERRY_WILL_LEAVE_FOR_PRIMEVAL_ISLE_AFTER_ANCHORING_FOR_THREE_MINUTES(1991),
	/**
	 * Field THE_FERRY_IS_NOW_DEPARTING_RUNE_HARBOR_FOR_PRIMEVAL_ISLE.
	 */
	THE_FERRY_IS_NOW_DEPARTING_RUNE_HARBOR_FOR_PRIMEVAL_ISLE(1992),
	/**
	 * Field THE_FERRY_FROM_PRIMEVAL_ISLE_TO_RUNE_HARBOR_HAS_BEEN_DELAYED.
	 */
	THE_FERRY_FROM_PRIMEVAL_ISLE_TO_RUNE_HARBOR_HAS_BEEN_DELAYED(1993),
	/**
	 * Field THE_FERRY_FROM_RUNE_HARBOR_TO_PRIMEVAL_ISLE_HAS_BEEN_DELAYED.
	 */
	THE_FERRY_FROM_RUNE_HARBOR_TO_PRIMEVAL_ISLE_HAS_BEEN_DELAYED(1994),
	/**
	 * Field C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_ENGAGED_IN_A_PRIVATE_STORE_OR_MANUFACTURE.
	 */
	C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_ENGAGED_IN_A_PRIVATE_STORE_OR_MANUFACTURE(2017),
	/**
	 * Field C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_FISHING.
	 */
	C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_FISHING(2018),
	/**
	 * Field C1_CANNOT_DUEL_BECAUSE_C1S_HP_OR_MP_IS_BELOW_50.
	 */
	C1_CANNOT_DUEL_BECAUSE_C1S_HP_OR_MP_IS_BELOW_50(2019),
	/**
	 * Field C1_CANNOT_MAKE_A_CHALLENGE_TO_A_DUEL_BECAUSE_C1_IS_CURRENTLY_IN_A_DUELPROHIBITED_AREA_PEACEFUL_ZONE__SEVEN_SIGNS_ZONE__NEAR_WATER__RESTART_PROHIBITED_AREA.
	 */
	C1_CANNOT_MAKE_A_CHALLENGE_TO_A_DUEL_BECAUSE_C1_IS_CURRENTLY_IN_A_DUELPROHIBITED_AREA_PEACEFUL_ZONE__SEVEN_SIGNS_ZONE__NEAR_WATER__RESTART_PROHIBITED_AREA(2020),
	/**
	 * Field C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_ENGAGED_IN_BATTLE.
	 */
	C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_ENGAGED_IN_BATTLE(2021),
	/**
	 * Field C1_CANNOT_DUEL_BECAUSE_C1_IS_ALREADY_ENGAGED_IN_A_DUEL.
	 */
	C1_CANNOT_DUEL_BECAUSE_C1_IS_ALREADY_ENGAGED_IN_A_DUEL(2022),
	/**
	 * Field C1_CANNOT_DUEL_BECAUSE_C1_IS_IN_A_CHAOTIC_STATE.
	 */
	C1_CANNOT_DUEL_BECAUSE_C1_IS_IN_A_CHAOTIC_STATE(2023),
	/**
	 * Field C1_CANNOT_DUEL_BECAUSE_C1_IS_PARTICIPATING_IN_THE_OLYMPIAD.
	 */
	C1_CANNOT_DUEL_BECAUSE_C1_IS_PARTICIPATING_IN_THE_OLYMPIAD(2024),
	/**
	 * Field C1_CANNOT_DUEL_BECAUSE_C1_IS_PARTICIPATING_IN_A_CLAN_HALL_WAR.
	 */
	C1_CANNOT_DUEL_BECAUSE_C1_IS_PARTICIPATING_IN_A_CLAN_HALL_WAR(2025),
	/**
	 * Field C1_CANNOT_DUEL_BECAUSE_C1_IS_PARTICIPATING_IN_A_SIEGE_WAR.
	 */
	C1_CANNOT_DUEL_BECAUSE_C1_IS_PARTICIPATING_IN_A_SIEGE_WAR(2026),
	/**
	 * Field C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_RIDING_A_BOAT_STEED_OR_STRIDER.
	 */
	C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_RIDING_A_BOAT_STEED_OR_STRIDER(2027),
	/**
	 * Field C1_CANNOT_RECEIVE_A_DUEL_CHALLENGE_BECAUSE_C1_IS_TOO_FAR_AWAY.
	 */
	C1_CANNOT_RECEIVE_A_DUEL_CHALLENGE_BECAUSE_C1_IS_TOO_FAR_AWAY(2028),
	/**
	 * Field A_SUBCLASS_CANNOT_BE_CREATED_OR_CHANGED_BECAUSE_YOU_HAVE_EXCEEDED_YOUR_INVENTORY_LIMIT.
	 */
	A_SUBCLASS_CANNOT_BE_CREATED_OR_CHANGED_BECAUSE_YOU_HAVE_EXCEEDED_YOUR_INVENTORY_LIMIT(2033),
	/**
	 * Field S1_CLAN_IS_TRYING_TO_DISPLAY_A_FLAG.
	 */
	S1_CLAN_IS_TRYING_TO_DISPLAY_A_FLAG(2050),
	/**
	 * Field THAT_WEAPON_CANNOT_PERFORM_ANY_ATTACKS.
	 */
	THAT_WEAPON_CANNOT_PERFORM_ANY_ATTACKS(2066),
	/**
	 * Field THAT_WEAPON_CANNOT_USE_ANY_OTHER_SKILL_EXCEPT_THE_WEAPONS_SKILL.
	 */
	THAT_WEAPON_CANNOT_USE_ANY_OTHER_SKILL_EXCEPT_THE_WEAPONS_SKILL(2067),
	/**
	 * Field ENEMY_BLOOD_PLEDGES_HAVE_INTRUDED_INTO_THE_FORTRESS.
	 */
	ENEMY_BLOOD_PLEDGES_HAVE_INTRUDED_INTO_THE_FORTRESS(2084),
	/**
	 * Field SHOUT_AND_TRADE_CHATTING_CANNOT_BE_USED_WHILE_POSSESSING_A_CURSED_WEAPON.
	 */
	SHOUT_AND_TRADE_CHATTING_CANNOT_BE_USED_WHILE_POSSESSING_A_CURSED_WEAPON(2085),
	/**
	 * Field SEARCH_ON_USER_C2_FOR_THIRDPARTY_PROGRAM_USE_WILL_BE_COMPLETED_IN_S1_MINUTES.
	 */
	SEARCH_ON_USER_C2_FOR_THIRDPARTY_PROGRAM_USE_WILL_BE_COMPLETED_IN_S1_MINUTES(2086),
	/**
	 * Field A_FORTRESS_IS_UNDER_ATTACK.
	 */
	A_FORTRESS_IS_UNDER_ATTACK(2087),
	/**
	 * Field S1_MINUTES_UNTIL_THE_FORTRESS_BATTLE_STARTS.
	 */
	S1_MINUTES_UNTIL_THE_FORTRESS_BATTLE_STARTS(2088),
	/**
	 * Field S1_SECONDS_UNTIL_THE_FORTRESS_BATTLE_STARTS.
	 */
	S1_SECONDS_UNTIL_THE_FORTRESS_BATTLE_STARTS(2089),
	/**
	 * Field THE_FORTRESS_BATTLE_S1_HAS_BEGUN.
	 */
	THE_FORTRESS_BATTLE_S1_HAS_BEGUN(2090),
	/**
	 * Field C1_IS_IN_A_LOCATION_WHICH_CANNOT_BE_ENTERED_THEREFORE_IT_CANNOT_BE_PROCESSED.
	 */
	C1_IS_IN_A_LOCATION_WHICH_CANNOT_BE_ENTERED_THEREFORE_IT_CANNOT_BE_PROCESSED(2096),
	/**
	 * Field C1S_LEVEL_DOES_NOT_CORRESPOND_TO_THE_REQUIREMENTS_FOR_ENTRY.
	 */
	C1S_LEVEL_DOES_NOT_CORRESPOND_TO_THE_REQUIREMENTS_FOR_ENTRY(2097),
	/**
	 * Field C1S_QUEST_REQUIREMENT_IS_NOT_SUFFICIENT_AND_CANNOT_BE_ENTERED.
	 */
	C1S_QUEST_REQUIREMENT_IS_NOT_SUFFICIENT_AND_CANNOT_BE_ENTERED(2098),
	/**
	 * Field C1S_ITEM_REQUIREMENT_IS_NOT_SUFFICIENT_AND_CANNOT_BE_ENTERED.
	 */
	C1S_ITEM_REQUIREMENT_IS_NOT_SUFFICIENT_AND_CANNOT_BE_ENTERED(2099),
	/**
	 * Field C1_MAY_NOT_REENTER_YET.
	 */
	C1_MAY_NOT_REENTER_YET(2100),
	/**
	 * Field YOU_ARE_NOT_CURRENTLY_IN_A_PARTY_SO_YOU_CANNOT_ENTER.
	 */
	YOU_ARE_NOT_CURRENTLY_IN_A_PARTY_SO_YOU_CANNOT_ENTER(2101),
	/**
	 * Field YOU_CANNOT_ENTER_DUE_TO_THE_PARTY_HAVING_EXCEEDED_THE_LIMIT.
	 */
	YOU_CANNOT_ENTER_DUE_TO_THE_PARTY_HAVING_EXCEEDED_THE_LIMIT(2102),
	/**
	 * Field YOU_CANNOT_ENTER_BECAUSE_YOU_ARE_NOT_ASSOCIATED_WITH_THE_CURRENT_COMMAND_CHANNEL.
	 */
	YOU_CANNOT_ENTER_BECAUSE_YOU_ARE_NOT_ASSOCIATED_WITH_THE_CURRENT_COMMAND_CHANNEL(2103),
	/**
	 * Field THE_MAXIMUM_NUMBER_OF_INSTANCE_ZONES_HAS_BEEN_EXCEEDED.
	 */
	THE_MAXIMUM_NUMBER_OF_INSTANCE_ZONES_HAS_BEEN_EXCEEDED(2104),
	/**
	 * Field YOU_HAVE_ENTERED_ANOTHER_INSTANCE_ZONE_THEREFORE_YOU_CANNOT_ENTER_CORRESPONDING_DUNGEON.
	 */
	YOU_HAVE_ENTERED_ANOTHER_INSTANCE_ZONE_THEREFORE_YOU_CANNOT_ENTER_CORRESPONDING_DUNGEON(2105),
	/**
	 * Field THIS_DUNGEON_WILL_EXPIRE_IN_S1_MINUTES.
	 */
	THIS_DUNGEON_WILL_EXPIRE_IN_S1_MINUTES(2106),
	/**
	 * Field YOU_CANNOT_CONVERT_THIS_ITEM.
	 */
	YOU_CANNOT_CONVERT_THIS_ITEM(2130),
	/**
	 * Field CONGRATULATIONS__YOUVE_COMPLETED_A_CLASS_TRANSFER.
	 */
	CONGRATULATIONS__YOUVE_COMPLETED_A_CLASS_TRANSFER(1308),
	/**
	 * Field THE_TARGET_IS_NOT_A_FLAGPOLE_SO_A_FLAG_CANNOT_BE_DISPLAYED.
	 */
	THE_TARGET_IS_NOT_A_FLAGPOLE_SO_A_FLAG_CANNOT_BE_DISPLAYED(2154),
	/**
	 * Field A_FLAG_IS_ALREADY_BEING_DISPLAYED_ANOTHER_FLAG_CANNOT_BE_DISPLAYED.
	 */
	A_FLAG_IS_ALREADY_BEING_DISPLAYED_ANOTHER_FLAG_CANNOT_BE_DISPLAYED(2155),
	/**
	 * Field THERE_ARE_NOT_ENOUGH_NECESSARY_ITEMS_TO_USE_THE_SKILL.
	 */
	THERE_ARE_NOT_ENOUGH_NECESSARY_ITEMS_TO_USE_THE_SKILL(2156),
	/**
	 * Field FORCE_ATTACK_IS_IMPOSSIBLE_AGAINST_A_TEMPORARY_ALLIED_MEMBER_DURING_A_SIEGE.
	 */
	FORCE_ATTACK_IS_IMPOSSIBLE_AGAINST_A_TEMPORARY_ALLIED_MEMBER_DURING_A_SIEGE(2158),
	/**
	 * Field THE_BARRACKS_HAVE_BEEN_SEIZED.
	 */
	THE_BARRACKS_HAVE_BEEN_SEIZED(2164),
	/**
	 * Field THE_BARRACKS_FUNCTION_HAS_BEEN_RESTORED.
	 */
	THE_BARRACKS_FUNCTION_HAS_BEEN_RESTORED(2165),
	/**
	 * Field ALL_BARRACKS_ARE_OCCUPIED.
	 */
	ALL_BARRACKS_ARE_OCCUPIED(2166),
	/**
	 * Field C1_HAS_ACQUIRED_THE_FLAG.
	 */
	C1_HAS_ACQUIRED_THE_FLAG(2168),
	/**
	 * Field YOUR_CLAN_HAS_BEEN_REGISTERED_TO_S1S_FORTRESS_BATTLE.
	 */
	YOUR_CLAN_HAS_BEEN_REGISTERED_TO_S1S_FORTRESS_BATTLE(2169),
	/**
	 * Field C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_POLYMORPHED.
	 */
	C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_POLYMORPHED(2174),
	/**
	 * Field PARTY_DUEL_CANNOT_BE_INITIATED_DUE_TO_A_POLYMORPHED_PARTY_MEMBER.
	 */
	PARTY_DUEL_CANNOT_BE_INITIATED_DUE_TO_A_POLYMORPHED_PARTY_MEMBER(2175),
	/**
	 * Field THE_FORTRESS_BATTLE_OF_S1_HAS_FINISHED.
	 */
	THE_FORTRESS_BATTLE_OF_S1_HAS_FINISHED(2183),
	/**
	 * Field S1_IS_VICTORIOUS_IN_THE_FORTRESS_BATTLE_OF_S2.
	 */
	S1_IS_VICTORIOUS_IN_THE_FORTRESS_BATTLE_OF_S2(2184),
	/**
	 * Field ONLY_A_PARTY_LEADER_CAN_MAKE_THE_REQUEST_TO_ENTER.
	 */
	ONLY_A_PARTY_LEADER_CAN_MAKE_THE_REQUEST_TO_ENTER(2185),
	/**
	 * Field YOU_CANNOT_BOARD_A_SHIP_WHILE_YOU_ARE_POLYMORPHED.
	 */
	YOU_CANNOT_BOARD_A_SHIP_WHILE_YOU_ARE_POLYMORPHED(2213),
	/**
	 * Field THE_BALLISTA_HAS_BEEN_SUCCESSFULLY_DESTROYED.
	 */
	THE_BALLISTA_HAS_BEEN_SUCCESSFULLY_DESTROYED(2217),
	/**
	 * Field THIS_SQUAD_SKILL_HAS_ALREADY_BEEN_ACQUIRED.
	 */
	THIS_SQUAD_SKILL_HAS_ALREADY_BEEN_ACQUIRED(2219),
	/**
	 * Field THE_PREVIOUS_LEVEL_SKILL_HAS_NOT_BEEN_LEARNED.
	 */
	THE_PREVIOUS_LEVEL_SKILL_HAS_NOT_BEEN_LEARNED(2220),
	/**
	 * Field IT_IS_NOT_POSSIBLE_TO_REGISTER_FOR_THE_CASTLE_SIEGE_SIDE_OR_CASTLE_SIEGE_OF_A_HIGHER_CASTLE_IN_THE_CONTRACT.
	 */
	IT_IS_NOT_POSSIBLE_TO_REGISTER_FOR_THE_CASTLE_SIEGE_SIDE_OR_CASTLE_SIEGE_OF_A_HIGHER_CASTLE_IN_THE_CONTRACT(2227),
	/**
	 * Field INSTANCE_ZONE_TIME_LIMIT.
	 */
	INSTANCE_ZONE_TIME_LIMIT(2228),
	/**
	 * Field THERE_IS_NO_INSTANCE_ZONE_UNDER_A_TIME_LIMIT.
	 */
	THERE_IS_NO_INSTANCE_ZONE_UNDER_A_TIME_LIMIT(2229),
	/**
	 * Field S1_WILL_BE_AVAILABLE_FOR_REUSE_AFTER_S2_HOURS_S3_MINUTES.
	 */
	S1_WILL_BE_AVAILABLE_FOR_REUSE_AFTER_S2_HOURS_S3_MINUTES(2230),
	/**
	 * Field SIEGE_REGISTRATION_IS_NOT_POSSIBLE_DUE_TO_YOUR_CASTLE_CONTRACT.
	 */
	SIEGE_REGISTRATION_IS_NOT_POSSIBLE_DUE_TO_YOUR_CASTLE_CONTRACT(2233),
	/**
	 * Field YOU_ARE_PARTICIPATING_IN_THE_SIEGE_OF_S1_THIS_SIEGE_IS_SCHEDULED_FOR_2_HOURS.
	 */
	YOU_ARE_PARTICIPATING_IN_THE_SIEGE_OF_S1_THIS_SIEGE_IS_SCHEDULED_FOR_2_HOURS(2238),
	/**
	 * Field S1_MINUTES_REMAINING.
	 */
	S1_MINUTES_REMAINING(2244),
	/**
	 * Field S1_SECONDS_REMAINING.
	 */
	S1_SECONDS_REMAINING(2245),
	/**
	 * Field THE_CONTEST_WILL_BEGIN_IN_S1_MINUTES.
	 */
	THE_CONTEST_WILL_BEGIN_IN_S1_MINUTES(2246),
	/**
	 * Field YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_TRANSFORMED.
	 */
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_TRANSFORMED(2247),
	/**
	 * Field YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_PETRIFIED.
	 */
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_PETRIFIED(2248),
	/**
	 * Field YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_DEAD.
	 */
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_DEAD(2249),
	/**
	 * Field YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_FISHING.
	 */
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_FISHING(2250),
	/**
	 * Field YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_IN_BATTLE.
	 */
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_IN_BATTLE(2251),
	/**
	 * Field YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_IN_A_DUEL.
	 */
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_IN_A_DUEL(2252),
	/**
	 * Field YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_SITTING.
	 */
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_SITTING(2253),
	/**
	 * Field YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_CASTING.
	 */
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_CASTING(2254),
	/**
	 * Field YOU_CANNOT_BOARD_AN_AIRSHIP_WHEN_A_CURSED_WEAPON_IS_EQUIPPED.
	 */
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHEN_A_CURSED_WEAPON_IS_EQUIPPED(2255),
	/**
	 * Field YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_HOLDING_A_FLAG.
	 */
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_HOLDING_A_FLAG(2256),
	/**
	 * Field YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_A_PET_OR_A_SERVITOR_IS_SUMMONED.
	 */
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_A_PET_OR_A_SERVITOR_IS_SUMMONED(2257),
	/**
	 * Field YOU_HAVE_ALREADY_BOARDED_ANOTHER_AIRSHIP.
	 */
	YOU_HAVE_ALREADY_BOARDED_ANOTHER_AIRSHIP(2258),
	/**
	 * Field THIS_SKILL_CANNOT_BE_LEARNED_WHILE_IN_THE_SUBCLASS_STATE.
	 */
	THIS_SKILL_CANNOT_BE_LEARNED_WHILE_IN_THE_SUBCLASS_STATE(2273),
	/**
	 * Field YOU_CANNOT_WEAR_S1_BECAUSE_YOU_ARE_NOT_WEARING_A_BRACELET.
	 */
	YOU_CANNOT_WEAR_S1_BECAUSE_YOU_ARE_NOT_WEARING_A_BRACELET(2286),
	/**
	 * Field YOU_CANNOT_EQUIP_S1_BECAUSE_YOU_DO_NOT_HAVE_ANY_AVAILABLE_SLOTS.
	 */
	YOU_CANNOT_EQUIP_S1_BECAUSE_YOU_DO_NOT_HAVE_ANY_AVAILABLE_SLOTS(2287),
	/**
	 * Field AGATHION_SKILLS_CAN_BE_USED_ONLY_WHEN_YOUR_AGATHION_IS_SUMMONED.
	 */
	AGATHION_SKILLS_CAN_BE_USED_ONLY_WHEN_YOUR_AGATHION_IS_SUMMONED(2292),
	/**
	 * Field THERE_ARE_S2_SECONDS_REMAINING_IN_S1S_REUSE_TIME.
	 */
	THERE_ARE_S2_SECONDS_REMAINING_IN_S1S_REUSE_TIME(2303),
	/**
	 * Field THERE_ARE_S2_MINUTES_S3_SECONDS_REMAINING_IN_S1S_REUSE_TIME.
	 */
	THERE_ARE_S2_MINUTES_S3_SECONDS_REMAINING_IN_S1S_REUSE_TIME(2304),
	/**
	 * Field THERE_ARE_S2_HOURS_S3_MINUTES_AND_S4_SECONDS_REMAINING_IN_S1S_REUSE_TIME.
	 */
	THERE_ARE_S2_HOURS_S3_MINUTES_AND_S4_SECONDS_REMAINING_IN_S1S_REUSE_TIME(2305),
	/**
	 * Field YOUR_CHARM_OF_COURAGE_IS_TRYING_TO_RESURRECT_YOU.
	 */
	YOUR_CHARM_OF_COURAGE_IS_TRYING_TO_RESURRECT_YOU(2306),
	/**
	 * Field ONLY_CLANS_WHO_ARE_LEVEL_4_OR_ABOVE_CAN_REGISTER_FOR_BATTLE_AT_DEVASTATED_CASTLE_AND_FORTRESS_OF_THE_DEAD.
	 */
	ONLY_CLANS_WHO_ARE_LEVEL_4_OR_ABOVE_CAN_REGISTER_FOR_BATTLE_AT_DEVASTATED_CASTLE_AND_FORTRESS_OF_THE_DEAD(2328),
	/**
	 * Field S1_SECONDS_TO_GAME_END.
	 */
	S1_SECONDS_TO_GAME_END(2347),
	/**
	 * Field RESURRECTION_WILL_TAKE_PLACE_IN_THE_WAITING_ROOM_AFTER_S1_SECONDS.
	 */
	RESURRECTION_WILL_TAKE_PLACE_IN_THE_WAITING_ROOM_AFTER_S1_SECONDS(2370),
	/**
	 * Field END_MATCH.
	 */
	END_MATCH(2374),
	/**
	 * Field A_PARTY_CANNOT_BE_FORMED_IN_THIS_AREA.
	 */
	A_PARTY_CANNOT_BE_FORMED_IN_THIS_AREA(2388),
	/**
	 * Field YOU_HAVE_USED_THE_FEATHER_OF_BLESSING_TO_RESURRECT.
	 */
	YOU_HAVE_USED_THE_FEATHER_OF_BLESSING_TO_RESURRECT(2391),
	/**
	 * Field THAT_PET_SERVITOR_SKILL_CANNOT_BE_USED_BECAUSE_IT_IS_RECHARGING.
	 */
	THAT_PET_SERVITOR_SKILL_CANNOT_BE_USED_BECAUSE_IT_IS_RECHARGING(2396),
	/**
	 * Field INSTANT_ZONE_CURRENTLY_IN_USE_S1.
	 */
	INSTANT_ZONE_CURRENTLY_IN_USE_S1(2400),
	/**
	 * Field CLAN_LORD_C2_WHO_LEADS_CLAN_S1_HAS_BEEN_DECLARED_THE_LORD_OF_THE_S3_TERRITORY.
	 */
	CLAN_LORD_C2_WHO_LEADS_CLAN_S1_HAS_BEEN_DECLARED_THE_LORD_OF_THE_S3_TERRITORY(2401),
	/**
	 * Field THE_TERRITORY_WAR_REQUEST_PERIOD_HAS_ENDED.
	 */
	THE_TERRITORY_WAR_REQUEST_PERIOD_HAS_ENDED(2402),
	/**
	 * Field THE_TERRITORY_WAR_BEGINS_IN_10_MINUTES.
	 */
	THE_TERRITORY_WAR_BEGINS_IN_10_MINUTES(2403),
	/**
	 * Field THE_TERRITORY_WAR_BEGINS_IN_5_MINUTES.
	 */
	THE_TERRITORY_WAR_BEGINS_IN_5_MINUTES(2404),
	/**
	 * Field THE_TERRITORY_WAR_BEGINS_IN_1_MINUTE.
	 */
	THE_TERRITORY_WAR_BEGINS_IN_1_MINUTE(2405),
	/**
	 * Field YOU_ARE_CURRENTLY_REGISTERED_FOR_A_3_VS_3_CLASS_IRRELEVANT_TEAM_MATCH.
	 */
	YOU_ARE_CURRENTLY_REGISTERED_FOR_A_3_VS_3_CLASS_IRRELEVANT_TEAM_MATCH(2408),
	/**
	 * Field C1_IS_ALREADY_REGISTERED_ON_THE_WAITING_LIST_FOR_THE_3_VS_3_CLASS_IRRELEVANT_TEAM_MATCH.
	 */
	C1_IS_ALREADY_REGISTERED_ON_THE_WAITING_LIST_FOR_THE_3_VS_3_CLASS_IRRELEVANT_TEAM_MATCH(2440),
	/**
	 * Field ONLY_A_PARTY_LEADER_CAN_REQUEST_A_TEAM_MATCH.
	 */
	ONLY_A_PARTY_LEADER_CAN_REQUEST_A_TEAM_MATCH(2441),
	/**
	 * Field THE_REQUEST_CANNOT_BE_MADE_BECAUSE_THE_REQUIREMENTS_HAVE_NOT_BEEN_MET.
	 */
	THE_REQUEST_CANNOT_BE_MADE_BECAUSE_THE_REQUIREMENTS_HAVE_NOT_BEEN_MET(2442),
	/**
	 * Field THE_BATTLEFIELD_CHANNEL_HAS_BEEN_ACTIVATED.
	 */
	THE_BATTLEFIELD_CHANNEL_HAS_BEEN_ACTIVATED(2445),
	/**
	 * Field THE_BATTLEFIELD_CHANNEL_HAS_BEEN_DEACTIVATED.
	 */
	THE_BATTLEFIELD_CHANNEL_HAS_BEEN_DEACTIVATED(2446),
	/**
	 * Field FIVE_YEARS_HAVE_PASSED_SINCE_THIS_CHARACTERS_CREATION.
	 */
	FIVE_YEARS_HAVE_PASSED_SINCE_THIS_CHARACTERS_CREATION(2447),
	/**
	 * Field YOUR_BIRTHDAY_GIFT_HAS_ARRIVED.
	 */
	YOUR_BIRTHDAY_GIFT_HAS_ARRIVED(2448),
	/**
	 * Field THERE_ARE_S1_DAYS_UNTIL_YOUR_CHARACTERS_BIRTHDAY.
	 */
	THERE_ARE_S1_DAYS_UNTIL_YOUR_CHARACTERS_BIRTHDAY(2449),
	/**
	 * Field C1S_BIRTHDAY_IS_S3S4S2.
	 */
	C1S_BIRTHDAY_IS_S3S4S2(2450),
	/**
	 * Field IN_ORDER_TO_ACQUIRE_AN_AIRSHIP_THE_CLANS_LEVEL_MUST_BE_LEVEL_5_OR_HIGHER.
	 */
	IN_ORDER_TO_ACQUIRE_AN_AIRSHIP_THE_CLANS_LEVEL_MUST_BE_LEVEL_5_OR_HIGHER(2456),
	/**
	 * Field AN_AIRSHIP_CANNOT_BE_SUMMONED_BECAUSE_EITHER_YOU_HAVE_NOT_REGISTERED_YOUR_AIRSHIP_LICENSE_OR_THE_AIRSHIP_HAS_NOT_YET_BEEN_SUMMONED.
	 */
	AN_AIRSHIP_CANNOT_BE_SUMMONED_BECAUSE_EITHER_YOU_HAVE_NOT_REGISTERED_YOUR_AIRSHIP_LICENSE_OR_THE_AIRSHIP_HAS_NOT_YET_BEEN_SUMMONED(2457),
	/**
	 * Field YOUR_CLANS_AIRSHIP_IS_ALREADY_BEING_USED_BY_ANOTHER_CLAN_MEMBER.
	 */
	YOUR_CLANS_AIRSHIP_IS_ALREADY_BEING_USED_BY_ANOTHER_CLAN_MEMBER(2458),
	/**
	 * Field THE_AIRSHIP_SUMMON_LICENSE_HAS_ALREADY_BEEN_ACQUIRED.
	 */
	THE_AIRSHIP_SUMMON_LICENSE_HAS_ALREADY_BEEN_ACQUIRED(2459),
	/**
	 * Field THE_CLAN_OWNED_AIRSHIP_ALREADY_EXISTS.
	 */
	THE_CLAN_OWNED_AIRSHIP_ALREADY_EXISTS(2460),
	/**
	 * Field AN_AIRSHIP_CANNOT_BE_SUMMONED_BECAUSE_YOU_DONT_HAVE_ENOUGH_S1.
	 */
	AN_AIRSHIP_CANNOT_BE_SUMMONED_BECAUSE_YOU_DONT_HAVE_ENOUGH_S1(2462),
	/**
	 * Field THE_AIRSHIPS_FUEL_EP_WILL_SOON_RUN_OUT.
	 */
	THE_AIRSHIPS_FUEL_EP_WILL_SOON_RUN_OUT(2463),
	/**
	 * Field THE_AIRSHIPS_FUEL_EP_HAS_RUN_OUT.
	 */
	THE_AIRSHIPS_FUEL_EP_HAS_RUN_OUT(2464),
	/**
	 * Field YOUR_SHIP_CANNOT_TELEPORT_BECAUSE_IT_DOES_NOT_HAVE_ENOUGH_FUEL_FOR_THE_TRIP.
	 */
	YOUR_SHIP_CANNOT_TELEPORT_BECAUSE_IT_DOES_NOT_HAVE_ENOUGH_FUEL_FOR_THE_TRIP(2491),
	/**
	 * Field THE_S1_WARD_HAS_BEEN_DESTROYED_C2_NOW_HAS_THE_TERRITORY_WARD.
	 */
	THE_S1_WARD_HAS_BEEN_DESTROYED_C2_NOW_HAS_THE_TERRITORY_WARD(2750),
	/**
	 * Field THE_CHARACTER_THAT_ACQUIRED_S1S_WARD_HAS_BEEN_KILLED.
	 */
	THE_CHARACTER_THAT_ACQUIRED_S1S_WARD_HAS_BEEN_KILLED(2751),
	/**
	 * Field YOU_CANNOT_ENTER_BECAUSE_YOU_DO_NOT_MEET_THE_REQUIREMENTS.
	 */
	YOU_CANNOT_ENTER_BECAUSE_YOU_DO_NOT_MEET_THE_REQUIREMENTS(2706),
	/**
	 * Field YOU_CANNOT_REGISTER_WHILE_IN_POSSESSION_OF_A_CURSED_WEAPON.
	 */
	YOU_CANNOT_REGISTER_WHILE_IN_POSSESSION_OF_A_CURSED_WEAPON(2708),
	/**
	 * Field APPLICANTS_FOR_THE_OLYMPIAD_UNDERGROUND_COLISEUM_OR_KRATEIS_CUBE_MATCHES_CANNOT_REGISTER.
	 */
	APPLICANTS_FOR_THE_OLYMPIAD_UNDERGROUND_COLISEUM_OR_KRATEIS_CUBE_MATCHES_CANNOT_REGISTER(2709),
	/**
	 * Field YOU_CANNOT_BOARD_BECAUSE_YOU_DO_NOT_MEET_THE_REQUIREMENTS.
	 */
	YOU_CANNOT_BOARD_BECAUSE_YOU_DO_NOT_MEET_THE_REQUIREMENTS(2727),
	/**
	 * Field YOU_CANNOT_CONTROL_THE_HELM_WHILE_TRANSFORMED.
	 */
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_TRANSFORMED(2729),
	/**
	 * Field YOU_CANNOT_CONTROL_THE_HELM_WHILE_YOU_ARE_PETRIFIED.
	 */
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_YOU_ARE_PETRIFIED(2730),
	/**
	 * Field YOU_CANNOT_CONTROL_THE_HELM_WHEN_YOU_ARE_DEAD.
	 */
	YOU_CANNOT_CONTROL_THE_HELM_WHEN_YOU_ARE_DEAD(2731),
	/**
	 * Field YOU_CANNOT_CONTROL_THE_HELM_WHILE_FISHING.
	 */
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_FISHING(2732),
	/**
	 * Field YOU_CANNOT_CONTROL_THE_HELM_WHILE_IN_A_BATTLE.
	 */
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_IN_A_BATTLE(2733),
	/**
	 * Field YOU_CANNOT_CONTROL_THE_HELM_WHILE_IN_A_DUEL.
	 */
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_IN_A_DUEL(2734),
	/**
	 * Field YOU_CANNOT_CONTROL_THE_HELM_WHILE_IN_A_SITTING_POSITION.
	 */
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_IN_A_SITTING_POSITION(2735),
	/**
	 * Field YOU_CANNOT_CONTROL_THE_HELM_WHILE_USING_A_SKILL.
	 */
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_USING_A_SKILL(2736),
	/**
	 * Field YOU_CANNOT_CONTROL_THE_HELM_WHILE_A_CURSED_WEAPON_IS_EQUIPPED.
	 */
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_A_CURSED_WEAPON_IS_EQUIPPED(2737),
	/**
	 * Field YOU_CANNOT_CONTROL_THE_HELM_WHILE_HOLDING_A_FLAG.
	 */
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_HOLDING_A_FLAG(2738),
	/**
	 * Field YOU_CANNOT_CONTROL_THE_HELM_BECAUSE_YOU_DO_NOT_MEET_THE_REQUIREMENTS.
	 */
	YOU_CANNOT_CONTROL_THE_HELM_BECAUSE_YOU_DO_NOT_MEET_THE_REQUIREMENTS(2739),
	/**
	 * Field THIS_ACTION_IS_PROHIBITED_WHILE_STEERING.
	 */
	THIS_ACTION_IS_PROHIBITED_WHILE_STEERING(2740),
	/**
	 * Field THIS_TYPE_OF_ATTACK_IS_PROHIBITED_WHEN_ALLIED_TROOPS_ARE_THE_TARGET.
	 */
	THIS_TYPE_OF_ATTACK_IS_PROHIBITED_WHEN_ALLIED_TROOPS_ARE_THE_TARGET(2753),
	/**
	 * Field YOU_CANNOT_BE_SIMULTANEOUSLY_REGISTERED_FOR_PVP_MATCHES_SUCH_AS_THE_OLYMPIAD_UNDERGROUND_COLISEUM_AERIAL_CLEFT_KRATEIS_CUBE_AND_HANDYS_BLOCK_CHECKERS.
	 */
	YOU_CANNOT_BE_SIMULTANEOUSLY_REGISTERED_FOR_PVP_MATCHES_SUCH_AS_THE_OLYMPIAD_UNDERGROUND_COLISEUM_AERIAL_CLEFT_KRATEIS_CUBE_AND_HANDYS_BLOCK_CHECKERS(2754),
	/**
	 * Field ANOTHER_PLAYER_IS_PROBABLY_CONTROLLING_THE_TARGET.
	 */
	ANOTHER_PLAYER_IS_PROBABLY_CONTROLLING_THE_TARGET(2756),
	/**
	 * Field YOU_MUST_TARGET_THE_ONE_YOU_WISH_TO_CONTROL.
	 */
	YOU_MUST_TARGET_THE_ONE_YOU_WISH_TO_CONTROL(2761),
	/**
	 * Field YOU_CANNOT_CONTROL_BECAUSE_YOU_ARE_TOO_FAR.
	 */
	YOU_CANNOT_CONTROL_BECAUSE_YOU_ARE_TOO_FAR(2762),
	/**
	 * Field THE_EFFECT_OF_TERRITORY_WARD_IS_DISAPPEARING.
	 */
	THE_EFFECT_OF_TERRITORY_WARD_IS_DISAPPEARING(2776),
	/**
	 * Field THE_AIRSHIP_SUMMON_LICENSE_HAS_BEEN_ENTERED.
	 */
	THE_AIRSHIP_SUMMON_LICENSE_HAS_BEEN_ENTERED(2777),
	/**
	 * Field YOU_CANNOT_TELEPORT_WHILE_IN_POSSESSION_OF_A_WARD.
	 */
	YOU_CANNOT_TELEPORT_WHILE_IN_POSSESSION_OF_A_WARD(2778),
	/**
	 * Field MERCENARY_PARTICIPATION_IS_REQUESTED_IN_S1_TERRITORY.
	 */
	MERCENARY_PARTICIPATION_IS_REQUESTED_IN_S1_TERRITORY(2788),
	/**
	 * Field MERCENARY_PARTICIPATION_REQUEST_IS_CANCELLED_IN_S1_TERRITORY.
	 */
	MERCENARY_PARTICIPATION_REQUEST_IS_CANCELLED_IN_S1_TERRITORY(2789),
	/**
	 * Field CLAN_PARTICIPATION_IS_REQUESTED_IN_S1_TERRITORY.
	 */
	CLAN_PARTICIPATION_IS_REQUESTED_IN_S1_TERRITORY(2790),
	/**
	 * Field CLAN_PARTICIPATION_REQUEST_IS_CANCELLED_IN_S1_TERRITORY.
	 */
	CLAN_PARTICIPATION_REQUEST_IS_CANCELLED_IN_S1_TERRITORY(2791),
	/**
	 * Field YOU_MUST_HAVE_A_MINIMUM_OF_S1_PEOPLE_TO_ENTER_THIS_INSTANT_ZONE.
	 */
	YOU_MUST_HAVE_A_MINIMUM_OF_S1_PEOPLE_TO_ENTER_THIS_INSTANT_ZONE(2793),
	/**
	 * Field THE_TERRITORY_WAR_CHANNEL_AND_FUNCTIONS_WILL_NOW_BE_DEACTIVATED.
	 */
	THE_TERRITORY_WAR_CHANNEL_AND_FUNCTIONS_WILL_NOW_BE_DEACTIVATED(2794),
	/**
	 * Field YOUVE_ALREADY_REQUESTED_A_TERRITORY_WAR_IN_ANOTHER_TERRITORY_ELSEWHERE.
	 */
	YOUVE_ALREADY_REQUESTED_A_TERRITORY_WAR_IN_ANOTHER_TERRITORY_ELSEWHERE(2795),
	/**
	 * Field THE_CLAN_WHO_OWNS_THE_TERRITORY_CANNOT_PARTICIPATE_IN_THE_TERRITORY_WAR_AS_MERCENARIES.
	 */
	THE_CLAN_WHO_OWNS_THE_TERRITORY_CANNOT_PARTICIPATE_IN_THE_TERRITORY_WAR_AS_MERCENARIES(2796),
	/**
	 * Field IT_IS_NOT_A_TERRITORY_WAR_REGISTRATION_PERIOD_SO_A_REQUEST_CANNOT_BE_MADE_AT_THIS_TIME.
	 */
	IT_IS_NOT_A_TERRITORY_WAR_REGISTRATION_PERIOD_SO_A_REQUEST_CANNOT_BE_MADE_AT_THIS_TIME(2797),
	/**
	 * Field THE_TERRITORY_WAR_WILL_END_IN_S1HOURS.
	 */
	THE_TERRITORY_WAR_WILL_END_IN_S1HOURS(2798),
	/**
	 * Field THE_TERRITORY_WAR_WILL_END_IN_S1MINUTES.
	 */
	THE_TERRITORY_WAR_WILL_END_IN_S1MINUTES(2799),
	/**
	 * Field S1_SECONDS_TO_THE_END_OF_TERRITORY_WAR.
	 */
	S1_SECONDS_TO_THE_END_OF_TERRITORY_WAR(2900),
	/**
	 * Field YOU_CANNOT_FORCE_ATTACK_A_MEMBER_OF_THE_SAME_TERRITORY.
	 */
	YOU_CANNOT_FORCE_ATTACK_A_MEMBER_OF_THE_SAME_TERRITORY(2901),
	/**
	 * Field YOUVE_ACQUIRED_THE_WARD.
	 */
	YOUVE_ACQUIRED_THE_WARD(2902),
	/**
	 * Field TERRITORY_WAR_HAS_BEGUN.
	 */
	TERRITORY_WAR_HAS_BEGUN(2903),
	/**
	 * Field TERRITORY_WAR_HAS_ENDED.
	 */
	TERRITORY_WAR_HAS_ENDED(2904),
	/**
	 * Field YOUVE_REQUESTED_C1_TO_BE_ON_YOUR_FRIENDS_LIST.
	 */
	YOUVE_REQUESTED_C1_TO_BE_ON_YOUR_FRIENDS_LIST(2911),
	/**
	 * Field CLAN_S1_HAS_SUCCEEDED_IN_CAPTURING_S2S_TERRITORY_WARD.
	 */
	CLAN_S1_HAS_SUCCEEDED_IN_CAPTURING_S2S_TERRITORY_WARD(2913),
	/**
	 * Field THE_TERRITORY_WAR_WILL_BEGIN_IN_20_MINUTES.
	 */
	THE_TERRITORY_WAR_WILL_BEGIN_IN_20_MINUTES(2914),
	/**
	 * Field THIS_CLAN_MEMBER_CANNOT_WITHDRAW_OR_BE_EXPELLED_WHILE_PARTICIPATING_IN_A_TERRITORY_WAR.
	 */
	THIS_CLAN_MEMBER_CANNOT_WITHDRAW_OR_BE_EXPELLED_WHILE_PARTICIPATING_IN_A_TERRITORY_WAR(2915),
	/**
	 * Field ONLY_CHARACTERS_WHO_ARE_LEVEL_40_OR_ABOVE_WHO_HAVE_COMPLETED_THEIR_SECOND_CLASS_TRANSFER_CAN_REGISTER_IN_A_TERRITORY_WAR.
	 */
	ONLY_CHARACTERS_WHO_ARE_LEVEL_40_OR_ABOVE_WHO_HAVE_COMPLETED_THEIR_SECOND_CLASS_TRANSFER_CAN_REGISTER_IN_A_TERRITORY_WAR(2918),
	/**
	 * Field THE_DISGUISE_SCROLL_CANNOT_BE_USED_BECAUSE_IT_IS_MEANT_FOR_USE_IN_A_DIFFERENT_TERRITORY.
	 */
	THE_DISGUISE_SCROLL_CANNOT_BE_USED_BECAUSE_IT_IS_MEANT_FOR_USE_IN_A_DIFFERENT_TERRITORY(2936),
	/**
	 * Field A_TERRITORY_OWNING_CLAN_MEMBER_CANNOT_USE_A_DISGUISE_SCROLL.
	 */
	A_TERRITORY_OWNING_CLAN_MEMBER_CANNOT_USE_A_DISGUISE_SCROLL(2937),
	/**
	 * Field THE_DISGUISE_SCROLL_CANNOT_BE_USED_WHILE_YOU_ARE_ENGAGED_IN_A_PRIVATE_STORE_OR_MANUFACTURE_WORKSHOP.
	 */
	THE_DISGUISE_SCROLL_CANNOT_BE_USED_WHILE_YOU_ARE_ENGAGED_IN_A_PRIVATE_STORE_OR_MANUFACTURE_WORKSHOP(2938),
	/**
	 * Field A_DISGUISE_CANNOT_BE_USED_WHEN_YOU_ARE_IN_A_CHAOTIC_STATE.
	 */
	A_DISGUISE_CANNOT_BE_USED_WHEN_YOU_ARE_IN_A_CHAOTIC_STATE(2939),
	/**
	 * Field THE_TERRITORY_WAR_EXCLUSIVE_DISGUISE_AND_TRANSFORMATION_CAN_BE_USED_20_MINUTES_BEFORE_THE_START_OF_THE_TERRITORY_WAR_TO_10_MINUTES_AFTER_ITS_END.
	 */
	THE_TERRITORY_WAR_EXCLUSIVE_DISGUISE_AND_TRANSFORMATION_CAN_BE_USED_20_MINUTES_BEFORE_THE_START_OF_THE_TERRITORY_WAR_TO_10_MINUTES_AFTER_ITS_END(2955),
	/**
	 * Field A_CHARACTER_BORN_ON_FEBRUARY_29_WILL_RECEIVE_A_GIFT_ON_FEBRUARY_28.
	 */
	A_CHARACTER_BORN_ON_FEBRUARY_29_WILL_RECEIVE_A_GIFT_ON_FEBRUARY_28(2957),
	/**
	 * Field AN_AGATHION_HAS_ALREADY_BEEN_SUMMONED.
	 */
	AN_AGATHION_HAS_ALREADY_BEEN_SUMMONED(2958),
	/**
	 * Field THE_COMMAND_CHANNEL_MATCHING_ROOM_WAS_CANCELLED.
	 */
	THE_COMMAND_CHANNEL_MATCHING_ROOM_WAS_CANCELLED(2994),
	/**
	 * Field YOU_CANNOT_ENTER_THE_COMMAND_CHANNEL_MATCHING_ROOM_BECAUSE_YOU_DO_NOT_MEET_THE_REQUIREMENTS.
	 */
	YOU_CANNOT_ENTER_THE_COMMAND_CHANNEL_MATCHING_ROOM_BECAUSE_YOU_DO_NOT_MEET_THE_REQUIREMENTS(2996),
	/**
	 * Field YOU_EXITED_FROM_THE_COMMAND_CHANNEL_MATCHING_ROOM.
	 */
	YOU_EXITED_FROM_THE_COMMAND_CHANNEL_MATCHING_ROOM(2997),
	/**
	 * Field YOU_WERE_EXPELLED_FROM_THE_COMMAND_CHANNEL_MATCHING_ROOM.
	 */
	YOU_WERE_EXPELLED_FROM_THE_COMMAND_CHANNEL_MATCHING_ROOM(2998),
	/**
	 * Field THE_COMMAND_CHANNEL_AFFILIATED_PARTYS_PARTY_MEMBER_CANNOT_USE_THE_MATCHING_SCREEN.
	 */
	THE_COMMAND_CHANNEL_AFFILIATED_PARTYS_PARTY_MEMBER_CANNOT_USE_THE_MATCHING_SCREEN(2999),
	/**
	 * Field THE_COMMAND_CHANNEL_MATCHING_ROOM_WAS_CREATED.
	 */
	THE_COMMAND_CHANNEL_MATCHING_ROOM_WAS_CREATED(3000),
	/**
	 * Field THE_COMMAND_CHANNEL_MATCHING_ROOM_INFORMATION_WAS_EDITED.
	 */
	THE_COMMAND_CHANNEL_MATCHING_ROOM_INFORMATION_WAS_EDITED(3001),
	/**
	 * Field C1_ENTERED_THE_COMMAND_CHANNEL_MATCHING_ROOM.
	 */
	C1_ENTERED_THE_COMMAND_CHANNEL_MATCHING_ROOM(3003),
	/**
	 * Field A_USER_CURRENTLY_PARTICIPATING_IN_THE_OLYMPIAD_CANNOT_SEND_PARTY_AND_FRIEND_INVITATIONS.
	 */
	A_USER_CURRENTLY_PARTICIPATING_IN_THE_OLYMPIAD_CANNOT_SEND_PARTY_AND_FRIEND_INVITATIONS(3094),
	/**
	 * Field THE_COUPLE_ACTION_WAS_DENIED.
	 */
	THE_COUPLE_ACTION_WAS_DENIED(3119),
	/**
	 * Field THE_REQUEST_CANNOT_BE_COMPLETED_BECAUSE_THE_TARGET_DOES_NOT_MEET_LOCATION_REQUIREMENTS.
	 */
	THE_REQUEST_CANNOT_BE_COMPLETED_BECAUSE_THE_TARGET_DOES_NOT_MEET_LOCATION_REQUIREMENTS(3120),
	/**
	 * Field THE_COUPLE_ACTION_WAS_CANCELLED.
	 */
	THE_COUPLE_ACTION_WAS_CANCELLED(3121),
	/**
	 * Field C1_IS_ALREADY_PARTICIPATING_IN_A_COUPLE_ACTION_AND_CANNOT_BE_REQUESTED_FOR_ANOTHER_COUPLE_ACTION.
	 */
	C1_IS_ALREADY_PARTICIPATING_IN_A_COUPLE_ACTION_AND_CANNOT_BE_REQUESTED_FOR_ANOTHER_COUPLE_ACTION(3126),
	/**
	 * Field YOU_HAVE_REQUESTED_A_COUPLE_ACTION_WITH_C1.
	 */
	YOU_HAVE_REQUESTED_A_COUPLE_ACTION_WITH_C1(3150),
	/**
	 * Field C1_IS_SET_TO_REFUSE_DUEL_REQUESTS_AND_CANNOT_RECEIVE_A_DUEL_REQUEST.
	 */
	C1_IS_SET_TO_REFUSE_DUEL_REQUESTS_AND_CANNOT_RECEIVE_A_DUEL_REQUEST(3169),
	/**
	 * Field S1_WAS_SUCCESSFULLY_ADDED_TO_YOUR_CONTACT_LIST.
	 */
	S1_WAS_SUCCESSFULLY_ADDED_TO_YOUR_CONTACT_LIST(3214),
	/**
	 * Field THE_NAME_S1__DOESNT_EXIST.
	 */
	THE_NAME_S1__DOESNT_EXIST(3215),
	/**
	 * Field THE_NAME_ALREADY_EXISTS_ON_THE_ADDED_LIST.
	 */
	THE_NAME_ALREADY_EXISTS_ON_THE_ADDED_LIST(3216),
	/**
	 * Field THE_NAME_IS_NOT_CURRENTLY_REGISTERED.
	 */
	THE_NAME_IS_NOT_CURRENTLY_REGISTERED(3217),
	/**
	 * Field S1_WAS_SUCCESSFULLY_DELETED_FROM_YOUR_CONTACT_LIST.
	 */
	S1_WAS_SUCCESSFULLY_DELETED_FROM_YOUR_CONTACT_LIST(3219),
	/**
	 * Field YOU_CANNOT_ADD_YOUR_OWN_NAME.
	 */
	YOU_CANNOT_ADD_YOUR_OWN_NAME(3221),
	/**
	 * Field THE_MAXIMUM_NUMBER_OF_NAMES_100_HAS_BEEN_REACHED.
	 */
	THE_MAXIMUM_NUMBER_OF_NAMES_100_HAS_BEEN_REACHED(3222),
	/**
	 * Field THE_MAXIMUM_MATCHES_YOU_CAN_PARTICIPATE_IN_1_WEEK_IS_70.
	 */
	THE_MAXIMUM_MATCHES_YOU_CAN_PARTICIPATE_IN_1_WEEK_IS_70(3224),
	/**
	 * Field THE_TOTAL_NUMBER_OF_MATCHES_THAT_CAN_BE_ENTERED_IN_1_WEEK_IS_60_CLASS_IRRELEVANT_INDIVIDUAL_MATCHES_30_SPECIFIC_MATCHES_AND_10_TEAM_MATCHES.
	 */
	THE_TOTAL_NUMBER_OF_MATCHES_THAT_CAN_BE_ENTERED_IN_1_WEEK_IS_60_CLASS_IRRELEVANT_INDIVIDUAL_MATCHES_30_SPECIFIC_MATCHES_AND_10_TEAM_MATCHES(3225),
	/**
	 * Field MP_BECAME_0_AND_THE_ARCANE_SHIELD_IS_DISAPPEARING.
	 */
	MP_BECAME_0_AND_THE_ARCANE_SHIELD_IS_DISAPPEARING(3256),
	/**
	 * Field YOU_HAVE_ACQUIRED_S1_EXP_BONUS_S2_AND_S3_SP_BONUS_S4.
	 */
	YOU_HAVE_ACQUIRED_S1_EXP_BONUS_S2_AND_S3_SP_BONUS_S4(3259),
	/**
	 * Field YOU_HAVE_S1_MATCHES_REMAINING_THAT_YOU_CAN_PARTICIPATE_IN_THIS_WEEK_S2_1_VS_1_CLASS_MATCHES_S3_1_VS_1_MATCHES__S4_3_VS_3_TEAM_MATCHES.
	 */
	YOU_HAVE_S1_MATCHES_REMAINING_THAT_YOU_CAN_PARTICIPATE_IN_THIS_WEEK_S2_1_VS_1_CLASS_MATCHES_S3_1_VS_1_MATCHES__S4_3_VS_3_TEAM_MATCHES(3261),
	/**
	 * Field THERE_ARE_S2_SECONDS_REMAINING_FOR_S1S_REUSE_TIME.
	 */
	THERE_ARE_S2_SECONDS_REMAINING_FOR_S1S_REUSE_TIME(3263),
	/**
	 * Field THERE_ARE_S2_MINUTES_S3_SECONDS_REMAINING_FOR_S1S_REUSE_TIME.
	 */
	THERE_ARE_S2_MINUTES_S3_SECONDS_REMAINING_FOR_S1S_REUSE_TIME(3264),
	/**
	 * Field THERE_ARE_S2_HOURS_S3_MINUTES_S4_SECONDS_REMAINING_FOR_S1S_REUSE_TIME.
	 */
	THERE_ARE_S2_HOURS_S3_MINUTES_S4_SECONDS_REMAINING_FOR_S1S_REUSE_TIME(3265),
	/**
	 * Field C1_IS_SET_TO_REFUSE_COUPLE_ACTIONS_AND_CANNOT_BE_REQUESTED_FOR_A_COUPLE_ACTION.
	 */
	C1_IS_SET_TO_REFUSE_COUPLE_ACTIONS_AND_CANNOT_BE_REQUESTED_FOR_A_COUPLE_ACTION(3164),
	/**
	 * Field THE_ANGEL_NEVIT_HAS_BLESSED_YOU_FROM_ABOVE_YOU_ARE_IMBUED_WITH_FULL_VITALITY_AS_WELL_AS_A_VITALITY_REPLENISHING_EFFECT.
	 */
	THE_ANGEL_NEVIT_HAS_BLESSED_YOU_FROM_ABOVE_YOU_ARE_IMBUED_WITH_FULL_VITALITY_AS_WELL_AS_A_VITALITY_REPLENISHING_EFFECT(3266),
	/**
	 * Field YOU_ARE_STARTING_TO_FEEL_THE_EFFECTS_OF_NEVITS_BLESSING.
	 */
	YOU_ARE_STARTING_TO_FEEL_THE_EFFECTS_OF_NEVITS_BLESSING(3267),
	/**
	 * Field YOU_ARE_FURTHER_INFUSED_WITH_THE_BLESSINGS_OF_NEVIT_CONTINUE_TO_BATTLE_EVIL_WHEREVER_IT_MAY_LURK.
	 */
	YOU_ARE_FURTHER_INFUSED_WITH_THE_BLESSINGS_OF_NEVIT_CONTINUE_TO_BATTLE_EVIL_WHEREVER_IT_MAY_LURK(3268),
	/**
	 * Field NEVITS_BLESSING_SHINES_STRONGLY_FROM_ABOVE_YOU_CAN_ALMOST_SEE_HIS_DIVINE_AURA.
	 */
	NEVITS_BLESSING_SHINES_STRONGLY_FROM_ABOVE_YOU_CAN_ALMOST_SEE_HIS_DIVINE_AURA(3269),
	/**
	 * Field NEVITS_BLESSING_HAS_ENDED_CONTINUE_YOUR_JOURNEY_AND_YOU_WILL_SURELY_MEET_HIS_FAVOR_AGAIN_SOMETIME_SOON.
	 */
	NEVITS_BLESSING_HAS_ENDED_CONTINUE_YOUR_JOURNEY_AND_YOU_WILL_SURELY_MEET_HIS_FAVOR_AGAIN_SOMETIME_SOON(3275),
	/**
	 * Field YOU_DO_NOT_HAVE_ENOUGH_ADENA_TO_REGISTER_THE_ITEM.
	 */
	YOU_DO_NOT_HAVE_ENOUGH_ADENA_TO_REGISTER_THE_ITEM(3364),
	/**
	 * Field YOU_CANNOT_CHANGE_CLASS_BECAUSE_OF_IDENTIFY_CRISIS.
	 */
	YOU_CANNOT_CHANGE_CLASS_BECAUSE_OF_IDENTIFY_CRISIS(3574),
	/**
	 * Field THE_MENTORING_RELATIONSHIP_WITH_S1_HAS_BEEN_CANCELED.
	 */
	THE_MENTORING_RELATIONSHIP_WITH_S1_HAS_BEEN_CANCELED(3689),
	/**
	 * Field DO_TOU_WISH_TO_MAKE_S1_YOUR_MENTOR_CLASS_S2_LEVEL_S3.
	 */
	DO_TOU_WISH_TO_MAKE_S1_YOUR_MENTOR_CLASS_S2_LEVEL_S3(3690),
	/**
	 * Field FROM_NOW_ON_S1_WILL_BE_YOUR_MENTOR.
	 */
	FROM_NOW_ON_S1_WILL_BE_YOUR_MENTOR(3691),
	/**
	 * Field FROM_NOW_ON_S1_WILL_BE_YOUR_MENTEE.
	 */
	FROM_NOW_ON_S1_WILL_BE_YOUR_MENTEE(3692),
	/**
	 * Field A_MENTOR_CAN_HAVE_UP_TO_3_MENTEES_AT_THE_SAME_TIME.
	 */
	A_MENTOR_CAN_HAVE_UP_TO_3_MENTEES_AT_THE_SAME_TIME(3693),
	/**
	 * Field YOU_MUST_AWAKEN_IN_ORDER_TO_BECOME_A_MENTOR.
	 */
	YOU_MUST_AWAKEN_IN_ORDER_TO_BECOME_A_MENTOR(3694),
	/**
	 * Field YOU_MENTEE_S1_HAS_CONNECTED.
	 */
	YOU_MENTEE_S1_HAS_CONNECTED(3695),
	/**
	 * Field YOU_MENTOR_S1_HAS_CONNECTED.
	 */
	YOU_MENTOR_S1_HAS_CONNECTED(3696),
	/**
	 * Field YOU_MENTEE_S1_HAS_DISCONNECTED.
	 */
	YOU_MENTEE_S1_HAS_DISCONNECTED(3697),
	/**
	 * Field YOU_MENTOR_S1_HAS_DISCONNECTED.
	 */
	YOU_MENTOR_S1_HAS_DISCONNECTED(3698),
	/**
	 * Field S1_HAS_DECLINED_BECOMING_YOUR_MENTEE.
	 */
	S1_HAS_DECLINED_BECOMING_YOUR_MENTEE(3699),
	/**
	 * Field YOU_CANNOT_BECOME_YOUR_OWN_MENTEE.
	 */
	YOU_CANNOT_BECOME_YOUR_OWN_MENTEE(3701),
	/**
	 * Field S1_ALREADY_HAS_A_MENTOR.
	 */
	S1_ALREADY_HAS_A_MENTOR(3702),
	/**
	 * Field S1_IS_ABOVE_LEVEL_86_AND_CANNOT_BECOME_A_MENTEE.
	 */
	S1_IS_ABOVE_LEVEL_86_AND_CANNOT_BECOME_A_MENTEE(3703),
	/**
	 * Field S1_DOES_NOT_HAVE_THE_ITEM_NEDEED_TO_BECOME_A_MENTEE.
	 */
	S1_DOES_NOT_HAVE_THE_ITEM_NEDEED_TO_BECOME_A_MENTEE(3704),
	/**
	 * Field THE_MENTEE_S1_HAS_REACHED_LEVEL_86.
	 */
	THE_MENTEE_S1_HAS_REACHED_LEVEL_86(3705),
	/**
	 * Field YOU_REACHED_LEVEL_86_RELATIONSHIP_WITH_S1_CAME_TO_AN_END.
	 */
	YOU_REACHED_LEVEL_86_RELATIONSHIP_WITH_S1_CAME_TO_AN_END(3706),
	/**
	 * Field YOU_HAVE_OFFERED_TO_BECOME_S1_MENTOR.
	 */
	YOU_HAVE_OFFERED_TO_BECOME_S1_MENTOR(3707),
	/**
	 * Field YOU_CAN_BOND_WITH_A_NEW_MENTEE_IN_S1_DAYS_S2_HOUR_S3_MINUTE.
	 */
	YOU_CAN_BOND_WITH_A_NEW_MENTEE_IN_S1_DAYS_S2_HOUR_S3_MINUTE(3713),
	/**
	 * Field THE_SKILL_HAS_BEEN_CANCELED_BECAUSE_YOU_HAVE_INSUFFICIENT_ENERGY.
	 */
	THE_SKILL_HAS_BEEN_CANCELED_BECAUSE_YOU_HAVE_INSUFFICIENT_ENERGY(6042),
	/**
	 * Field YOUR_ENERGY_CANNOT_BE_REPLENISHED_BECAUSE_CONDITIONS_ARE_NOT_MET.
	 */
	YOUR_ENERGY_CANNOT_BE_REPLENISHED_BECAUSE_CONDITIONS_ARE_NOT_MET(6043),
	/**
	 * Field ENERGY_S1_REPLENISHED.
	 */
	ENERGY_S1_REPLENISHED(6044),
	/**
	 * Field YOU_CANNOT_BOOKMARK_THIS_LOCATION_BECAUSE_YOU_DO_NOT_HAVE_A_MY_TELEPORT_FLAG.
	 */
	YOU_CANNOT_BOOKMARK_THIS_LOCATION_BECAUSE_YOU_DO_NOT_HAVE_A_MY_TELEPORT_FLAG(6501),
	/**
	 * Field YOUR_CLOAK_HAS_BEEN_UNEQUIPPED_BECAUSE_YOUR_ARMOR_SET_IS_NO_LONGER_COMPLETE.
	 */
	YOUR_CLOAK_HAS_BEEN_UNEQUIPPED_BECAUSE_YOUR_ARMOR_SET_IS_NO_LONGER_COMPLETE(2451),
	/**
	 * Field ITEM_PURCHASE_HAS_FAILED.
	 */
	ITEM_PURCHASE_HAS_FAILED(3371),
	/**
	 * Field THIS_TERRITORY_CAN_NOT_CHANGE_CLASS.
	 */
	THIS_TERRITORY_CAN_NOT_CHANGE_CLASS(3684),
	/**
	 * Field YOU_CAN_NOT_CHANGE_CLASS_IN_TRANSFORMATION.
	 */
	YOU_CAN_NOT_CHANGE_CLASS_IN_TRANSFORMATION(3677),
	/**
	 * Field VITALITY_IS_APPLIED_300.
	 */
	VITALITY_IS_APPLIED_300(3525),
	/**
	 * Field YOU_CAN_NOT_CHANGE_THE_ATTRIBUTE_WHILE_OPERATING_A_PRIVATE_STORE_OR_PRIVATE_WORKSHOP.
	 */
	YOU_CAN_NOT_CHANGE_THE_ATTRIBUTE_WHILE_OPERATING_A_PRIVATE_STORE_OR_PRIVATE_WORKSHOP(3659),
	/**
	 * Field THE_ITEM_FOR_CHANGING_AN_ATTRIBUTE_DOES_NOT_EXIST.
	 */
	THE_ITEM_FOR_CHANGING_AN_ATTRIBUTE_DOES_NOT_EXIST(3669),
	/**
	 * Field THE_COMMUNITY_SERVER_IS_CURRENTLY_OFFLINE.
	 */
	THE_COMMUNITY_SERVER_IS_CURRENTLY_OFFLINE(938),
	/**
	 * Field CANCELLATION_OF_SALE_FOR_THE_ITEM_IS_SUCCESSFUL.
	 */
	CANCELLATION_OF_SALE_FOR_THE_ITEM_IS_SUCCESSFUL(3485),
	/**
	 * Field STOPPED_SEARCHING_THE_PARTY.
	 */
	STOPPED_SEARCHING_THE_PARTY(3453),
	/**
	 * Field YOU_ARE_REGISTERED_ON_THE_WAITING_LIST.
	 */
	YOU_ARE_REGISTERED_ON_THE_WAITING_LIST(3452),
	/**
	 * Field THE_PLAYER_TO_BE_REPLACED_DOES_NOT_EXIST.
	 */
	THE_PLAYER_TO_BE_REPLACED_DOES_NOT_EXIST(3454),
	/**
	 * Field YOUR_NUMBER_OF_MY_TELEPORTS_SLOTS_HAS_REACHED_ITS_MAXIMUM_LIMIT.
	 */
	YOUR_NUMBER_OF_MY_TELEPORTS_SLOTS_HAS_REACHED_ITS_MAXIMUM_LIMIT(2390),
	/**
	 * Field THE_NUMBER_OF_MY_TELEPORTS_SLOTS_HAS_BEEN_INCREASED.
	 */
	THE_NUMBER_OF_MY_TELEPORTS_SLOTS_HAS_BEEN_INCREASED(2409),
	/**
	 * Field LOOKING_FOR_A_PLAYER_WHO_WILL_REPLACE_S1.
	 */
	LOOKING_FOR_A_PLAYER_WHO_WILL_REPLACE_S1(3445);
	/**
	 * Field _message.
	 */
	private final L2GameServerPacket _message;
	/**
	 * Field _id.
	 */
	private final int _id;
	/**
	 * Field _size.
	 */
	private final byte _size;
	
	/**
	 * Constructor for SystemMsg.
	 * @param i int
	 */
	SystemMsg(int i)
	{
		_id = i;
		if (name().contains("S4") || name().contains("C4"))
		{
			_size = 4;
			_message = null;
		}
		else if (name().contains("S3") || name().contains("C3"))
		{
			_size = 3;
			_message = null;
		}
		else if (name().contains("S2") || name().contains("C2"))
		{
			_size = 2;
			_message = null;
		}
		else if (name().contains("S1") || name().contains("C1"))
		{
			_size = 1;
			_message = null;
		}
		else
		{
			_size = 0;
			_message = new SystemMessage2(this);
		}
	}
	
	/**
	 * Method getId.
	 * @return int
	 */
	public int getId()
	{
		return _id;
	}
	
	/**
	 * Method size.
	 * @return byte
	 */
	public byte size()
	{
		return _size;
	}
	
	/**
	 * Method valueOf.
	 * @param id int
	 * @return SystemMsg
	 */
	public static SystemMsg valueOf(int id)
	{
		for (SystemMsg m : values())
		{
			if (m.getId() == id)
			{
				return m;
			}
		}
		throw new NoSuchElementException("Not find SystemMsg by id: " + id);
	}
	
	/**
	 * Method packet.
	 * @param player Player
	 * @return L2GameServerPacket * @see lineage2.gameserver.network.serverpackets.components.IStaticPacket#packet(Player)
	 */
	@Override
	public L2GameServerPacket packet(Player player)
	{
		if (_message == null)
		{
			throw new NoSuchElementException("Running SystemMsg.packet(Player), but message require arguments: " + name());
		}
		return _message;
	}
}
